### PR TITLE
Automated Changelog Entry for 7.0.0a5 on main

### PR DESCRIPTION
**Pull request by blink1073**
Automated Changelog Entry for 7.0.0a5 on main
```
Python version: 7.0.0a5
npm version: @jupyter-notebook/root: 0.1.0
npm workspace versions:
@jupyter-notebook/app: 7.0.0-alpha.5
@jupyter-notebook/buildutils: 7.0.0-alpha.5
@jupyter-notebook/metapackage: 7.0.0-alpha.5
@jupyter-notebook/application: 7.0.0-alpha.5
@jupyter-notebook/application-extension: 7.0.0-alpha.5
@jupyter-notebook/console-extension: 7.0.0-alpha.5
@jupyter-notebook/docmanager-extension: 7.0.0-alpha.5
@jupyter-notebook/documentsearch-extension: 7.0.0-alpha.5
@jupyter-notebook/help-extension: 7.0.0-alpha.5
@jupyter-notebook/lab-extension: 7.0.0-alpha.5
@jupyter-notebook/notebook-extension: 7.0.0-alpha.5
@jupyter-notebook/terminal-extension: 7.0.0-alpha.5
@jupyter-notebook/tree-extension: 7.0.0-alpha.5
@jupyter-notebook/ui-components: 7.0.0-alpha.5
```

After merging this PR run the "Full Release" Workflow on your fork of `jupyter_releaser` with the following inputs
| Input  | Value |
| ------------- | ------------- |
| Target | jupyter/notebook  |
| Branch  | main  |
| Version Spec | next |
| Since | v7.0.0a4 |

### CODE REVIEW

**Comment by blink1073** [comment]
Cool, looks like that worked, proceeding with release.

**Comment by jtpio** [comment]
Looks like the release did not go through? (the GitHub release is still in draft: https://github.com/jupyter/notebook/releases/tag/untagged-fa85a5b095cdb8696abb)

**Comment by jtpio** [comment]
Looks like this is the "Full Release" run: https://github.com/blink1073/jupyter_releaser/runs/6872746312?check_suite_focus=true ?

```
npm ERR! 404 Not Found - PUT https://registry.npmjs.org/@jupyter-notebook%2fapplication - Not found
```

Maybe this can be restarted if it was a transient issue with npm.

**Comment by blink1073** [comment]
Same issue with this run: https://github.com/blink1073/jupyter_releaser/runs/6882307427?check_suite_focus=true

**Comment by blink1073** [comment]
I think this is the same issue we had in JupyterLab, where we needed to wait for the [packages to be published](https://github.com/jupyterlab/jupyterlab/blob/03046f4d3f1501e1eefcea030261f6774e26c5d3/buildutils/src/publish.ts#L95).

**Comment by blink1073** [comment]
Haha that was easy.  Thanks!

**Pull request merged**
