### PR TITLE
Refactor code duplication of markdown renderers

### PR DESCRIPTION
**Pull request by toonijn**
In textcell.js  and outputarea.js markdown is being rendered. This PR brings the code together in 1 function.

### CODE REVIEW

**Comment by toonijn** [comment]
@Zsailer this is the elimination of code duplication for the markdown renderers. Without a readme-viewer (#5299), this is definitely less necessary. I leave this up to you to judge.

**Comment by Zsailer** [comment]
Thanks, @toonijn! I really appreciate your work here. I'll review this as soon as possible.

**Comment by kevin-bates** [comment]
@toonijn - would you mind rebasing with master?
@Zsailer - if you could give this a look in the near future, that would be awesome.

**Review by kevin-bates — APPROVED** [review]
Sorry for the delay - these changes look good.  Thank you!

**Comment by Zsailer** [comment]
I missed this in initial review, but looks like the following file was moved:
`notebook/static/notebook/js/mathjaxutils.js` → `notebook/static/base/js/mathjaxutils.js`

This causes issues for extensions, i.e. https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator/issues/125

**Comment by toonijn** [comment]
I'm sorry, I didn't realise this impacted the plugins.

**Pull request merged**
