### PR TITLE
Fix notebook scrolling in JupyterLab

### PR DESCRIPTION
**Pull request by blink1073**
cf https://github.com/jupyter/jupyter-js-plugins/pull/105

Also adds more shortcuts and palette items:

screen shot 2016-03-15 at 12 40 24 pm

### CODE REVIEW

**Comment by blink1073** [comment]
cc @SylvainCorlay

**Comment by minrk** [comment]
Nice! Scrolling works, but I can no longer type the letter 'i' in a cell. Any idea what's up there?

**Comment by blink1073** [comment]
Ack!  We'll need another PR to pick up the fixes to the interrupt/restart shortcuts that caused your problem.

**Comment by blink1073** [comment]
Nevermind, I just released a patch version of plugins so anyone updating will get the latest, we can wait for the next round of changes.

**Comment by minrk** [comment]
Awesome, thanks.

**Pull request merged**
