### PR TITLE
[WIP] Convert attachements.js to selenium

### PR DESCRIPTION
**Pull request by Sheshtawy**
This is addressing issue #3335 as part of converting js tests to selenium. This contains the conversion of the file `notebook/tests/notebook/attachments.js`

### CODE REVIEW

**Comment by takluyver** [comment]
Looks like the new file is empty - was that intentional, or did you forget to commit some additions?

**Comment by Sheshtawy** [comment]
Hi @takluyver .. it was intentional to let the team know I'm gonna start working on that.

**Comment by Sheshtawy** [comment]
I'm stuck in something here that I might need some help with. I'm trying to convert attachments and for some reason I keep getting this selenium error when I try to select the `insert image` menuitem and click on it.

```python
selenium.common.exceptions.ElementNotInteractableException: Message: Element <li id="insert_image" class=""> could not be scrolled into view
```

I looked on stackoverflow and several other places and I didn't find anything particularly helpful. @takluyver have you run into something like this before?

**Comment by Sheshtawy** [comment]
nvm. I figured it out

**Comment by takluyver** [comment]
Now you're getting an `ElementNotInteractableException` when you try to click on it. I think the problem is that the menu item isn't visible to click on. I think you'll need to click on the edit menu (`id="edit_menu"`) to show it first, and then click on it.

**Comment by takluyver** [comment]
@Sheshtawy I've rebased and updated this as part of a push to get the Selenium migration back on track. I've worked out the code to upload the image through Selenium. But I haven't completed the test yet. Do you want to finish it up?

(I've force-pushed the branch because I rebased it, so you might have to delete your local copy of the branch and check it out again, to avoid a messy merge. Sorry about that.)

**Comment by Sheshtawy** [comment]
@takluyver apologies for the super delayed response. I would love to finish this up. Thanks for letting me know about the rebase update, I'll keep that in mind

**Comment by blink1073** [comment]
Closing this as stale, please feel free to re-open if you are available to continue working on it @Sheshtawy.

**Pull request closed without merging**
