### PR TITLE
Add Folder for document translation

### PR DESCRIPTION
**Pull request by ChungJooHo**
As you suggested I first add translation folder. And I added my translation 'Readme.md' in Korean.
Thank you for your suggestion. I will steadily update docs.

### CODE REVIEW

**Comment by willingc** [comment]
Thanks!

I'll leave for @jzf2101 to review and merge :-)

**Comment by gnestor** [comment]
Another options is to use a file name convention like `README.ko-KR.md` 👍

**Comment by rgbkrk** [comment]
> Another options is to use a file name convention like README.ko-KR.md

Oh that's true for the base. Then we would just make that folder for the `docs/` translations.

**Comment by ChungJooHo** [comment]
Okay!! Then I will just add folder for translations and rename readme to readme.ko-KR.md :)

**Comment by ChungJooHo** [comment]
But I think making each language folders like docs/transation/ko-KR is more comfortable to access docs .

**Comment by jzf2101** [comment]
@ChungJooHo this is great thanks!

**Pull request merged**
