### PR TITLE
Force the Firefox to recalculate pager content size.

### PR DESCRIPTION
**Pull request by jdfreder**
Ping @minrk , I wonder if the "closes" statement below will automatically close the ipython issue even though it's in another repo.

closes ipython/ipython#8853

### CODE REVIEW

**Comment by jdfreder** [comment]
@sccolbert do you know of a better way to force Firefox's resize handler?  Here I change a DOM attribute, wait for a redraw, then change it back.  I've found that the wait for a redraw is important.

**Comment by sccolbert** [comment]
@jdfreder do you mean force a reflow so you can measure geometry? You can read the `offsetWidth` or `offsetHeight` to do that: https://github.com/phosphorjs/phosphor-dockpanel/blob/549c8c8a37057657467184d2e2e1aba4f1e58bbf/src/index.ts#L1131

Or do you mean something different?

**Comment by jdfreder** [comment]
No, I mean to fool the browser into thinking the page was resized.  What I've done here seems to work, but may not be the best way.

**Comment by jdfreder** [comment]
Found a short way to do it, just resetting html to the current html.

**Comment by sccolbert** [comment]
That will blow-away and re-render all the content. If it's a lot of stuff, that will be expensive. 

That said, you should have to do any trickery to get Firefox to show scroll bars, it should happen automatically when the content changes.  Do you have a small repro?

**Comment by jdfreder** [comment]
> Do you have a small repro?

No I don't, the code is fairly complicated and uses jquery ui animate and resize.  I'm not sure where the problem lies,  but I think it's somewhere in the triangle of getting animate and resize to work well, and the tweaks that accomplish that.

> That will blow-away and re-render all the content. If it's a lot of stuff, that will be expensive.

I'm not worried about the expense of rerending the content in the pager (mostly plain text).  It's the kind of thing that will disappear as we move to the new componentized notebook and it happens at a point in time where it won't affect the user experience.

**Comment by ellisonbg** [comment]
The pager doesn't have lots of data usually and we will be able to do this type of layout much better with phosphor. I am fine with this hack for now and it is documented.

Merging.

**Pull request merged**
