### PR TITLE
use RFC5987 encoding for filenames

### LINKED ISSUE #2742: Download as HTML puts "+" symbols instead of spaces in filename
Using the File > Download > As HTML... command, I would expect the downloaded HTML file to have the same filename as the Jupyter Notebook.

However, every space is replaced by a + symbol.

Versions:
Python 3.6.1
IPython 5.3.0
Jupyter 1.0.0
Windows 10 Pro x64

### PR DESCRIPTION
**Pull request by minrk**
as described in RFC 6266 describing Content-Disposition

This should result in the correct download filename for filenames with spaces and non-latin characters

finishes up #2761
closes #2742

### CODE REVIEW

**Comment by minrk** [comment]
Hold the phone, this doesn't work on Firefox, which apparently doesn't implement RFC 5987

**Comment by takluyver** [comment]
On #2761 you said you've tested this on Firefox. Does that supersede your comment here that it doesn't work?

**Comment by minrk** [comment]
@takluyver yes, sorry. Commenting in two issues. My first attempt didn't work on Firefox, but it does now.

**Comment by takluyver** [comment]
Thanks. Confirmed with a manual test.

I'd be in favour of putting this in 5.1, but if we're not confident enough it's fine to bump it to 5.2.

**Comment by minrk** [comment]
It worked for me, but the tiniest typo while I was figuring this out caused pretty weird failures that different browsers handled differently, so I'd be okay merging right after 5.1.

**Comment by gnestor** [comment]
I tested and I'm still seeing filenames with pluses vs. spaces?

**Comment by gnestor** [comment]
Ok, nevermind. I guess that I was not using a develop version of notebook or something. Looks good to me! 

@minrk What do you think about merging this with 5.1 now? Feel free to mark as 5.2 otherwise.

**Comment by minrk** [comment]
Let's be conservative and call it 5.2

**Pull request merged**
