### PR TITLE
Upgrade Codemirror to 5.18

### PR DESCRIPTION
**Pull request by gnestor**
Implements https://github.com/jupyter/notebook/issues/1686

### CODE REVIEW

**Comment by gnestor** [comment]
@jasongrout I've enabled "allow edits from maintainers" so feel free to contribute to this PR.

**Comment by minrk** [comment]
@gnestor what's WIP here? looks good to go, here (I've done this same bump previously while tracking down an unrelated bug, and didn't encounter any issues).

**Comment by gnestor** [comment]
@minrk Just wanted to make sure... I'm not sure what all depends on Coremirror. Feel free to merge 👍

**Comment by minrk** [comment]
Thanks! Codemirror issues caused by minor updates are generally rare / weird edge cases, so the main way we have to test is getting it in the hands of people running on master.

**Pull request merged**
