### PR TITLE
russian i18n - 100%

### PR DESCRIPTION
**Pull request by krote5k**
nbui.po - 100%
nbjs.po - 100%
notebook.po - 100%

### CODE REVIEW

**Comment by kevin-bates** [comment]
Thank you for this great contribution.  I'm adding a WIP label until you feel its at a merge point.

It would be **much appreciated** if others could review the translations as well!

**Comment by krote5k** [comment]
nbui.po - 100%
nbjs.po - 30%
notebook.po - 35%

**Comment by krote5k** [comment]
nbjs.po - 100%

**Comment by kevin-bates** [comment]
Hi @krote5k - I've removed the WIP label with the assumption that this PR is ready for review.  Thank you for adding this!

**Pull request merged**
