### PR TITLE
remove clusters tab from notebook

### LINKED ISSUE #85: Proposal: Move clusters tab to ipyparallel
I think we should ship it as a notebook server extension in ipyparallel, rather than keep it in the notebook code.

### PR DESCRIPTION
**Pull request by minrk**
moving to an nbextension in ipyparallel

closes #85

### CODE REVIEW

**Comment by Carreau** [comment]
+1, I suppose you want to merge that in sync with #11

**Comment by minrk** [comment]
In the absence of ipyparallel, there is now a placeholder Clusters tab that points for ipyparallel, rather than removing the tab altogether with no hints.

**Comment by Carreau** [comment]
@minrk Want to rebase ? And once test passes. I'll merge the 2 PR at the same time.

**Comment by minrk** [comment]
Rebased.

**Pull request merged**
