### PR TITLE
Don't url escape filenames on download

### PR DESCRIPTION
**Pull request by gnestor**
Closes https://github.com/jupyter/notebook/issues/2742

### CODE REVIEW

**Comment by takluyver** [comment]
This looks fine to me, but I'd like @minrk to have a quick look too. I notice you've also marked it for 5.2, so we should release 5.1 before merging it.

**Comment by gnestor** [comment]
We can fit this in 5.1 as long as we're confident that this won't break anything else! 😮

**Comment by minrk** [comment]
This solves a problem for spaces in ascii names but reintroduces a problem for non-ascii names.

Test with a filename like 'üni spåce™' to be sure it's working.

**Comment by minrk** [comment]
Some diagnoses:

1. the `+` was introduced by using the wrong escape function (`tornado.escape.url_escape`, which is for URL query parameters by default, not url components)
2. Putting a name in quotes means it shouldn't be escaped, but it also has to be Latin-1 if you do that.
3. [RFC 6266](https://tools.ietf.org/html/rfc6266) explains how to specify filename encodings properly (url escapes were the right thing to do, we just did them wrong)

#2767 should implement filename encoding correctly. I've tested it on Safari, Chrome, and Firefox.

**Comment by takluyver** [comment]
Closing in favour of #2767.

**Pull request closed without merging**
