### PR TITLE
Make split cell match mark state of origin

### LINKED ISSUE #648: Split cell leave one cell marked.
I don't think that is intended.

### PR DESCRIPTION
**Pull request by jdfreder**
closes #648
alternative #654

### CODE REVIEW

**Comment by jdfreder** [comment]
Personally, I prefer this to #654, especially when couple with a hotkey to unmark all.

**Comment by blink1073** [comment]
:+1: for this version.

**Comment by minrk** [comment]
+1, esp. if you fix the commit to only include the actual code change.

**Comment by jdfreder** [comment]
> +1, esp. if you fix the commit to only include the actual code change.

Fixed :)  Stupid atom whitespace package - on a new install of atom.

**Comment by ellisonbg** [comment]
I like this approach. Let's wait on the keyboard shortcut for unmarking all. There is a command for that that users can access from the palette.

**Comment by jdfreder** [comment]
@ellisonbg see #657

**Comment by ellisonbg** [comment]
@Carreau or @minrk - I am +1 on merging this rather than the alternative #654 - thoughts?

**Comment by Carreau** [comment]
I'm fine with this. 

No strong feeling on this vs #654

**Comment by Carreau** [comment]
Oh... self merge :-)

**Comment by jdfreder** [comment]
> self merge :-)

Not `self.merge`, `this.merge` ;)

**Pull request merged**
