### PR TITLE
replace jupyter_nbformat by nbformat

### PR DESCRIPTION
**Pull request by Carreau**
Also replace the `import nbformat as nbformat` by `import nbformat`
and change the name of the installed egg.

### CODE REVIEW

**Comment by Carreau** [comment]
Hopefully this will fix travis faillures.

**Comment by minrk** [comment]
I think this will work after jupyter/nbconvert#19 is merged.

**Comment by minrk** [comment]
poking travis now that nbconvert is updated.

**Comment by Carreau** [comment]
Travis happy.

**Comment by minrk** [comment]
Thanks.

**Pull request merged**
