### PR TITLE
Upgrade bower dependencies

### PR DESCRIPTION
**Pull request by gnestor**
Follow up from https://github.com/jupyter/notebook/issues/1227

This upgrades xterm.js and codemirror dependencies in bower.json. 

I also removed the codemirror patch code in favor of installing codemirror from a fork repo because it seems like it will be easier to maintain that way (and it’s slightly less of a hack). Using the patch code, it isn’t obvious to any contributor except myself which part of codemirror needs patched and this patching needs to happen every time that codemirror is upgraded. Using a fork repo, we can simply rebase the patch branch to the most recent release commit on codemirror and replay the patch commit over it. For efficiency’s sake. the fork is under my name, but I can transfer it to the jupyter org or any other contributor can fork codemirror themselves and perform the same patch on their own branch.

### CODE REVIEW

**Comment by takluyver** [comment]
Thanks @gnestor . Looks like there's an issue on CI with building the JS with your codemirror fork.

**Comment by takluyver** [comment]
Also, have we re-tested for the issue with the latest Codemirror? It might have been fixed, in which case we could drop our patch.

**Comment by gnestor** [comment]
I tested vanilla codemirror 5.27.2 and I can't reproduce any of those bugs from https://github.com/jupyter/notebook/issues/1967. I tested in Safari and Chrome. Can you give it a try to double-check?

**Comment by takluyver** [comment]
I'll have a go with it, but I think that bug only ever affected Safari, so I can't check for it. If we can get another Mac user to test and find it working, I'd say ship the vanilla version and cross our fingers.

**Comment by takluyver** [comment]
I had a very brief play with it in Firefox, it seems to be working OK.

**Comment by gnestor** [comment]
Ya, it looks good to me too. Merge at will 👍

**Comment by takluyver** [comment]
I'd like to get one more safari user (or at least, someone with a Mac who can run Safari) to try to reproduce #1967 while we're still thinking about it before we merge, because it will be harder to find the necessary information if it's reported again in a few weeks.

**Comment by gnestor** [comment]
Ok, @rgbkrk or @minrk, could you check this out and test for codemirror single-space bugs (https://github.com/jupyter/notebook/issues/1967) in Safari?

**Comment by takluyver** [comment]
OK, let's merge this and hope that the problem is gone.

**Pull request merged**
