### PR TITLE
Update enforce-label.yml

### PR DESCRIPTION
**Pull request by colleenpridemore**
added suggested code from REST API in docs

### CODE REVIEW

**Comment by colleenpridemore** [comment]
REST API code snippet removed.  Back at square one.

**Comment by jtpio** [comment]
Hey @colleenpridemore, would you mind providing more context for this change?

It looks like the PR might have been opened by mistake?

**Comment by colleenpridemore** [comment]
Yes, I'm really having difficulty determining what happened and how to fix it.  I'm open to any suggestions you may have.

**Comment by colleenpridemore** [comment]
All I know is I had some codespaces open, I wasn't here for a week and now i've came back to this.

**Pull request closed without merging**
