### PR TITLE
Don't pass destination when installing nbextension from Python package

### PR DESCRIPTION
**Pull request by takluyver**
Closes gh-1401

### CODE REVIEW

**Comment by ellisonbg** [comment]
I have tested this against master of ipywidgets and it seems to fix it. @SylvainCorlay @jdfreder How are you even getting ipywidgets to work at all without this fix?

**Comment by SylvainCorlay** [comment]
I have not looked at it closely, but in any case, you don't need to install the `widgetsnbextension` nbextension for a non-dev install. The assets are parts of the wheel.

**Comment by ellisonbg** [comment]
Ahh, got it...

On Thu, Apr 28, 2016 at 8:58 PM, Sylvain Corlay <notifications@github.com>
wrote:

> I have not looked at it closely, but in any case, you don't need to
> install the widgetsnbextension nbextension for a non-dev install. The
> assets are parts of the wheel.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/pull/1403#issuecomment-215621014>
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by nastasi-oq** [comment]
The ipywidget installation works fine with this branch, tnx.

**Comment by minrk** [comment]
@nastasi-oq thanks!

**Pull request merged**
