### PR TITLE
Update link to developer documentation

### PR DESCRIPTION
**Pull request by captainsafia**
Link in the README should like to the specific "Contributing to Code" section in the docs.

cc: @willingc

### CODE REVIEW

**Comment by takluyver** [comment]
Or is this page more helpful?
http://jupyter-notebook.readthedocs.org/en/latest/development_js.html

**Comment by captainsafia** [comment]
Erm. This is not the thing I was trying to convey.

Gimme 2 seconds

giphy

**Comment by captainsafia** [comment]
OK. _This_ is the thing I wanted to do.

We should have a link to the actual contributing documentation in the README as opposed to the JavaScript compilation/setup document.

**Comment by takluyver** [comment]
:+1:

**Comment by willingc** [comment]
Looks good! Thanks @captainsafia and @takluyver. :sunny:

**Pull request merged**
