### PR TITLE
Make notebook 6.5.x point to nbclassic static assets

### PR DESCRIPTION
**Pull request by ericsnekbytes**
This makes notebook use the `static` assets of `nbclassic`, so both use the same physical files for future frontend development. Main changes (still being refined) are:

- Change the DEFAULT_STATIC_FILES_PATH in `__init__` to point to nbclassic/static folder
- Delete the `static/` folder from `notebook`
- Remove static file build/related logic from setup system (`nbclassic` will do this itself, we don't need the logic here anymore)
- Remove JS tests from CI (those tests are covered in nbclassic)

_Note that this PR involves removing static frontend JS/CSS files from notebook and obtaining those instead from nbclassic, it does not remove the handlers and other logic, those are still in place._

### CODE REVIEW

**Comment by echarles** [comment]
I have installed locally this branch and launching `jupyter notebook` I receive

```
  File ".../jupyter-notebook-classic/notebook/__init__.py", line 29, in <module>
    from notebook.nbextensions import install_nbextension
ModuleNotFoundError: No module named 'notebook.nbextensions'
```

**Review by echarles — APPROVED** [review]
Epic PR @ericsnekbytes Tested locally and looks good. Checked the diff. CI failures were also shown before on 6.4.x branch. Will merge. Thx again!

**Comment by echarles** [comment]
@ericsnekbytes I have reviewed and approved. Can you undraft so I can merge? Thx,

**Comment by ericsnekbytes** [comment]
> @ericsnekbytes I have reviewed and approved. Can you undraft so I can merge? Thx,

Ready!

**Pull request merged**
