### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by kant**
(proposal)

### CODE REVIEW

**Comment by takluyver** [comment]
Maybe use `*asterisks for italics*` rather than backticks. The meaning of backticks is configurable in rst, and in some of our docs we configure it to mean inline code.

**Comment by kant** [comment]
Understood!

**Comment by takluyver** [comment]
Ping? If you've got a moment to switch it to asterisks, I'm happy to merge this.

**Comment by takluyver** [comment]
I made the change myself to tidy this up.

**Pull request merged**
