### PR TITLE
Fix a dead link to example notebooks

### PR DESCRIPTION
**Pull request by brettcannon**

### CODE REVIEW

**Comment by brettcannon** [comment]
The test failures don't seem to have anything to do with my change from what I can tell.

**Comment by willingc** [comment]
@brettcannon You are correct. Your change is a good one :D 

FYI, @minrk @Carreau

**Comment by Carreau** [comment]
> @brettcannon You are correct. Your change is a good one :D
> 
> FYI, @minrk @Carreau

Yeah, travis might be grumpy, I asked him to rerun failing test I'll merge once they go green.

**Comment by minrk** [comment]
Thanks!

**Pull request merged**
