### PR TITLE
Updated Dockerfile for widgetsnbextension

### LINKED ISSUE #1114: The docker file should also install python2 widgetsnbextension
Please add this line:
pip2 install widgetsnbextension
after
pip3 install widgetsnbextension

So it won't generate 404 error:

404 GET /nbextensions/widgets/notebook/js/extension.js

### PR DESCRIPTION
**Pull request by brandles**
Closes #1114.

cc: @captainsafia

### CODE REVIEW

**Comment by takluyver** [comment]
@jdfreder is this right? It seems like the nbextension stuff should only need to be installed once, so I'm not sure if #1114 correctly identified the cause of the issue.

Looking at the widgetsnbextension wheel on PyPI, it refers to a `static/` data directory which is not in fact anywhere in the package.

**Comment by rgbkrk** [comment]
@takluyver They both need the kernel side python code though right? Not just the frontend assets?

**Comment by minrk** [comment]
Yeah, and `widgetsnbextension` should only be notebook-side, right? That's the point of it?

**Comment by jdfreder** [comment]
Hey, don't know why I didn't see this ping, sorry.  `widgetsnbextension` is the nbextension for widgets, which is language agnostic.  `ipywidgets` is the Python backend.

This fix should not be needed now - ipywidgets depends on widgetsnbextension.

**Pull request merged**
