### PR TITLE
fix login page CSS

### LINKED ISSUE #469: UI problem
Hi, there is a small UI problem in login page that the height of `<div id="site" style="display: block; height: 596px;">` is not necessary and it's cause the scrollbar displayed.
qq 20150921160110

### PR DESCRIPTION
**Pull request by Jeffiy**
closes #469

### CODE REVIEW

**Comment by minrk** [comment]
@Jeffiy I see you have a merge commit from upstream. Would it be possible for you to rebase this branch to remove that? If not, it's okay, but we would prefer to avoid the extra merge.

**Comment by Jeffiy** [comment]
@minrk but I don't know how to rebase it, could you tell me how to rebase? thanks.

**Comment by minrk** [comment]
Thanks!

**Comment by Carreau** [comment]
The way you rebase usually is the following:

```
$ git rebase -i origin/master
```
Editor open with the list of commits
```
pick 1fb2288 Edit see also box in doc
pick 86b9b0b set dirty flag on kernelspec/language_info changes
pick c9a9b5b don't overwrite file
pick ac509bc fix login page UI problem
```

You delete the lines of the commit you don't want, (follow the instructions)
save and quit editor.

```
$ git rebase -i origin/master
Rebasing  (9/15) # updates while rebasing
Successfully rebased and updated <your branch>
```

If there are conflicts it will tell you "conflict in ....", you edit the file(s) to resolve conflict, git add the files, and then `git rebase --continue` a conflict look like that

```
<<<<<<<< fix these -> this
THere is 2 conflicts in this sentence
=======
There is 2 conflits in these sentence
>>>>>>>> Lowercase H
````

As a human you know how to merge the two, and delete the `<<<<<`,`>>>>>`,`======`. Anyway rebase might look scary, it is not, you can alway get back on your feet.

**Comment by Jeffiy** [comment]
@Carreau Thanks!

**Pull request merged**
