### PR TITLE
enable logout button on terminal page

### LINKED ISSUE #1708: Logout button doesn't work on a terminal page
Click the logout button on a terminal page or nbextensions page. but nothing happens. The pages include:

http://jupyter_host/terminals/1
http://jupyter_host/nbextensions (if jupyter_contrib_extensions installed)

It work well on other pages. e.g. tree, folder, notebook page.

### PR DESCRIPTION
**Pull request by minrk**
closes #1708

### CODE REVIEW

**Comment by gnestor** [comment]
@minrk I assume this logout button is only visible on JupyterHub? Is there anyway I can test this locally?

**Comment by minrk** [comment]
You can set a password on the regular notebook:

Generate a hashed password:

```python
from notebook.auth import passwd
passwd('P@$$w0rd')
```

and store it in `c.NotebookApp.password` in your jupyter_notebook_config.py

**Comment by gnestor** [comment]
@minrk I set up a notebook password as described, but how do I test this? I am not prompted for a password... I don't see a login/logout button...

**Comment by gnestor** [comment]
I tested it logout button now works in a terminal page. Merging...

**Pull request merged**
