### PR TITLE
changes for 4.2.1

### PR DESCRIPTION
**Pull request by minrk**
With this, I can release 4.2.1 this evening.

cc @SylvainCorlay, @willingc, @JamiesHQ

### CODE REVIEW

**Comment by takluyver** [comment]
:+1:

**Comment by SylvainCorlay** [comment]
:+1:

**Comment by willingc** [comment]
Looks good. Perhaps in a future release, we can start moving toward adding pr/issue numbers to the bullets.

**Comment by Carreau** [comment]
things like #1490 (if the right fix)  should really go into notebook soon, as all the extensions since 4.2 are broken.

**Comment by Carreau** [comment]
> things like #1490 (if the right fix) should really go into notebook soon, as all the extensions since 4.2 are broken.

And all non-python kernels have no highlighting.

**Comment by minrk** [comment]
@Carreau good call. I'll cut 4.2.1 now, and we can do 4.2.2 with #1490 next week.

**Pull request merged**
