### PR TITLE
Add "official" documentation statement and links to Jupyter Universe documentation

### PR DESCRIPTION
**Pull request by willingc**
1. Added a sentence at the start of the documentation re: this is "official" documentation. Hoping to avoid some of the confusion with other documentation on rtd.
  screen shot 2015-12-22 at 6 03 04 pm

2. Added to left sidebar links to the documentation of many Jupyter and IPython projects. 
Three big advantages:
  a. Search within the RTD doc will bring up the link to another Jupyter project. (i.e. a search for JupyterHub would hit on, at minimum, the JupyterHub documentation link)
  screen shot 2015-12-22 at 11 08 14 am

  b. Easy interim step, that may help users as well as devs, as we iterate on the overall documentation strategy.
  c. Easy to propagate to other Jupyter projects' documentation either in a custom theme or manually (at least initially).

  **Left sidebar and links**
  screen shot 2015-12-22 at 6 03 31 pm
  **Left sidebar**
  screen shot 2015-12-22 at 6 03 50 pm

### CODE REVIEW

**Comment by Carreau** [comment]
I would trim this list down a lot (personal opinion) :
  - 3 docker-* repos (not really active)
  - Notebook legacy docs are too much indexed by google, remove the link. 
  - IPython-* are IPython specific, I'm not sure we want the here. 
  - Traitlets maybe too much too.
  - tmpnb is really unlikely to be useful. 

I'm wondering if there is a way to but that in a package, and require it in all docs instead of having to update in N places.

**Comment by willingc** [comment]
@Carreau Thanks for the review and comments. I'll try to give some perspective inline on what my thinking was for inclusion. We can certainly iterate from there :-)

> I would trim this list down a lot (personal opinion) :

I would too. Yet, the growth of repos has made it difficult (particularly for a user of the projects) to see the breadth of projects that they may run across in their use of Jupyter. We do have this [subprojects](https://jupyter.readthedocs.org/en/latest/subprojects.html) page in the Jupyter docs (which is different than the Jupyter notebook docs). The list of projects essentially come from that page. The additions are the docker repos and IPython/traitlets.

>    3 docker-* repos (not really active)
>    Notebook legacy docs are too much indexed by google, remove the link.
>    IPython-* are IPython specific, I'm not sure we want the here.

The inclusion of these were prompted by an issue that @fperez filed https://github.com/jupyter/jupyter/issues/87 after reading a blog post by G. Dumpleton on OpenShift, Docker, IPython and Jupyter. A [second blog post](http://blog.dscpl.com.au/2015/12/random-user-ids-when-running-docker.html) came out yesterday.

>    Traitlets maybe too much too.

No strong objections from me on removing.

>    tmpnb is really unlikely to be useful.

You are likely correct, but I think that users have a name association with tmpnb so I don't think there is real harm of leaving it in.

> I'm wondering if there is a way to but that in a package, and require it in all docs instead of having to update in N places.

Agreed. I am pretty confident that a custom Sphinx theme based off the RTD theme will enable us to do this. 

:evergreen_tree: Ultimately, I would love to see a pretty docs landing page at Jupyter.org that visually displays the projects and links easily to the individual documentation. That would take longer to implement since it would need design work, strategic input on which projects, and development. I was hoping to implement this PR in jupyter/notebook and jupyter/jupyter docs as an interim step to at least give us the opportunity to begin referring to the front page of each of those docs as a gateway to most of the docs. It truly is an interim step but one that I think has benefits in the short term, especially since there will be eyeballs on both sets of docs when 4.1 is officially released :-)

I'm open to thoughts and other ideas for now or down the road. :bulb: 

cc/ @ellisonbg

**Comment by willingc** [comment]
Logo added to Jupyter Sphinx RTD theme

screen shot 2015-12-24 at 7 08 32 pm

**Comment by takluyver** [comment]
I'm not sure about the white square, though I don't think the logo would look right on a blue background either.

**Comment by Carreau** [comment]
> I'm not sure about the white square, though I don't think the logo would look right on a blue background either.

We might want a cutout version of the logo which have a white border al around it.

**Comment by willingc** [comment]
Thanks for the feedback @takluyver and @carreau. I'm playing around with ideas on this PR. Feel free to share other ideas - things you would like to see in a custom RTD theme. Going to work on getting the project links into a sidebar template. Been looking at Astropy, Numpy, SciPy, IPython, Django and a few other sites for ideas. If you have some favorite docs, drop a note here and I will check them out too.

**Comment by fperez** [comment]
Since the work of a full "Jupyter theme" is IMO out of scope (great to have, but I'd rather we focus our energy for now on docs structure and content), an idea might be to put a thick frame/border around our Jupyter and IPython logos in the doc pages, that might ease the visual transition. 

If the frame colors are more in line with those of the theme, it may help contain the logo items, that  by necessity may have their own colors that are somewhat different from the surrounding theme.

Just a thought looking for a quick solution so we can focus on content :)

**Comment by willingc** [comment]
@fperez Agreed. Good suggestion re: border transition. I think we're on the same page re: priorities.

When I say theme, I'm less focused on design (since that's not my strength) and more on content/structure. Things like:
- simpler access to installation instructions for operating systems (see Astropy example)
- easy access to the breadth of documentation/project links (see Django example)
- Easy download of PDFs of documentation by project and/or versions and access to further help (see SciPy example)
- Prominent access to notebook viewer (one of the most powerful features of the IPython documentation from a user group perspective) and examples (notebook gallery) (see IPython example)

## Plan
0. ASAP Highest priority - Have at least one location where all documentation can be accessed easily. This will likely be interim in terms of design but important to have as a start toward integrating the docs that live in different repos yet the user may wish to access easily while setting up their environment and workflows.
1. come up ASAP with a standard ``conf.py`` (sidebars, links) and ``index.rst`` (consistent table of contents structure for a project) templates for existing and new documentation on RTD (These two files are what I'm referring to as a standard Jupyter theme or more simply Jupyter doc standard.)
2. Revisit ipynb examples and use of ``pandoc`` or other third party Sphinx extensions to better display rendered notebooks on RTD.
3. Add cross reference links to help end users navigate between common configuration scenarios that span multiple projects (i.e. jupyterhub, nbgrader) or (docker, notebook).

@fperez, @ellisonbg Please let me know if you have different priorities. I'm working under the assumption that we're doing doc triage and incremental changes to RTD hosted docs now moving over time to a more visually appealing design for docs to coincide with 5.0 if not sooner.

## Examples from other projects
- simpler access to installation instructions for operating systems (Astropy):
screen shot 2015-12-25 at 5 46 17 pm
- easy access to the breadth of documentation/project links (Django)
screen shot 2015-12-25 at 5 49 01 pm
screen shot 2015-12-25 at 5 49 33 pm
- Easy download of PDFs of documentation by project and/or versions (SciPy)
screen shot 2015-12-25 at 5 52 54 pm
- Prominent access to notebook viewer (one of the most powerful features of the IPython documentation from a user group perspective) and examples (notebook gallery) (IPython)
screen shot 2015-12-25 at 5 55 34 pm

**Comment by fperez** [comment]
On Fri, Dec 25, 2015 at 6:22 PM, Carol Willing <notifications@github.com>
wrote:

> @fperez <https://github.com/fperez> Agreed. Good suggestion re: border
> transition. I think we're on the same page re: priorities.
>
> When I say theme, I'm less focused on design (since that's not my
> strength) and more on content/structure. Things like:
>
>    - simpler access to installation instructions for operating systems
>    (see Astropy example)
>    - easy access to the breadth of documentation/project links (see
>    Django example)
>
>
Agreed.


>
>    - Easy download of PDFs of documentation by project and/or versions
>    and access to further help (see SciPy example)
>
>
While very valuable long-term, I'd put below the others in priority for
now, unless our build chain is in such good shape that it doesn't take much
work. I think for now, having good HTML docs is the main priority.  Someone
from the community could help with the technical tooling for clean PDF
builds, but I'd much rather your talents go towards thinking about content
and structure to help the users navigate their way around the project.


>
>    - Prominent access to notebook viewer (one of the most powerful
>    features of the IPython documentation from a user group perspective) and
>    examples (notebook gallery) (see IPython example)
>
> Yup, along with what those examples illustrate, how they play with the
rest of the docs, eliminating redundancy, etc.  That's where we've fallen
so badly behind.


>
>
> Plan
>
>    1. ASAP Highest priority - Have at least one location where all
>    documentation can be accessed easily. This will likely be interim in terms
>    of design but important to have as a start toward integrating the docs that
>    live in different repos yet the user may wish to access easily while
>    setting up their environment and workflows.
>    2. come up ASAP with a standard conf.py (sidebars, links) and index.rst
>    (consistent table of contents structure for a project) templates for
>    existing and new documentation on RTD (These two files are what I'm
>    referring to as a standard Jupyter theme or more simply Jupyter doc
>    standard.)
>    3. Revisit ipynb examples and use of pandoc or other third party
>    Sphinx extensions to better display rendered notebooks on RTD.
>    4. Add cross reference links to help end users navigate between common
>    configuration scenarios that span multiple projects (i.e. jupyterhub,
>    nbgrader) or (docker, notebook).
>
> @fperez <https://github.com/fperez>, @ellisonbg
> <https://github.com/ellisonbg> Please let me know if you have different
> priorities. I'm working under the assumption that we're doing doc triage
> and incremental changes to RTD hosted docs now moving over time to a more
> visually appealing design for docs to coincide with 5.0 if not sooner.
>

This sounds very reasonable. I'm sure along the way, you'll find lots of
inconsistencies, circular links, dead-ends, etc.  But precisely having your
lead on this problem will let us finally make progress on this mess, thanks
so much :)

f


-- 
Fernando Perez (@fperez_org; http://fperez.org)
fperez.net-at-gmail: mailing lists only (I ignore this when swamped!)
fernando.perez-at-berkeley: contact me here for any direct mail

**Comment by willingc** [comment]
Closing this PR since much of it has been covered in other doc PRs.

**Pull request closed without merging**
