### PR TITLE
Update ruff config

### PR DESCRIPTION
**Pull request by blink1073**
Use updated recommendations for Ruff [config](https://learn.scientific-python.org/development/guides/style/#ruff), and the new ruff [`docstring-code-format`](https://astral.sh/blog/ruff-v0.1.8#formatting-code-snippets-in-docstrings) that replaces `blacken-docs`.

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks!

The UI tests failure might be relevant? Unless it is caused by a new release of an underlying package?

**actual (extra home icon)**

image

**expected**

image

**Comment by blink1073** [comment]
I addressed that failure, but it looks like there is a pre-existing race condition, because this firefox test failed with the same error as this chromium test did: https://github.com/jupyter/notebook/actions/runs/7198343749/job/19607743050

**Comment by jtpio** [comment]
Thanks!

Is this the same error? Now the issue seems to be related to the trusted indicator not being displayed correctly:

**Actual**

image

**Expected**

image

But this is likely not related to this PR, as it also happens in https://github.com/jupyter/notebook/pull/7191 now.

**Review by jtpio — APPROVED** [review]
Thanks!

**Pull request merged**
