### PR TITLE
Update webpack and eslint config

### PR DESCRIPTION
**Pull request by gnestor**
Improve source maps and decrease eslint warnings

### CODE REVIEW

**Comment by Carreau** [comment]
+1 to do that !

**Comment by gnestor** [comment]
It looks like all the checks failed! 😮 @Carreau Can you tell why?

**Comment by Carreau** [comment]
I'll have a look. 

Sorry 'm usually more responsive, but I had a lot of things that coulnd't that took priority.

It seem to be 3 of [these lines](https://github.com/jupyter/notebook/blob/master/setupbase.py#L124-L130) that try to ensure at install time that the `.maps` files are built.

**Comment by Carreau** [comment]
https://github.com/gnestor/notebook/pull/1 shoudl fix the build.

**Comment by gnestor** [comment]
@Carreau To make sure I understand: The checks were failing because I switched from `source-map` to `inline-source-map`?

**Comment by Carreau** [comment]
Yes, building the python package was failing to include the map files that
where explicitely included.

It's not obvious from the log, as there is this weird combination of python
calling npm.

The error messages are probably due to some extra-cleverness from
setuptools of trying to figure out what went wrong in previous command.

**Comment by gnestor** [comment]
"Checks have passed!"

**Comment by Carreau** [comment]
> "Checks have passed!"

Aka: Travis is Happy.

@minrk , this inline the maps if we release it,  and make the files bigger, do you know of anyone that would be strongly affected on the hub side by these changes and would complain ?

**Comment by gnestor** [comment]
@Carreau @minrk If inline maps prove to be an optimization issue in production, we can conditionally set the `sourcemap` config based on the `NODE_ENV` (e.g. `inline-source-map` for `development` and `source-map` for `production`). However, this may over-complicate things for `setupbase.py` and Travis.

**Comment by rgbkrk** [comment]
:shipit:

**Comment by minrk** [comment]
@Carreau I wouldn't expect any complaints about the size due to including maps.

**Pull request merged**
