### PR TITLE
Adjust tags UI styling

### PR DESCRIPTION
**Pull request by vidartf**
Adjust styling of tags UI according to #2205.

Most of the asked changes are in, but I'm not sure if there is a standard way in this repo to style things in order to get rid of focus highlighting on input, or if I should simply write out the CSS:
```css
.tags-input input[type=text]:focus {
    outline: none;
    box-shadow: none;
    border-color: #ccc;
}
```

### CODE REVIEW

**Comment by vidartf** [comment]
Preview: 
tags-review

**Comment by Carreau** [comment]
> Most of the asked changes are in, but I'm not sure if there is a standard way in this repo to style things in order to get rid of focus highlighting on input

I don't think there is. Your snippet looks fine. Do you want to add in this PR or in a subsequent one ?

**Comment by vidartf** [comment]
I think I have a working copy of that, which I can commit to this PR
tomorrow.

**Comment by takluyver** [comment]
@vidartf don't forget to commit & push that.

**Comment by vidartf** [comment]
Thanks for the reminder, just pushed it :)

**Comment by Carreau** [comment]
> Thanks for the reminder, just pushed it :)

Sweet ! Thanks !

**Comment by Carreau** [comment]
@ellisonbg how does master looks for you now ?

**Comment by ellisonbg** [comment]
Just tested and it looks great! I did submit a super minor PR that fixes a few minor things: #2230 

Once that PR is merged, I think the cell tags are set to go. Very happy to see these!

**Pull request merged**
