### PR TITLE
Added metrics for currently running terminals and labeled by type kernels

### PR DESCRIPTION
**Pull request by Hyaxia**
Moved the 'metrics' file to a new package named 'promethues'.
Then split the file into two files, one containing the metrics themselves, the other containing any function that have something to do with prometheus.

Finally, Added new metrics into the prometheus.metrics file that represent the number of running terminals and added the functionality for that metric to be recorded in the terminal.api_handlers file.

relevant issue #3682

### CODE REVIEW

**Comment by Hyaxia** [comment]
Its wierd that it failed...
All i have changed way the python code and I am able to run the jupyter notebook perfectly fine...
All of the errors say that it has failed running `python -m notebook.jstest notebook`, no idea why that is...
Can anyone explain?

**Comment by Hyaxia** [comment]
Feels like the problem is not with my code but rather the way i uploaded the changes...
Can anybody explain me how to do it in the right way? there is no reason for this error to occur because of my code... (or atleast i cant find one)

**Comment by Carreau** [comment]
I've pushed the fix of #4039 to your branch to hopefully fix the test suite.

**Comment by blink1073** [comment]
LGTM, thanks!

**Pull request merged**
