### PR TITLE
Add releaser workflows

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Comment by blink1073** [comment]
I set up the appropriate permissions and tokens for the bot.

**Comment by jtpio** [comment]
Attempting to make a release with the new workflows and facing the following issue:

```

***github.com/jupyter/notebook.git
remote: error: GH006: Protected branch update failed for refs/heads/main.
remote: error: Changes must be made through a pull request. Required status check "tests_check" is expected.
```

I don't know if this check is new but I will disable for now to finish the release.

**Comment by jtpio** [comment]
Strangely a release commit and a tag have been pushed to the repo:

image

But it does not appear on the main branch:

image

Which makes the Publish Release workflow fail because the tag already exists.

I'll try deleting the tag and restart the workflow.

**Comment by jtpio** [comment]
Looks like it went through after disabling the branch protection rule: https://github.com/jupyter/notebook/releases/tag/v7.0.0a11

For more information the workflow runs are available here: https://github.com/jupyter/notebook/actions/workflows/publish-release.yml

**Comment by blink1073** [comment]
I adjusted the permissions of the bot account and reinstated the branch protection rules.

**Pull request merged**
