### PR TITLE
Added description text to setup.py to resolve #374

### LINKED ISSUE #374: Package have no description on PyPI
I think @willingc was looking for docs to do while traveling.

Marking as sprint friendly.

### PR DESCRIPTION
**Pull request by captainsafia**
cc/ @Carreau

### CODE REVIEW

**Comment by minrk** [comment]
@captainsafia thanks! Can you add a short `long_description` as well? A very brief summary of what it is and a restructured-text link to https://jupyter-notebook.readthedocs.org should do it, I think.

**Comment by captainsafia** [comment]
@minrk — check it out now!

**Comment by ellisonbg** [comment]
Perfect, merging!

**Comment by captainsafia** [comment]
giphy-3

**Comment by ellisonbg** [comment]
:-)

On Wed, Sep 9, 2015 at 6:43 PM, Safia Abdalla <notifications@github.com>
wrote:

> [image: giphy-3]
> <https://cloud.githubusercontent.com/assets/1857993/9778236/a349d870-5722-11e5-9cef-a8d7c322c758.gif>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/pull/408#issuecomment-139091597>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Pull request merged**
