### PR TITLE
Add a banner and log to information about the migration to Notebook 7 plan

### PR DESCRIPTION
**Pull request by echarles**
Contribues to https://github.com/jupyter/nbclassic/issues/214

### CODE REVIEW

**Comment by echarles** [comment]
Closing/reopening to trigger CI

**Comment by RRosio** [comment]
LGTM, Thank you @echarles!

**Comment by echarles** [comment]
Thx @RRosio for the review and merge.

**Comment by echarles** [comment]
> Is there a way to prevent rendering this notice in the web page as a server administrator?

There is not such thing today. Could you open a dedicated issue for that?

**Pull request merged**
