### PR TITLE
Fix readthedocs environment

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Comment by frenzymadness** [comment]
Would it make sense to add it also [here](https://github.com/jupyter/notebook/blob/master/setup.py#L129)?

**Comment by blink1073** [comment]
@frenzymadness, thanks for the heads up!  I made this PR from the web UI so I can't edit other files, would you like to submit a separate PR to make that change?

**Comment by frenzymadness** [comment]
Will do it in a moment.

**Comment by frenzymadness** [comment]
See https://github.com/jupyter/notebook/pull/6021

**Pull request merged**
