### PR TITLE
Update notebook docs based on @carreau suggestions

### PR DESCRIPTION
**Pull request by willingc**
Closes #1250 #1251 #1252

I think this incorporates all the desired changes that @carreau wanted in these issues and PRs:

- Removed rst versions of notebooks
- notebooks build using nbsphinx
- Removed the Examples index notebook and replaced with a rst version since linking from notebook to notebook was not working on RTD
- Fixed the Typesetting equations notebook so that it now displays the rendered math on RTD :tada:
- Fixed a bunch of the notebooks including: to avoid segfaulting sphinx, to use py3 for all nbs, to avoid using multiple H1 in notebooks so contents render more neatly
- Gotten rid of all warnings except one pesky one
- Added notebook extensions back to the TOC.
- Updated conda yaml to ``environment.yml``

Here's a [rendered version on RTD](http://testnb.readthedocs.org/en/new-build/examples/Notebook/Typesetting%20Equations.html).

**Visual of Master Table of Contents**
screen shot 2016-03-23 at 8 29 03 pm

**Visual of example notebooks table of contents**
screen shot 2016-03-23 at 8 29 24 pm

I spent way too long on this but it fixes a bunch of loose ends that have bugged me for a while.

@carreau, @minrk, @ellisonbg Please review. Thanks.

### CODE REVIEW

**Comment by ellisonbg** [comment]
Wow, that is fantastic progress. A few questions:

What is meant by "Community Documentation?" Is that what we are using to
refer to all our docs, or just part of the docs that non-core devs wrote?

Originally the notebook based documentation was supposed to be *the*
documentation for the notebook - at least that is how I wrote it initially.
The only problem is that we didn't delete the other sphinx docs so now we
have things repeated in multiple places. Have we started to deduplicate the
content so that content is only in one place or the other rather than both?

Kids are here this week, so I won't have much of a chance to do an in depth
review, so I would merge and we can iterate further.

Cheers, and great work!

On Wed, Mar 23, 2016 at 8:46 PM, Carol Willing <notifications@github.com>
wrote:

> Closes #1250 <https://github.com/jupyter/notebook/pull/1250> #1251
> <https://github.com/jupyter/notebook/pull/1251> #1252
> <https://github.com/jupyter/notebook/issues/1252>
>
> I think this incorporates all the desired changes that @carreau
> <https://github.com/carreau> wanted in these issues and PRs:
>
>    - Removed rst versions of notebooks
>    - notebooks build using nbsphinx
>    - Removed the Examples index notebook and replaced with a rst version
>    since linking from notebook to notebook was not working on RTD
>    - Fixed the Typesetting equations notebook so that it now displays the
>    rendered math on RTD [image: :tada:]
>    - Fixed a bunch of the notebooks including: to avoid segfaulting
>    sphinx, to use py3 for all nbs, to avoid using multiple H1 in notebooks so
>    contents render more neatly
>    - Gotten rid of all warnings except one pesky one
>    - Added notebook extensions back to the TOC.
>    - Updated conda yaml to environment.yml
>
> Here's a rendered version on RTD
> <http://testnb.readthedocs.org/en/new-build/examples/Notebook/Typesetting%20Equations.html>
> .
>
> *Visual of Master Table of Contents*
> [image: screen shot 2016-03-23 at 8 29 03 pm]
> <https://cloud.githubusercontent.com/assets/2680980/14007828/95364840-f137-11e5-989a-903a5ce8a050.png>
>
> *Visual of example notebooks table of contents*
> [image: screen shot 2016-03-23 at 8 29 24 pm]
> <https://cloud.githubusercontent.com/assets/2680980/14007829/9536556a-f137-11e5-9a20-448c1180599a.png>
>
> I spent way too long on this but it fixes a bunch of loose ends that have
> bugged me for a while.
>
> @carreau <https://github.com/carreau>, @minrk <https://github.com/minrk>,
> @ellisonbg <https://github.com/ellisonbg> Please review. Thanks.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/jupyter/notebook/pull/1255
> Commit Summary
>
>    - Remove rst versions of nb
>    - Update makefile and build configuration
>    - Update the nodebook so a cell doesn't cause a segfault intentionally
>    - Update TOC
>    - Add frontend doc
>    - Tweak notebooks for build
>    - Add nbsphinx to conda yaml
>    - Save notebook as py3
>    - Fix some links
>    - Use rst for index
>    - Drop H1 to H2 in markdown
>    - Add link to nbviewer at the top of the rst index
>    - Fix typo
>    - Try Prof. Willie Wong's code snippet
>    - Added $ for mathjax
>    - $ for math doc win
>
> File Changes
>
>    - *M* docs/Makefile
>    <https://github.com/jupyter/notebook/pull/1255/files#diff-0> (6)
>    - *R* docs/environment.yml
>    <https://github.com/jupyter/notebook/pull/1255/files#diff-1> (6)
>    - *M* docs/source/conf.py
>    <https://github.com/jupyter/notebook/pull/1255/files#diff-2> (4)
>    - *D* docs/source/examples/Notebook/Examples and Tutorials Index.ipynb
>    <https://github.com/jupyter/notebook/pull/1255/files#diff-3> (81)
>    - *M* docs/source/examples/Notebook/Importing Notebooks.ipynb
>    <https://github.com/jupyter/notebook/pull/1255/files#diff-4> (2)
>    - *M* docs/source/examples/Notebook/JavaScript Notebook
>    Extensions.ipynb
>    <https://github.com/jupyter/notebook/pull/1255/files#diff-5> (17)
>    - *M* docs/source/examples/Notebook/Notebook Basics.ipynb
>    <https://github.com/jupyter/notebook/pull/1255/files#diff-6> (10)
>    - *M* docs/source/examples/Notebook/Running Code.ipynb
>    <https://github.com/jupyter/notebook/pull/1255/files#diff-7> (653)
>    - *M* docs/source/examples/Notebook/Typesetting Equations.ipynb
>    <https://github.com/jupyter/notebook/pull/1255/files#diff-8> (40)
>    - *M* docs/source/examples/Notebook/Working With Markdown Cells.ipynb
>    <https://github.com/jupyter/notebook/pull/1255/files#diff-9> (58)
>    - *A* docs/source/examples/Notebook/examples_index.rst
>    <https://github.com/jupyter/notebook/pull/1255/files#diff-10> (21)
>    - *M* docs/source/examples/Notebook/nbpackage/nbs/other.ipynb
>    <https://github.com/jupyter/notebook/pull/1255/files#diff-11> (4)
>    - *D* docs/source/examples/Notebook/rstversions/Connecting with the Qt
>    Console.rst
>    <https://github.com/jupyter/notebook/pull/1255/files#diff-12> (67)
>    - *D* docs/source/examples/Notebook/rstversions/Custom Keyboard
>    Shortcuts.rst
>    <https://github.com/jupyter/notebook/pull/1255/files#diff-13> (71)
>    - *D* docs/source/examples/Notebook/rstversions/Examples and Tutorials
>    Index.rst <https://github.com/jupyter/notebook/pull/1255/files#diff-14>
>    (34)
>    - *D* docs/source/examples/Notebook/rstversions/Importing Notebooks.rst
>    <https://github.com/jupyter/notebook/pull/1255/files#diff-15> (286)
>    - *D* docs/source/examples/Notebook/rstversions/JavaScript Notebook
>    Extensions.rst
>    <https://github.com/jupyter/notebook/pull/1255/files#diff-16> (389)
>    - *D* docs/source/examples/Notebook/rstversions/Notebook Basics.rst
>    <https://github.com/jupyter/notebook/pull/1255/files#diff-17> (266)
>    - *D* docs/source/examples/Notebook/rstversions/Running Code.rst
>    <https://github.com/jupyter/notebook/pull/1255/files#diff-18> (154)
>    - *D* docs/source/examples/Notebook/rstversions/Typesetting
>    Equations.rst
>    <https://github.com/jupyter/notebook/pull/1255/files#diff-19> (290)
>    - *D* docs/source/examples/Notebook/rstversions/What is the Jupyter
>    Notebook.rst
>    <https://github.com/jupyter/notebook/pull/1255/files#diff-20> (136)
>    - *D* docs/source/examples/Notebook/rstversions/Working With Markdown
>    Cells.rst <https://github.com/jupyter/notebook/pull/1255/files#diff-21>
>    (313)
>    - *D* docs/source/examples/Notebook/rstversions/index.rst
>    <https://github.com/jupyter/notebook/pull/1255/files#diff-22> (37)
>    - *M* docs/source/extending/frontend_extensions.rst
>    <https://github.com/jupyter/notebook/pull/1255/files#diff-23> (5)
>    - *M* docs/source/extending/index.rst
>    <https://github.com/jupyter/notebook/pull/1255/files#diff-24> (1)
>    - *M* docs/source/index.rst
>    <https://github.com/jupyter/notebook/pull/1255/files#diff-25> (17)
>    - *M* readthedocs.yml
>    <https://github.com/jupyter/notebook/pull/1255/files#diff-26> (2)
>
> Patch Links:
>
>    - https://github.com/jupyter/notebook/pull/1255.patch
>    - https://github.com/jupyter/notebook/pull/1255.diff
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/pull/1255>
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by willingc** [comment]
@ellisonbg Yeah, we really should move the notebooks up to the user documentation section. The community section is really a place for us to highlight great uses and community written documentation that would be helpful to others.

Have fun with the kids. O'Reilly sustainability summit was very good yesterday. It sparked a few ideas that I want to share with you and others when we meet in person.

**Comment by minrk** [comment]
Thanks, @willingc! Merging here, and we can continue content discussions in subsequent PRs.

**Comment by willingc** [comment]
Thanks @minrk. Linking notebook to notebook is one thing that is holding us back from using the notebook more in documentation. If you have any thoughts on that, please share :-) I do plan to rationalize the content as suggested by @ellisonbg.

**Comment by Carreau** [comment]
Awesome ! Thanks !

**Comment by mgeier** [comment]
@willingc wrote:

> Linking notebook to notebook is one thing that is holding us back [...]

What do you mean?

This should work just as it works in the live notebook and on nbviewer, see http://nbsphinx.readthedocs.org/en/latest/markdown-cells.html#Links-to-Other-Notebooks

Or am I missing something?

BTW, [ipynb -> rst](http://nbsphinx.readthedocs.org/en/latest/markdown-cells.html#Links-to-*.rst-Files-(and-Other-Sphinx-Source-Files)) and [rst -> ipynb](http://nbsphinx.readthedocs.org/en/latest/rst.html#links-to-notebooks) should work as well, if anybody should need that.
However, links to subsections are only possible if the target is a notebook.

**Comment by mgeier** [comment]
@willingc Did you read my comment above?

BTW, I've just made a new [`nbsphinx` release](https://github.com/spatialaudio/nbsphinx/releases) which should handle LaTeX math environments correctly. With that, the work-around with different numbers of `$` signs shouldn't be necessary anymore.

**Pull request merged**
