### PR TITLE
unwebpackify

### LINKED ISSUE #1431: Auto-closing brackets/parentheses
Per [this question](http://stackoverflow.com/a/33015443/233293), I have been using the following in `~/.jupyter/custom/custom.js` to disable auto-closing parentheses:

```
require(['notebook/js/codecell'], function (codecell) {
      codecell.CodeCell.options_default.cm_config.autoCloseBrackets = false;
})
```

Under `notebook==4.2.0` this works, but upgrading to `5.0.0.dev0` the default behavior is back. Is this a bug, or just a change in the way that this parameter is configured?

### LINKED ISSUE #1554: Replace webpack with require.js
Proposal from #1547: go back to using require.js for this notebook, and leave webpack for newer projects, such as jupyterlab.

The switch to webpack in the legacy notebook seems to make lots of backward-compatibility maintenance impossible, and has been the source of numerous issues (#1547, #1439, #1431, etc.). Following some discussion in #1547, I think it's not feasible to maintain our goals of backward-compatibility in the existing notebook javascript while adopting webpack. The key point being that it seems to be impossible to include a module in the webpack, and then load it later with require, which is a necessity for numerous extensions and official APIs.

If that's not true, and we are just failing to configure things correctly, there might be a nicer, simpler fix. But this gist is, for the notebook js the following two things must return the same object:
- `require('notebook/js/cell')` in our packed-up sources
- `require('notebook/js/cell')` at runtime, in outputs, custom.js, or nbextensions

(and so on, for codemirror and everything else we load via require). The behavior in master is to load a different copy of the module, which is causing all kinds of things to break.

### LINKED ISSUE #2024: Celltoobars registered by nbextensions don't work
Right now, the Create Assignment nbextension from nbgrader doesn't work with master, but does with 4.3.1. I think it is related to webpack stuff and might be resolve by #2011. But this needs to be checked before we release.

### PR DESCRIPTION
**Pull request by minrk**
restores r.js-based build system from 4.x. Bonus: *way* faster.

This is one of the main impediments to getting started on the 5.0 release process, so I figured I'd get the ball rolling.

removes some of the shims added that were needed for webpack, some deprecations for things that are no longer broken.

closes #1554
closes #1431
closes #2024

TODO:

- [x] test #1431

### CODE REVIEW

**Comment by blink1073** [comment]
Nice, thanks for taking this on, Min.

**Comment by rgbkrk** [comment]
Thank you for switching this back.

**Comment by minrk** [comment]
I got the shortcut editor working by copying preact from the npm packages to components, which seems to be simple enough.

**Comment by ellisonbg** [comment]
@minrk I am finding that the Create Assignment celltoolbar from nbgrader doesn't work with master. I have tracked it down to multiple `CellToolbar` classes being present. Looks like there is one that is created from all of the files that use require.js and another from the notebook file which uses the import syntax. The version used in the nbextension to register the CTB isn't the same as the one used in the notebook, thus, it doesn't show up.

Do you think this is related to other issue that this PR is fixing? Could you post links to the other issues we are seeing to help me understand what is going on.

**Comment by minrk** [comment]
@ellisonbg yes, that's the primary motivation for this PR. *Loads* of extensions and custom.js don't work with master due to the duplicates created by the webpack build, and we never found a simple fix other than going back to the previous build setup. #1431 was the first report of the same issue, I think.

**Comment by takluyver** [comment]
Is this still WIP, or is it ready for review/merge now?

**Comment by minrk** [comment]
I just got the tests passing a few minutes ago, so I'm taking WIP off now. Should be ready for review.

I had to upgrade phantom and casper to get the tests to run, which required a few small bugfixes not related to the rollback to require.js.

**Comment by blink1073** [comment]
:clap:  well done @minrk!

**Comment by blink1073** [comment]
@minrk, do you mind updating the top level comment to reflect the preact status?

**Comment by minrk** [comment]
@blink1073 done, thanks.

The one last thing I want to do is add a test that covers #1431, which I'm working on now.

**Comment by minrk** [comment]
test added and passing

**Comment by blink1073** [comment]
🎆 :tada:

**Pull request merged**
