### PR TITLE
Pressing Tab to cycle through autocomplete selection

### PR DESCRIPTION
**Pull request by timporath**
<kbd>TAB</kbd> can now be used to cycle through the selections of the autocompletion. Its original functionality will still be invoked if a shared start can be found. 
<kbd>TAB</kbd> will also not call carry_on_completion with the true parameter, as in the first invocation of the completer, if the autocompletion is already open.

Mentioned in Issue #4192

### CODE REVIEW

**Comment by fhgd** [comment]
I would love to use this feature. Please merge it, many thanks in advance :-)

**Comment by blink1073** [comment]
I'm hesitant to change the tab behavior, as it is a major UX change.  Thank you for the suggestion though, @timporath!

**Comment by fhgd** [comment]
What are the reasons against that (major) UX change?

BTW: In IPython is this wanted behaviour standard (tab cycles throuh the autocompletion).

**Comment by blink1073** [comment]
We are minimizing changes to the classic notebook in favor of development of JupyterLab.

**Pull request closed without merging**
