### PR TITLE
Normalise `os_path`

### PR DESCRIPTION
**Pull request by krassowski**
Port of https://github.com/jupyter-server/jupyter_server/pull/886, fixes https://github.com/jupyter/notebook/issues/6458

### CODE REVIEW

**Comment by krassowski** [comment]
Hi, could someone take a look at this and #6461? @echarles @RRosio? It fixes a regression preventing users from copying files (unless they enabled hidden files access).

**Review by echarles — APPROVED** [review]
LGTM Thx @krassowski

**Comment by echarles** [comment]
I have merged:

- https://github.com/jupyter/notebook/pull/6540 on 6.5.x branch: do you need ti also on 6.4.x branch?
- https://github.com/jupyter/notebook/pull/6461 on 6.4.x branch: reverse question, do you need something similar on 6.5.x branch? Or should that change go to nbclassic?

Also the intent was to not release any new 6.4.x and invite users to migrate to 6.5. As we are still looking for feedbacks on 6.5 (see this [blog post](https://blog.jupyter.org/jupyter-notebook-6-5-0-release-candidate-4c229c6dab55)), I guess there is still room to cut a new 6.4.x.

**Comment by krassowski** [comment]
I don't feel it is critical to backport these fixes to 6.4.x if 6.5.0 goes smoothly. I opened #6545 to forward port #6461.

**Pull request merged**
