### PR TITLE
Fix terminal styles bug

### PR DESCRIPTION
**Pull request by gnestor**
Fixes https://github.com/jupyter/notebook/issues/1758

Before:

image

After:

image

### CODE REVIEW

**Comment by takluyver** [comment]
See also #1724.

Pinging @yuvipanda

**Comment by yuvipanda** [comment]
This definitely is a nicer fix than the one I had!

**Comment by yuvipanda** [comment]
Tested and works nicer than mine in both firefox and chrome. 

@takluyver I'm going to merge this unless you've objections?

**Comment by takluyver** [comment]
No objections from me - I haven't really looked at this stuff for ages in any case. Merge away :-)

**Comment by yuvipanda** [comment]
Done! Thanks @gnestor :)

**Pull request merged**
