### PR TITLE
[WIP] Unify JupyterLab with the main npm build

### PR DESCRIPTION
**Pull request by blink1073**
This currently works (and results in one less npm install), but needs some cleanup.

### CODE REVIEW

**Comment by minrk** [comment]
Cool, thanks @blink1073! What cleaning up do you need to do?

**Comment by blink1073** [comment]
Just general housekeeping on the changes, making sure I didn't add/remove too much.

**Comment by blink1073** [comment]
@minrk, I though about this more over the weekend, and I think it would be prudent to hold off on this until we switch over to `phosphor-ui`, since the existing phosphor repos have a `dedupe` post install script and we have previously established in this repo that we would only `dedupe` once and only if using an older `npm`.

**Comment by minrk** [comment]
Sure, that makes sense.

**Comment by blink1073** [comment]
Closing in favor of #1506.

**Pull request closed without merging**
