### PR TITLE
Add newer python excursions on appveyor

### PR DESCRIPTION
**Pull request by bollwyvl**
Adds python 3.7 and 3.8 to the test matrix.

Anaconda and conda-forge now both have all of our upstreams, I'm pretty sure, but it would be better to catch compatibility issues here.

refs:
- tests #5047

### CODE REVIEW

**Comment by bollwyvl** [comment]
Previous success is very deceptive: conda failed to install 3.8, but the command didn't fail, so it was actually just testing 3.6 again, but as installed from pip. Note that that excursion did take _by far_ the least amount of time: 5 min vs 9 or 12 minutes.

**Comment by bollwyvl** [comment]
Finally, the actual error from #5047:

https://ci.appveyor.com/project/Carreau/notebook/builds/28828605/job/dlj8ckiaoc5cohy5#L2718

**Comment by bollwyvl** [comment]
Looks like that first fail is going to go the full 60 minute distance due to how it fails... someone with perms may have to kill my builds (except for maybe the last one, i guess).

**Comment by bollwyvl** [comment]
Ok, conda fiddling hopefully done now: current block-the-world error:
```
call %CONDA_INSTALL_LOCN%\Scripts\activate.bat notebook-test && md tst_tmp && cd tst_tmp && nosetests -v notebook --with-cov --cov notebook --traverse-namespace
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Miniconda36-x64\envs\notebook-test\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Miniconda36-x64\envs\notebook-test\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Miniconda36-x64\envs\notebook-test\lib\site-packages\notebook\tests\launchnotebook.py", line 165, in start_thread
    app.initialize(argv=cls.get_argv())
  File "<C:\Miniconda36-x64\envs\notebook-test\lib\site-packages\decorator.py:decorator-gen-7>", line 2, in initialize
  File "C:\Miniconda36-x64\envs\notebook-test\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Miniconda36-x64\envs\notebook-test\lib\site-packages\notebook\notebookapp.py", line 1754, in initialize
    self.init_webapp()
  File "C:\Miniconda36-x64\envs\notebook-test\lib\site-packages\notebook\notebookapp.py", line 1482, in init_webapp
    self.http_server.listen(port, self.ip)
  File "C:\Miniconda36-x64\envs\notebook-test\lib\site-packages\tornado\tcpserver.py", line 152, in listen
    self.add_sockets(sockets)
  File "C:\Miniconda36-x64\envs\notebook-test\lib\site-packages\tornado\tcpserver.py", line 165, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "C:\Miniconda36-x64\envs\notebook-test\lib\site-packages\tornado\netutil.py", line 240, in add_accept_handler
    io_loop = IOLoop.current()
  File "C:\Miniconda36-x64\envs\notebook-test\lib\site-packages\tornado\ioloop.py", line 265, in current
    loop = asyncio.get_event_loop()
  File "C:\Miniconda36-x64\envs\notebook-test\lib\asyncio\events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-1'.
```

Will try some local repro...

**Comment by bollwyvl** [comment]
First substantive error:
```
test_connections (notebook.services.kernels.tests.test_kernels_api.KernelAPITest) ... Traceback (most recent call last):
  File "C:\git\notebook\envs\default\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\git\notebook\envs\default\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\git\notebook\envs\default\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\git\notebook\envs\default\lib\site-packages\traitlets\config\application.py", line 663, in launch_instance
    app.initialize(argv)
  File "<C:\git\notebook\envs\default\lib\site-packages\decorator.py:decorator-gen-125>", line 2, in initialize
  File "C:\git\notebook\envs\default\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\git\notebook\envs\default\lib\site-packages\ipykernel\kernelapp.py", line 527, in initialize
    self.init_sockets()
  File "C:\git\notebook\envs\default\lib\site-packages\ipykernel\kernelapp.py", line 287, in init_sockets
    self.init_iopub(context)
  File "C:\git\notebook\envs\default\lib\site-packages\ipykernel\kernelapp.py", line 295, in init_iopub
    self.iopub_thread = IOPubThread(self.iopub_socket, pipe=True)
  File "C:\git\notebook\envs\default\lib\site-packages\ipykernel\iostream.py", line 68, in __init__
    self._setup_pipe_in()
  File "C:\git\notebook\envs\default\lib\site-packages\ipykernel\iostream.py", line 141, in _setup_pipe_in
    self._pipe_in = ZMQStream(pipe_in, self.io_loop)
  File "C:\git\notebook\envs\default\lib\site-packages\zmq\eventloop\zmqstream.py", line 127, in __init__
    self._init_io_state()
  File "C:\git\notebook\envs\default\lib\site-packages\zmq\eventloop\zmqstream.py", line 546, in _init_io_state
    self.io_loop.add_handler(self.socket, self._handle_events, self.io_loop.READ)
  File "C:\git\notebook\envs\default\lib\site-packages\tornado\platform\asyncio.py", line 99, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "C:\git\notebook\envs\default\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError
```

**Comment by bollwyvl** [comment]
Har, of course @minrk is already on it:

https://github.com/ipython/ipykernel/pull/456

**Comment by bollwyvl** [comment]
Tests are still hanging, but there's a lot less fail: down to just [two errors](https://ci.appveyor.com/project/Carreau/notebook/builds/28857057/job/ffcym17u0ny4gtnf#L2980). Haven't had a chance to dig in to them, as i was getting entirely different errors locally...

**Comment by bollwyvl** [comment]
Well, looks like i broke it again for an hour or three...

**Comment by bollwyvl** [comment]
Great, back down to the two errors coming from ipykernel.

**Comment by kevin-bates** [comment]
Closing since appveyor is no longer applicable.  Thanks for your time spent on this @bollwyvl - it's still appreciated.

**Pull request closed without merging**
