### PR TITLE
Prefer IP address over hostname when available

### PR DESCRIPTION
**Pull request by takluyver**
Following discussion on #3356.

@evandam @cyberwillis please let me know if you think this is a good idea. I haven't encountered the same issues as either of you, so I don't want to merge this without some confirmation that it's actually an improvement!

### CODE REVIEW

**Comment by takluyver** [comment]
And are there any other values for `self.ip` like '0.0.0.0', which can't be directly used?

**Comment by cyberwillis** [comment]
To me its working fine with this code. 
I replicate your changes locally here and tested:

```
0.0.0.0 => container_name
' ' => localhost 
127.0.0.1  => 127.0.0.1 
xxx.xxx.xxx.xxx => xxx.xxx.xxx.xxx
```
Thanks

**Comment by evandam** [comment]
Looks great to me! Does this handle when you do something like `--ip='*'`? If I recall it's the same thing as passing `0.0.0.0`, too.

**Comment by cyberwillis** [comment]
Yes does I have testes earlier.

**Comment by cyberwillis** [comment]
:)

**Comment by takluyver** [comment]
Thanks both! In it goes.

**Comment by cyberwillis** [comment]
I started to get this problem in my way too

[2935](https://github.com/jupyter/notebook/issues/2935)

**Pull request merged**
