### PR TITLE
Add warning to upgrade notebook for version 5.

### LINKED ISSUE #6524: Notebook 5: Add console output to indicate end-of-life
Notebook 5 will no longer be maintained after Notebook 7 is released. In the Notebook 5 branch, when the user launches Notebook from a terminal, add console output to urge the user to upgrade to version 6 or later.

We discussed this at the 2022-08-24 Notebook meeting.

### PR DESCRIPTION
**Pull request by kostyafarber**
# PR Summary
The purpose of this PR is to notify the user to update their notebook as version 5 is no longer being maintained. This intends to close #6524.

### CODE REVIEW

**Review by jweill-aws — APPROVED** [review]

**Review by RRosio — APPROVED** [review]

**Comment by RRosio** [comment]
Thank you for submitting this PR! I will go ahead and merge it!

**Comment by kostyafarber** [comment]
No worries! Would you be able to add the `hacktoberfest` label to this PR please 😄

Would be much appreciated. Thanks!

**Comment by RRosio** [comment]
Hi @kostyafarber, yes I have just added that label!
I am also wondering, were you able to install this version of notebook without any issues?

**Comment by kostyafarber** [comment]
No worries! Glad I could help 👍🏻👍🏻👍🏻

**Comment by RRosio** [comment]
👍 The release of Notebook 5 with this warning is live in [PyPI](https://pypi.org/project/notebook/5.7.16/)!

**Comment by kostyafarber** [comment]
@RRosio sorry to be a pain. But I got the label wrong. Would you be able to add the label 'hacktoberfest-accepted' 😅 it's not coming up as an accepted PR on my profile. Much appreciated

**Comment by RRosio** [comment]
@kostyafarber no worries! Just added that label! 🙂

**Pull request merged**
