### PR TITLE
Updated function call to match API changes in jupyter_client

### PR DESCRIPTION
**Pull request by captainsafia**
If [jupyter/jupyter_client#93](https://github.com/jupyter/jupyter_client/pull/93) is merged, this should be merged in order to reflect the API changes in that PR.

### CODE REVIEW

**Comment by minrk** [comment]
@captainsafia that PR doesn't seem to remove the API here, and removing that API would force a major-revision release on jupyter_client. I don't see why this API would be used, since it causes strictly more work to be done than the original `find_kernel_specs`.

**Comment by captainsafia** [comment]
@minrk — Did you mean to put this in [jupyter/jupyter_client#93](https://github.com/jupyter/jupyter_client/pull/93)? I'm a little bit confused as to what you mean.

**Comment by minrk** [comment]
No, I meant it to be here. This PR changes the dependency on jupyter_client to an unreleased version, and as far as I can tell from the jupyter_client PR, no benefit, since iterating through `find_all_specs` and `find_kernel_specs` has the same result and `find_all_specs` does strictly more work than `find_kernel_specs`. Perhaps there is something missing in this PR to actually make use of the difference between the two.

**Comment by minrk** [comment]
This can make sense if we *also* change the `kernel_model` call to allow passing the model from `get_all_specs`. But as it is, it doesn't make any use of the computed specs, it just discards them.

**Comment by Carreau** [comment]
Tagging as `closed-PR`, and closing as this is seem to have stalled a bit. 
This is just to keep the PR queue a bit shorter and focusing on what is actually worked on.
Feel free to reopen, (or ask for reopening if you don't have enough right to do so). 
If you were not the original author, and want to revive this, please feel free to do so. 

Also, we are doing our best to enable people to learn how to contribute to the project, and get commits in. If you are missing time or have any other issues that prevent you to work on that, please feel free to tell us, we can try to build on top of what you did. 

Thanks a lot and looking forward to see this moving forward again.

**Pull request closed without merging**
