### PR TITLE
Remove soft selected right border background-leaking

### PR DESCRIPTION
**Pull request by Carreau**
Ping @ellisonbg 

screen shot 2015-12-30 at 11 04 44

### CODE REVIEW

**Comment by ellisonbg** [comment]
Thanks @Carreau

I am +1 on this as the right border was never in any of the prototypes we
agreed upon.

On Wed, Dec 30, 2015 at 2:06 AM, Matthias Bussonnier <
notifications@github.com> wrote:

> Ping @ellisonbg <https://github.com/ellisonbg>
>
> [image: screen shot 2015-12-30 at 11 04 44]
> <https://cloud.githubusercontent.com/assets/335567/12049263/4f5c82f6-aee5-11e5-87f4-a655347dc72a.png>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/jupyter/notebook/pull/908
> Commit Summary
>
>    - Remove soft selected right border background-leaking
>
> File Changes
>
>    - *M* notebook/static/notebook/less/cell.less
>    <https://github.com/jupyter/notebook/pull/908/files#diff-0> (2)
>
> Patch Links:
>
>    - https://github.com/jupyter/notebook/pull/908.patch
>    - https://github.com/jupyter/notebook/pull/908.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/pull/908>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by minrk** [comment]
This conflicts with #909. I rebased and reissued it as #915, so @Carreau doesn't have to.

**Comment by Carreau** [comment]
Thanks @minrk inrk

**Comment by Carreau** [comment]
> Thanks @minrk

I gave you access to my fork so that you can directly update my PR instead of re-issuing them in case this ever shows up again.

**Comment by minrk** [comment]
Merged as #915

**Pull request closed without merging**
