### PR TITLE
Make sys_info more robust

### PR DESCRIPTION
**Pull request by takluyver**
- Don't call it at import time
- Don't fail if `git` isn't available
- Don't use `shell=True` to invoke git

Closes gh-2468

### CODE REVIEW

**Comment by minrk** [comment]
👍, though I have a vague recollection that `shell=True` was needed for it to work on Windows.

**Comment by takluyver** [comment]
I dug into git history, and it appeared to have been `shell=True` from when it was originally written in IPython - we don't seem to have started with `shell=False` and then changed it in response to an issue. That doesn't guarantee that it works on Windows, and I also vaguely recall some issues with invoking other things this way, but I think it's worth a try.

**Comment by sarathuniverse** [comment]
where to change this shell=true
I mean in which file i can change

**Comment by takluyver** [comment]
This is a pull request that was already merged. You can see the files that it changed under the 'Files changed' tab at the top.

**Pull request merged**
