### PR TITLE
Enable older version of ipywidgets on notebook 4.2

### LINKED ISSUE #1386: Widgets are not displayed after update to 4.2.0
Trying to run this code in a notebook:

    from ipywidgets import widgets
    from IPython.display import display
    s = widgets.IntSlider()
    display(s)

results in nothing.

After downgrading to notebook 4.1.0 the same code works as expected - widget is shown.

Installed packages:

    ipython = 4.2.0
    ipywidgets = 4.1.1

Browser: Firefox 46.0

Errors in browser console:

    Could not open comm  --  Error: Class ipython.widget not found in registry 
    Stack trace:
    load_class/<@http://localhost:8888/static/notebook/js/main.min.js?v=1c2abb797e9945d6ce7d58ae051fe985:12844:28
    load_class@http://localhost:8888/static/notebook/js/main.min.js?v=1c2abb797e9945d6ce7d58ae051fe985:12829:16
    CommManager.prototype.comm_open@http://localhost:8888/static/notebook/js/main.min.js?v=1c2abb797e9945d6ce7d58ae051fe985:21996:31
    .proxy/i@http://localhost:8888/static/notebook/js/main.min.js?v=1c2abb797e9945d6ce7d58ae051fe985:87:5486
    Kernel.prototype._handle_iopub_message@http://localhost:8888/static/notebook/js/main.min.js?v=1c2abb797e9945d6ce7d58ae051fe985:23338:20
    Kernel.prototype._finish_ws_message@http://localhost:8888/static/notebook/js/main.min.js?v=1c2abb797e9945d6ce7d58ae051fe985:23175:24
    Kernel.prototype._handle_ws_message/this._msg_queue<@http://localhost:8888/static/notebook/js/main.min.js?v=1c2abb797e9945d6ce7d58ae051fe985:23166:39
     main.min.js:12880:17

    Couldn't process kernel message Object { fileName: "http://localhost:8888/static/notebo…", lineNumber: 12799, columnNumber: 19, message: "Could not open comm", error_stack: Array[2], stack: "" } main.min.js:23167:34

    Couldn't process kernel message Object { fileName: "http://localhost:8888/static/notebo…", lineNumber: 12799, columnNumber: 19, message: "Could not open comm", error_stack: Array[2], stack: "" } main.min.js:23167:34

Posting it here since the package "responsible" for the change in behavior seems to be `notebook`

### PR DESCRIPTION
**Pull request by SylvainCorlay**
Fixes #1386.

@minrk  This makes it work but I can't believe this is the best way to do this.

### CODE REVIEW

**Comment by minrk** [comment]
If it works and is simple, I'm not super concerned about it being the best way to do it. You might want a comment about it, though. Should this be a PR against 4.x, not master, or should master be getting the same patch?

**Comment by SylvainCorlay** [comment]
Yes, I should open this on the 4.2 branch. It seems to work, but I don't know when we broke that.

**Comment by minrk** [comment]
It's fine for this to be against master if *both* 5.0 and 4.2 should have this. But if it's only for 4.2, we should close and reopen against 4.x.

**Comment by SylvainCorlay** [comment]
I think that it is for both. I opened another PR for 4.x though.

**Comment by minrk** [comment]
Okay, thanks

**Pull request merged**
