### PR TITLE
Fix button layout in dialog windows

### LINKED ISSUE #742: All dialogs should order buttons in the same way
In general, the "do action" button in a dialog should be the rightmost one and the "Cancel" should be the leftmost one:

screen shot 2015-11-20 at 5 13 04 pm

Right now, in our dialogs we do both:

screen shot 2015-11-20 at 5 13 40 pm

screen shot 2015-11-20 at 5 13 57 pm

This is dangerous as users might click buttons out of habits based on their positions.

### PR DESCRIPTION
**Pull request by captainsafia**
Closes #742.

I believe this updates all the necessary dialog windows but let me know if I missed any.

cc/ @ellisonbg

### CODE REVIEW

**Comment by ellisonbg** [comment]
Hmmm, aren't objects in JavaScript unordered collections? I was expecting us to have to turn the buttons into an array to get proper ordering on this.

**Comment by captainsafia** [comment]
According to the official ECMAScript guidelines, collections are unordered but I believe that most browsers return the items in the object in the order they were inserted so reordering the keys does work.

Not sure if we are OK with it working in most browsers or if I should try a solution that is in line with the official guidelines

**Comment by Carreau** [comment]
As stated in issue, not a 4.1 it is a change of UI, and will break people muscle memory.

**Comment by ellisonbg** [comment]
Um, I consider this a *bug* and should be fixed for 4.1.

On Sun, Nov 22, 2015 at 10:39 PM, Matthias Bussonnier <
notifications@github.com> wrote:

> As stated in issue, not a 4.1 it is a change of UI, and will break people
> muscle memory.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/pull/744#issuecomment-158862312>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by ellisonbg** [comment]
It is dangerous to have buttons in different orders in different parts of the UI.

Part of what makes this worse in 4.1/master is that we have cleaned up the Kernel Restart dialog, so there is now only a binary choice where before there was 3 options and the user had to pay really close attention and read exactly what those 3 buttons did:

4.0:

screen shot 2015-11-23 at 10 05 09 am

4.1/master:

screen shot 2015-11-23 at 10 09 46 am

Most importantly, all other dialogs that I can find have the buttons in the opposite order from the Restart Kernel dialog in both 4.0 and master:

screen shot 2015-11-23 at 10 05 21 am

screen shot 2015-11-23 at 10 06 08 am

Thus, the problem is really with the restart kernel dialog and for that, a change in 4.1 has made the situation worse. I would be find with simply swapping the order in the Kernel Restart dialog for 4.1 instead of swapping everything else. Then we could consider swapping the order of all dialog buttons to the Mac ordering for 5.0. But I prefer to just do it for 4.1.

**Comment by minrk** [comment]
I'm fine viewing the current inconsistency as a bug to be fixed.

**Comment by Carreau** [comment]
The restart are in the order they are **not to change use muscle memory** as the focused button is the last. I'm fine changing for 5.0 if you like, but the kernel restart has been with restart focused and on the right since 3.x. The number of people that have `0,0,Enter` as a habit is likely huge (I am one of the heavy user of this on).

I would see changing the order as a break for user, especially since we already made the decision to put in that order in the pr for 4.0. not to break muscle memory.

And we have already enough people complaining that restarting and clearing all cell is too long and has no shortcut. I do not want to deal with user complaining that it is even harder than before. 

So this is not 4.1

**Comment by ellisonbg** [comment]
I should have clarified. I am not suggesting that we change which action is
focused. The `0,0,Enter` shortcut should still restart the kernel. Changing
that would be problematic in a point release. I am only talking about
changing the order of those buttons.

I don't think the muscle memory argument applies for the visual ordering of
those elements - which is already different from 4.0.

With this clarification, can you get behind the visual reordering of the
buttons for 4.1?

Cheers, Brian

On Tue, Nov 24, 2015 at 2:38 AM, Matthias Bussonnier <
notifications@github.com> wrote:

> The restart are in the order they are *not to change use muscle memory*
> as the focused button is the last. I'm fine changing for 5.0 if you like,
> but the kernel restart has been with restart focused and on the right since
> 3.x. The number of people that have 0,0,Enter as a habit is likely huge
> (I am one of the heavy user of this on).
>
> I would see changing the order as a break for user, especially since we
> already made the decision to put in that order in the pr for 4.0. not to
> break muscle memory.
>
> And we have already enough people complaining that restarting and clearing
> all cell is too long and has no shortcut. I do not want to deal with user
> complaining that it is even harder than before.
>
> So this is not 4.1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/pull/744#issuecomment-159225279>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
> With this clarification, can you get behind the visual reordering of the
> buttons for 4.1?

Yes, but the focused button is always the last of the list
So you cannot reorder and keep the focus without probably major changes.

**Comment by minrk** [comment]
We can fix that.

**Comment by Carreau** [comment]
> We can fix that.

It's tricky if you wait for the dialog show event to focus the button you get a small window of time where the wrong button is focussed IIRC.

**Comment by minrk** [comment]
I'm pretty sure it's already our code that's focusing the last button, so I think we can work it out without a race.

**Comment by minrk** [comment]
#752 makes it possible to specify which button is highlighted when the dialog is drawn, rather than always focusing the last button (still default).

**Comment by ellisonbg** [comment]
Great, thanks @minrk - that is exactly what I was thinking about. @Carreau
are you OK with us swapping the order of the Restart Kernel dialog buttons
but using Min's implementation to make sure that `0,0,Enter` still works
(for 4.1)?

On Tue, Nov 24, 2015 at 12:29 PM, Min RK <notifications@github.com> wrote:

> #752 <https://github.com/jupyter/notebook/pull/752> makes it possible to
> specify which button is highlighted when the dialog is drawn, rather than
> always focusing the last button (still default).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/pull/744#issuecomment-159396311>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by minrk** [comment]
Also for some clarification: I this this PR doesn't change the ordering of the restart buttons, so Restart is still the rightmost button and default-last-focus continues to focus the 'Restart' action, as it did in 4.0 and does on master.

**Comment by Carreau** [comment]
> @Carreau
> are you OK with us swapping the order of the Restart Kernel dialog buttons
> but using Min's implementation to make sure that `0,0,Enter` still works
> (for 4.1)?

Yes.

**Comment by captainsafia** [comment]
> I this this PR doesn't change the ordering of the restart buttons, so Restart is still the rightmost button and default-last-focus continues to focus the 'Restart' action

I can update it so the button ordering to "Restart" then "Continue Running" and add the `default_button` configuration @minrk introduced in #752, assuming this is the final decision?

**Comment by minrk** [comment]
Thanks, @captainsafia, that clears it up, I think.

So the question is:

1. reorder restart buttons, vs
2. reorder everything else.

and this PR currently reorders everything else, but we are considering switching it to reordering just restart, so the default-action change is smaller.

I'm fine either way on that one - I like `Cancel, Action` better than `Action, Cancel` in the long run, but if the restart dialog is the main inconsistency, I see what you mean about changing fewer dialogs. Sorry for being slow.

**Comment by ellisonbg** [comment]
Nice summary Min. I am fine with either as well for 4.1

I prefer to `Cancel, Action` in general, but am fine with just changing the
kernel restart for 4.1 and then changing everything else (including Kernel
Restart) in 5.0. But maybe that is too many back and forth changes...

@fperez any thoughts on this?

On Tue, Nov 24, 2015 at 1:53 PM, Min RK <notifications@github.com> wrote:

> Thanks, @captainsafia <https://github.com/captainsafia>, that clears it
> up, I think.
>
> So the question is:
>
>    1. reorder restart buttons, vs
>    2. reorder everything else.
>
> and this PR currently reorders everything else, but we are considering
> switching it to reordering just restart, so the default-action change is
> smaller.
>
> I'm fine either way on that one - I like Cancel, Action better than Action,
> Cancel in the long run, but if the restart dialog is the main
> inconsistency, I see what you mean about changing fewer dialogs. Sorry for
> being slow.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/pull/744#issuecomment-159416445>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by fperez** [comment]
Given we're trying to land 4.1, I'd probably favor the option of changing fewer dialogs on this pass, and doing the full reorg for 5.0, even if it leaves some inconsistency. Fortunately, this dialog looks very different from those others, that say `OK/Cancel` instead of this one with fully named actions. 

And for 5.0, we can do a proper audit for consistency so the pattern is `Cancel`, `Named Action`.

Given the difference in the actual dialogs, I'm not too bothered by the inconsistency (and it's been there before, so I wouldn't go wholesale messing with the UI to fix it across all dialogs in this minor release, or at least not this late in the cycle when we're really trying to just dot i's and cross t's).

How does that sound?

**Comment by ellisonbg** [comment]
Mmm, I am not quite sure I understand what you are proposing:

A) Leave the order of the Restart Kernel buttons the same as in master,
which is opposite from all other dialogs in master. This is the original
bug I brought up.
B) Reorder the Restart Kernel buttons in master to match the rest of the
button orders in master for 4.1.

The *naming* of the buttons isn't really on the table here (although I
think some of that crept into the original PR).

On Tue, Nov 24, 2015 at 7:01 PM, Fernando Perez <notifications@github.com>
wrote:

> Given we're trying to land 4.1, I'd probably favor the option of changing
> fewer dialogs on this pass, and doing the full reorg for 5.0, even if it
> leaves some inconsistency. Fortunately, this dialog looks very different
> from those others, that say OK/Cancel instead of this one with fully
> named actions.
>
> And for 5.0, we can do a proper audit for consistency so the pattern is
> Cancel, Named Action.
>
> Given the difference in the actual dialogs, I'm not too bothered by the
> inconsistency (and it's been there before, so I wouldn't go wholesale
> messing with the UI to fix it across all dialogs in this minor release, or
> at least not this late in the cycle when we're really trying to just dot
> i's and cross t's).
>
> How does that sound?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/pull/744#issuecomment-159473902>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by fperez** [comment]
Ah, but I thought that you guys wanted to audit the UI for 5.0 so that all the buttons would move towards a `Cancel/Action` order, whereas now they mostly have an `OK/Cancel` order. Am I misunderstanding that?

**Comment by captainsafia** [comment]
> The *naming* of the buttons isn't really on the table here (although I think some of that crept into the original PR).

Yeah that's my fault. I spotted the naming and figured I might fix it. I can revert that though.

> Ah, but I thought that you guys wanted to audit the UI for 5.0 so that all the buttons would move towards a Cancel/Action order, whereas now they mostly have an OK/Cancel order.

This is the way that I understand it as well.

If I can synthesize everybody's thoughts, I *think* the takeaway from this is to:

1. Remove the rearrangements that I made in this PR.
2. Reorder the "Restart" dialog buttons so they match the `Action | Cancel` arrangement that currently dominates the UI, this is what will be release in 4.1.
3. In the 5.0 release, complete an overall of the dialog buttons which includes creating named actions and placing them in `Cancel | Named Action` order.

**Comment by ellisonbg** [comment]
I would like to do that audit for 4.1 and that is what Safia's PR
implements (would have to be updated on top of Min's changes to keep the
keyboard behaviors the same). Matthias felt like reordering buttons is a
breakage, but I feel that fixed usability problems of this sort are bug
fixes. Matthias did have an excellent point that re-ordering the buttons
should not change which action will happen when someone presses `Enter`.
That would be a breaking change to the keyboard shortcuts - but we can
preserve that.

I will admit that this is a totally grey line.

So maybe we have 3 options:

1) Fix the ordering of everything for 4.1, preserving the keyboard
behaviors.
2) Change nothing for 4.1, but everything for 5.0.
3) Temporarily re-order the "Restart Kernel" to match everything else for
4.1, but then change the order of everything for 5.0.

My preferences are 1, 3, 2.

Cheers,

Brian

On Tue, Nov 24, 2015 at 7:31 PM, Fernando Perez <notifications@github.com>
wrote:

> Ah, but I thought that you guys wanted to audit the UI for 5.0 so that all
> the buttons would move towards a Cancel/Action order, whereas now they
> mostly have an OK/Cancel order. Am I misunderstanding that?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/pull/744#issuecomment-159478172>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by fperez** [comment]
On Wed, Nov 25, 2015 at 9:05 AM, Brian E. Granger <notifications@github.com>
wrote:

> 1) Fix the ordering of everything for 4.1, preserving the keyboard
> behaviors.
> 2) Change nothing for 4.1, but everything for 5.0.
> 3) Temporarily re-order the "Restart Kernel" to match everything else for
> 4.1, but then change the order of everything for 5.0.
>

Ah, got it. My only concern with 1 is that I think if that reordering is
done, they shouldn't be called `Cancel, OK`, they should become named
actions. So the audit will have to be more thorough and careful, and there
will be decisions to make on the name of *every* button. That means this
becomes a potentially very long and detailed PR in terms of how many things
to look at (not that much code, obviously).

That worries me a bit, given we're trying to wrap up and ship...


-- 
Fernando Perez (@fperez_org; http://fperez.org)
fperez.net-at-gmail: mailing lists only (I ignore this when swamped!)
fernando.perez-at-berkeley: contact me here for any direct mail

**Comment by ellisonbg** [comment]
I wouldn't want to delay the release any further, but from looking at the
changes Safia made in the PR (which already includes some of of those
renames) I don't think it will be a problem.

What about the following?

* We start to work with Min and Safia to see if we can get the full button
order swap done for 4.1, with the renaming and keeping the keyboard
behavior the same.
* If the work isn't done by the first beta of 4.1, we release without it
and target this work for 5.0.



On Wed, Nov 25, 2015 at 9:33 AM, Fernando Perez <notifications@github.com>
wrote:

> On Wed, Nov 25, 2015 at 9:05 AM, Brian E. Granger <
> notifications@github.com>
> wrote:
>
> > 1) Fix the ordering of everything for 4.1, preserving the keyboard
> > behaviors.
> > 2) Change nothing for 4.1, but everything for 5.0.
> > 3) Temporarily re-order the "Restart Kernel" to match everything else for
> > 4.1, but then change the order of everything for 5.0.
> >
>
> Ah, got it. My only concern with 1 is that I think if that reordering is
> done, they shouldn't be called `Cancel, OK`, they should become named
> actions. So the audit will have to be more thorough and careful, and there
> will be decisions to make on the name of *every* button. That means this
> becomes a potentially very long and detailed PR in terms of how many things
> to look at (not that much code, obviously).
>
> That worries me a bit, given we're trying to wrap up and ship...
>
>
> --
> Fernando Perez (@fperez_org; http://fperez.org)
> fperez.net-at-gmail: mailing lists only (I ignore this when swamped!)
> fernando.perez-at-berkeley: contact me here for any direct mail
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/pull/744#issuecomment-159682515>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by captainsafia** [comment]
If the only modifications we want to make to the buttons are the ordering and the naming, then I am pretty sure I can flesh that out early AM tomorrow. As Brian mentioned I've gotten a good chunk (I think) of the work done already.

It definitely wouldn't hurt to go for it and if it isn't done by beta, we can defer to 5.0.

**Comment by fperez** [comment]
Sounds like a plan, full steam ahead then! We do have a beta/rc cycle to fine tune still, and as long as this doesn't drag us into long decision cycles, I have otherwise no objections.

**Comment by ellisonbg** [comment]
@captainsafia I merged #752 so if you rebase, you can use the `default_button` config option for each model to maintain which button is focused for keyboard events when the model is opened. If you can take a pass at finishing things up, I can help test.

**Comment by captainsafia** [comment]
OK. Checking in to see that I have the right approach. Here is what I am doing thus far.

* Swapping the button order on the dialog menus so that they are in `Cancel | Action` order
* Renaming the action oriented buttons in situations where I could think of a good name
* If button order was swapped, I used `default_button` to ensure that the focus is on the button that was previously on the right

Does that sound in line with what we have been discussing?

**Comment by fperez** [comment]
+1, thanks!

**Comment by ellisonbg** [comment]
Yep, that sounds right!

On Wed, Nov 25, 2015 at 9:39 PM, Fernando Perez <notifications@github.com>
wrote:

> +1, thanks!
>
> On Wed, Nov 25, 2015, 20:37 Safia Abdalla <notifications@github.com>
> wrote:
>
> > OK. Checking in to see that I have the right approach. Here is what I am
> > doing thus far.
> >
> > - Swapping the button order on the dialog menus so that they are in
> Cancel
> > | Action order
> > - Renaming the action oriented buttons in situations where I could
> > think of a good name
> > - If button order was swapped, I used default_button to ensure that
> > the focus is on the button that was previously on the right
> >
> > Does that sound in line with what we have been discussing?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/jupyter/notebook/pull/744#issuecomment-159801889>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/pull/744#issuecomment-159810305>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by captainsafia** [comment]
OK, if I am not crazy, @ellisonbg I think this is good to test.

**Comment by minrk** [comment]
Looking good!

**Comment by Carreau** [comment]
@ellisonbg do you want to get that in master early to give it a try ?

**Comment by Carreau** [comment]
I'm going to be annoying, if I don't get  negative feedback I'll merge that soon.

**Comment by takluyver** [comment]
:shipit:

**Pull request merged**
