### PR TITLE
remove es6 syntax

### PR DESCRIPTION
**Pull request by forbxy**
It is necessary to be compatible with a lower version of the browser

### CODE REVIEW

**Comment by takluyver** [comment]
How low a version are you using? We don't want to be stuck with old syntax forever.

**Comment by forbxy** [comment]
chrome 47.x

**Comment by takluyver** [comment]
That's [over two years old](https://en.wikipedia.org/wiki/Google_Chrome_version_history). Given how security critical browsers are now, I'd strongly recommend you let it upgrade to a current version.

**Comment by takluyver** [comment]
Closing since I think this syntax is [sufficiently well supported](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Browser_compatibility) that we can rely on it.

**Pull request closed without merging**
