### PR TITLE
Add debug log for static file paths

### PR DESCRIPTION
**Pull request by jasongrout**
Too often I'm trying to track down an errant extra static file path (like some javascript installed in some obscure place). This makes it easy to see exactly what is being served.

### CODE REVIEW

**Comment by jasongrout** [comment]
CC @dmadeka1

**Comment by jasongrout** [comment]
Perhaps `log()` doesn't have to be a function? I'm not sure what the specific lifetime concerns are with the application initialization check. @minrk - would the following work just as well?

```
    if Application.initialized():
        log = Application.instance().log
    else:
        log = app_log
```
at the top level?

**Comment by takluyver** [comment]
@jasongrout `FileFindHandler`, which you're modifying, inherits from `IPythonHandler`, which defines the `log` property. So you should be able to use `self.log.debug(...)`, I think, without needing an extra function.

The application won't be initialised at import time, so putting that check at the top level of the module wouldn't work.

**Comment by minrk** [comment]
Arg, I wrote a whole comment last week, but apparently GitHub lost it. What @takluyver said - module-level initialization won't work because import happens too early. This function is fine as-is. @takluyver it's needed here because this method is required to be a classmethod.

**Comment by gnestor** [comment]
@jasongrout Does this need to be backported before releasing 4.3?

**Comment by minrk** [comment]
Backported

**Pull request merged**
