### PR TITLE
Temporary workaround to fix js-tests related to sanitizer js loading by phantomjs

### PR DESCRIPTION
**Pull request by echarles**
Follow up of https://github.com/jupyter/notebook/pull/6354

### CODE REVIEW

**Comment by echarles** [comment]
Close/open to trigger CI.

**Comment by echarles** [comment]
So python tests are now failing with `ERROR  - ModuleNotFoundError: No module named 'testpath`.

@blink1073 Could it be a side-effect of yesterday https://github.com/jupyter/notebook/pull/6260 I guess the CI checks has run on January. Not sure if some (transitive) deps have changed since then.

**Comment by echarles** [comment]
@blink1073 The goal of this PR is reached. It solves the casperjs issue. The `base` javascript test pass, included the sanitizer ones as requested on https://github.com/jupyter/notebook/pull/6354#issuecomment-1095038309

The service and notebook js tests have failures, but a lot of them pass. The goal is to fix them in subsequent PRs.

I don't think the python failures are related to the changes of this PR.

```
Test file: /home/runner/work/notebook/notebook/notebook/tests/base/security.js  
PASS Safe: '<p>Hi there</p>'
PASS Safe: '<h1 class="foo">Hi There!</h1>'
PASS Safe: '<a data-cite="foo">citation</a>'
PASS Safe: '<div><span>Hi There</span></div>'
PASS Sanitized: '<script>alert([99](https://github.com/jupyter/notebook/runs/5984992097?check_suite_focus=true#step:9:99)9);</script>' => ''
PASS alert removed
PASS Sanitized: '<a onmouseover="alert(999)">9...' => '<a>999</a>'
PASS alert removed
PASS Sanitized: '<a onmouseover=alert(999)>999...' => '<a>999</a>'
PASS alert removed
PASS Sanitized: '<IMG """><SCRIPT>alert("XSS")...' => '<img>"&gt;'
PASS alert removed
PASS Sanitized: '<IMG SRC=# onmouseover="alert...' => '<img src="#">'
PASS alert removed
PASS Sanitized: '<<SCRIPT>alert(999);//<</SCRIPT>' => '&lt;'
PASS alert removed
PASS Sanitized: '<SCRIPT SRC=http://ha.ckers.o.../' => ''
PASS alert removed
PASS Sanitized: '<META HTTP-EQUIV="refresh" CO...' => ''
PASS alert removed
PASS Sanitized: '<META HTTP-EQUIV="refresh" CO...' => ''
PASS alert removed
PASS Sanitized: '<IFRAME SRC="javascript:alert...' => '<iframe></iframe>'
PASS alert removed
PASS Sanitized: '<IFRAME SRC=# onmouseover="al...' => '<iframe></iframe>'
PASS alert removed
PASS Sanitized: '<EMBED SRC="data:image/svg+xm...' => ''
PASS alert removed
PASS Sanitized: '<style src="http://untrusted/...' => ''
PASS alert removed
PASS Sanitized: '<style>div#notebook { backgro...' => ''
PASS alert removed
PASS Sanitized: '<div style="background-color:...' => '<div></div>'
PASS alert removed
Test file: /home/runner/work/notebook/notebook/notebook/test
```

**Comment by echarles** [comment]
https://github.com/jupyter/notebook/pull/6357 fixes the python `testpath` issue unrelated to this PR.

**Review by blink1073 — APPROVED** [review]
Thanks!

**Comment by echarles** [comment]
Thx @blink1073

**Pull request merged**
