### PR TITLE
View > Toggle line numbers

### PR DESCRIPTION
**Pull request by gnestor**
Implementation of https://github.com/jupyter/notebook/pull/1312. I moved the button from the toolbar to the View menu.

demo

### CODE REVIEW

**Comment by gnestor** [comment]
Added line number config persistence thanks to @Carreau and https://github.com/jupyter/notebook/pull/1423/commits/c04046430d2b10923ae3d08d367b629351283f1d

**Comment by gnestor** [comment]
@Carreau I think this is ready to merge if you would like to have the honors...

**Comment by rgbkrk** [comment]
Wonderful.

**Comment by ellisonbg** [comment]
Merged!

**Comment by maver1ck** [comment]
Is there an option to make line numbers enabled by default ?

**Comment by rgbkrk** [comment]
In your `~/.jupyter/nbconfig/notebook.json`set:

```
{
  "Cell": {
    "cm_config": {
      "lineNumbers": true
    }
  }
}
```

**Comment by juhasch** [comment]
Or run this in Python once:
```Python
from notebook.services.config import ConfigManager
c = ConfigManager()
c.update('notebook', {"CodeCell": {"cm_config": {"lineNumbers": True}}})
```

(Thanks to @takluyver in #2040)

**Pull request merged**
