### PR TITLE
Make dialogs draggable

### PR DESCRIPTION
**Pull request by gnestor**
Fixes https://github.com/jupyter/notebook/issues/2035

This simply calls `.draggable()` on `$(".modals")` when a modal receives a mousedown. I tried to add a `draggable` option and that didn't work. I also tried calling `.draggable()` on creation of a modal and that scrolled the page to the bottom.

screencap

### CODE REVIEW

**Comment by ivanov** [comment]
Sweet, @gnestor, thanks for this. I understand the motivation for having the whole modal be draggable, instead of just the header, but unfortunately that makes it impossible to select text from the modal (which makes editing the notebook metadata a rather painful experience). I sent you a patch to fix this - https://github.com/gnestor/notebook/pull/5

**Comment by gnestor** [comment]
Thanks @ivanov! I also added a "move" cursor to the modal header to indicate that it is now draggable 👍

**Comment by ivanov** [comment]
Oh wow, nice touch! 🎼 🍷 🎶 🍸  Very classy! :bowtie:

**Comment by gnestor** [comment]
@ivanov 😊

**Pull request merged**
