### PR TITLE
Move examples into docs folder, and integrate with docs.

### PR DESCRIPTION
**Pull request by jdfreder**
Also uploads the examples to RTD.  And adds a nice link to allow the reader to quickly open the original notebook on nbviewer.

@takluyver @ellisonbg

### CODE REVIEW

**Comment by takluyver** [comment]
:+1: This approach looks good.

I guess at some point we'll want the integration tool to generate a proper Sphinx `.. toctree::` directive, because I imagine Sphinx is currently spitting out warnings about documents not being in its list of contents. But that can be another day.

**Comment by jdfreder** [comment]
Thanks.  I'd still like to get rich output and widgets working, but I'd like to address that in another PR later.  Although it's not perfect, I'd like you to consider merging this as-is to expedite my docs work.  I'm going to be using the same general idea for the widgets repository, so I may end up consolidating the tools to a single repository somewhere (also making the link replacement a little more robust, if possible).

**Comment by takluyver** [comment]
I'm quite happy to merge this and keep iterating. I'll leave it until tomorrow so other people have a chance to have a look at it.

**Comment by ellisonbg** [comment]
Yes, let's merge and iterate...

On Thu, Jun 18, 2015 at 4:16 PM, Thomas Kluyver <notifications@github.com>
wrote:

> I'm quite happy to merge this and keep iterating. I'll leave it until
> tomorrow so other people have a chance to have a look at it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/pull/159#issuecomment-113315420>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by minrk** [comment]
:shipit: I trust you guys.

**Comment by damianavila** [comment]
:+1: to go in several steps...

**Pull request merged**
