### PR TITLE
h1 heading for dialog: issue #3936

### PR DESCRIPTION
**Pull request by joshuazeltser**
Fixed issue #3936. We have made the markdown popup have its title as h1 like the markdown text itself.

### CODE REVIEW

**Comment by takluyver** [comment]
I'm having a bit of trouble understanding the issue, but should it be h1 in *all* dialogs, rather than just this one?

Also, have you checked that increasing the heading level doesn't mess up the layout visually?

**Comment by joshuazeltser** [comment]
So I have checked the increased heading level on several browsers on windows and mac and the layout is fine visually. My changes are based on my understanding of the issue, which seems to say that as the markdown heading itself will be h1, the heading should be too.

**Comment by takluyver** [comment]
I don't think this is anything to do with the fact that the dialog is talking about markdown headings - I think that's just a confusing coincidence.

**Comment by joshuazeltser** [comment]
In that case should all dialogs have an h1 header?

**Comment by takluyver** [comment]
That's what I'm wondering. I've asked for clarification on #3936.

**Comment by jtpio** [comment]
Closing since there has not been any activity for a while, and the classic notebook UI has now moved to https://github.com/jupyter/nbclassic.

Please feel free to open the PR there if it is still relevant, thanks!

**Pull request closed without merging**
