### PR TITLE
Remove deprecated usage of `log.warn` prefer `log.warning`.

### PR DESCRIPTION
**Pull request by Carreau**
Treating just this notebookapp for now.

-- 
I'd like to find a nice way to turn some DeprecationWarning (and other warings) into errors using nose, without using a wrapper script, but it seem annoying.

### CODE REVIEW

**Comment by takluyver** [comment]
It looks like someone wrote a nose plugin for that:

https://github.com/Bernhard10/WarnAsError

I don't know how robust it is, but it's pretty simple.

**Comment by Carreau** [comment]
Yeah I saw that, but it turns **all** into error, I want to actually filter. 

I have the plugin working, I need to figureouthow to make entry point with flit.

**Comment by takluyver** [comment]
http://flit.readthedocs.org/en/latest/entrypoints.html :-)

**Comment by Carreau** [comment]
> http://flit.readthedocs.org/en/latest/entrypoints.html :-)

Yeah i found it, but nose does not seem to find the plugin when I do that,

**Comment by Carreau** [comment]
see https://github.com/Carreau/nose_warnings_filters/issues/1

**Comment by Carreau** [comment]
Can we merge that and workout testing later ?

**Pull request merged**
