### PR TITLE
 tree rename dialog - focus filename without extension

### PR DESCRIPTION
**Pull request by hiaselhans**
focus only the relevant part of the filename on rename dialog
this selects all prior to the first dot in the filename

(i accidently saved some files without extension, which led me to create this pr..)

### CODE REVIEW

**Comment by takluyver** [comment]
This looks reasonable to me, but I'll give others a chance to review it.

**Comment by ellisonbg** [comment]
Haha, yes I have run into this myself. Nice idea.

On Wed, Jun 3, 2015 at 2:55 PM, Thomas Kluyver <notifications@github.com>
wrote:

> This looks reasonable to me, but I'll give others a chance to review it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/pull/131#issuecomment-108626776>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by damianavila** [comment]
LGTM too...

**Comment by takluyver** [comment]
Alright, let's land it. Thanks @hiaselhans.

**Comment by hiaselhans** [comment]
cool! :palm_tree:

**Comment by rgbkrk** [comment]
Nice, thanks.

**Pull request merged**
