### PR TITLE
Revert "Use NPM, node ES5, and browserify."

### PR DESCRIPTION
**Pull request by rgbkrk**
Reverts jupyter/notebook#268

Since this did not get resolved before @jdfreder left and the only primary JS maintainer who will be around in this coming week is likely to be @carreau, I say we revert. We can aim again for this and provide feedback on how to address shortcomings of #268. If we have to create a branching strategy, we'll do it *before* we merge #268 again.

### CODE REVIEW

**Comment by ellisonbg** [comment]
With Jon's travels +1 to this revert. I would like us to continue to see if
we can get a stable version of this in 4.1 though (after Jon returns).

On Sat, Aug 29, 2015 at 3:59 PM, Kyle Kelley <notifications@github.com>
wrote:

> Reverts jupyter/notebook#268
> <https://github.com/jupyter/notebook/pull/268>
>
> Since this did not get resolved before @jdfreder
> <https://github.com/jdfreder> left and the only maintainer who will be
> around in this coming week is likely to be @carreau
> <https://github.com/carreau>, I say we revert. We can aim again for this
> and provide feedback on how to address shortcomings of #268
> <https://github.com/jupyter/notebook/pull/268>. If we have to create a
> branching strategy, we'll do it *before* we merge #268
> <https://github.com/jupyter/notebook/pull/268> again.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/jupyter/notebook/pull/364
> Commit Summary
>
>    - Revert "Use NPM, node ES5, and browserify."
>
> File Changes
>
>    - *M* .gitignore
>    <https://github.com/jupyter/notebook/pull/364/files#diff-0> (14)
>    - *D* .jshintrc
>    <https://github.com/jupyter/notebook/pull/364/files#diff-1> (6)
>    - *M* README.md
>    <https://github.com/jupyter/notebook/pull/364/files#diff-2> (33)
>    - *M* bower.json
>    <https://github.com/jupyter/notebook/pull/364/files#diff-3> (15)
>    - *D* notebook/amd.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-4> (35)
>    - *M* notebook/base/handlers.py
>    <https://github.com/jupyter/notebook/pull/364/files#diff-5> (4)
>    - *D* notebook/build.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-6> (35)
>    - *D* notebook/static-src/auth/js/loginmain.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-7> (14)
>    - *D* notebook/static-src/auth/js/main.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-8> (5)
>    - *D* notebook/static-src/base/js/globals.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-9> (94)
>    - *D* notebook/static-src/base/js/namespace.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-10> (70)
>    - *A* notebook/static/auth/js/loginmain.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-11> (14)
>    - *R* notebook/static/auth/js/loginwidget.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-12> (9)
>    - *R* notebook/static/auth/js/logoutmain.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-13> (10)
>    - *A* notebook/static/auth/js/main.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-14> (9)
>    - *R* notebook/static/base/js/dialog.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-15> (13)
>    - *R* notebook/static/base/js/events.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-16> (18)
>    - *R* notebook/static/base/js/keyboard.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-17> (20)
>    - *A* notebook/static/base/js/namespace.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-18> (82)
>    - *R* notebook/static/base/js/notificationarea.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-19> (9)
>    - *R* notebook/static/base/js/notificationwidget.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-20> (8)
>    - *R* notebook/static/base/js/page.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-21> (9)
>    - *R* notebook/static/base/js/security.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-22> (25)
>    - *R* notebook/static/base/js/utils.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-23> (63)
>    - *R* notebook/static/edit/js/editor.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-24> (34)
>    - *R* notebook/static/edit/js/main.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-25> (60)
>    - *R* notebook/static/edit/js/menubar.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-26> (21)
>    - *R* notebook/static/edit/js/notificationarea.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-27> (16)
>    - *R* notebook/static/edit/js/savewidget.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-28> (21)
>    - *R* notebook/static/notebook/js/about.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-29> (11)
>    - *R* notebook/static/notebook/js/actions.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-30> (6)
>    - *R* notebook/static/notebook/js/cell.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-31> (41)
>    - *R* notebook/static/notebook/js/celltoolbar.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-32> (12)
>    - *R* notebook/static/notebook/js/celltoolbarpresets/default.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-33> (12)
>    - *R* notebook/static/notebook/js/celltoolbarpresets/example.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-34> (9)
>    - *R* notebook/static/notebook/js/celltoolbarpresets/rawcell.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-35> (27)
>    - *R* notebook/static/notebook/js/celltoolbarpresets/slideshow.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-36> (9)
>    - *R* notebook/static/notebook/js/codecell.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-37> (48)
>    - *R* notebook/static/notebook/js/codemirror-ipython.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-38> (0)
>    - *R* notebook/static/notebook/js/codemirror-ipythongfm.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-39> (0)
>    - *R* notebook/static/notebook/js/commandpalette.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-40> (7)
>    - *R* notebook/static/notebook/js/completer.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-41> (15)
>    - *R* notebook/static/notebook/js/contexthint.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-42> (4)
>    - *R* notebook/static/notebook/js/kernelselector.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-43> (26)
>    - *R* notebook/static/notebook/js/keyboardmanager.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-44> (15)
>    - *R* notebook/static/notebook/js/main.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-45> (105)
>    - *R* notebook/static/notebook/js/maintoolbar.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-46> (14)
>    - *R* notebook/static/notebook/js/mathjaxutils.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-47> (14)
>    - *R* notebook/static/notebook/js/menubar.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-48> (25)
>    - *R* notebook/static/notebook/js/notebook.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-49> (45)
>    - *R* notebook/static/notebook/js/notificationarea.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-50> (24)
>    - *R* notebook/static/notebook/js/outputarea.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-51> (32)
>    - *R* notebook/static/notebook/js/pager.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-52> (10)
>    - *R* notebook/static/notebook/js/quickhelp.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-53> (17)
>    - *R* notebook/static/notebook/js/savewidget.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-54> (21)
>    - *R* notebook/static/notebook/js/scrollmanager.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-55> (4)
>    - *R* notebook/static/notebook/js/searchandreplace.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-56> (4)
>    - *R* notebook/static/notebook/js/textcell.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-57> (43)
>    - *R* notebook/static/notebook/js/toolbar.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-58> (6)
>    - *R* notebook/static/notebook/js/tooltip.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-59> (10)
>    - *R* notebook/static/notebook/js/tour.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-60> (48)
>    - *R* notebook/static/services/config.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-61> (36)
>    - *R* notebook/static/services/contents.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-62> (12)
>    - *R* notebook/static/services/kernels/comm.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-63> (57)
>    - *R* notebook/static/services/kernels/kernel.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-64> (32)
>    - *R* notebook/static/services/kernels/serialize.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-65> (18)
>    - *R* notebook/static/services/sessions/session.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-66> (16)
>    - *R* notebook/static/terminal/js/main.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-67> (40)
>    - *R* notebook/static/terminal/js/terminado.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-68> (14)
>    - *R* notebook/static/tree/js/kernellist.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-69> (16)
>    - *R* notebook/static/tree/js/main.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-70> (68)
>    - *R* notebook/static/tree/js/newnotebook.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-71> (26)
>    - *R* notebook/static/tree/js/notebooklist.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-72> (20)
>    - *R* notebook/static/tree/js/sessionlist.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-73> (12)
>    - *R* notebook/static/tree/js/terminallist.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-74> (20)
>    - *M* notebook/templates/edit.html
>    <https://github.com/jupyter/notebook/pull/364/files#diff-75> (2)
>    - *M* notebook/templates/notebook.html
>    <https://github.com/jupyter/notebook/pull/364/files#diff-76> (6)
>    - *M* notebook/templates/page.html
>    <https://github.com/jupyter/notebook/pull/364/files#diff-77> (7)
>    - *M* notebook/templates/terminal.html
>    <https://github.com/jupyter/notebook/pull/364/files#diff-78> (2)
>    - *M* notebook/templates/tree.html
>    <https://github.com/jupyter/notebook/pull/364/files#diff-79> (2)
>    - *M* notebook/tests/base/utils.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-80> (11)
>    - *M* notebook/tests/util.js
>    <https://github.com/jupyter/notebook/pull/364/files#diff-81> (4)
>    - *M* package.json
>    <https://github.com/jupyter/notebook/pull/364/files#diff-82> (33)
>    - *M* setup.py
>    <https://github.com/jupyter/notebook/pull/364/files#diff-83> (4)
>    - *M* setupbase.py
>    <https://github.com/jupyter/notebook/pull/364/files#diff-84> (200)
>
> Patch Links:
>
>    - https://github.com/jupyter/notebook/pull/364.patch
>    - https://github.com/jupyter/notebook/pull/364.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/pull/364>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by minrk** [comment]
OK to revert, we can take another stab later, when we have better tested the cases that were broken and figured out our branching plan.

**Comment by rgbkrk** [comment]
Going by @minrk, @ellisonbg's comments and @Carreau's feedback following #268's merge, I merged the revert.

**Comment by fperez** [comment]
Thanks folks, this is in line with my (belated) comments in #353...

**Pull request merged**
