### PR TITLE
Support multiple cell selections in markdown, raw, and code conversions

### LINKED ISSUE #803: to-markdown should apply on all selection
related #802

### PR DESCRIPTION
**Pull request by parente**
Builds atop PR #790 for issue #802. Addresses the missing function comment. Also handles multiselect in the to_markdown and to_raw functions to fix #803 and #804.

Manually vetted. I can look into adding some tests.

/cc @parleur @Carreau @captainsafia

### CODE REVIEW

**Comment by parente** [comment]
One additional comment: the behavior after conversion here is that the multiselect collapses and the focus remains where it is.

**Comment by parente** [comment]
Quick and dirty tests added for conversion behavior plus selection after convert.

**Comment by Carreau** [comment]
+1 thanks a lot for that !

**Comment by parleur** [comment]
A big thank for that. It helps a lot.

**Pull request merged**
