### PR TITLE
[WIP] Read binary files in chunks

### LINKED ISSUE #96: Uploading large files crashes the browser
If you try to upload a file that is larger than ~35mb the browser tab will crash about 5 seconds after clicking "Upload".  

If we could warn the user about large files or implement a file uploader the user expirience would be better.

screen shot 2015-05-15 at 1 44 38 pm

screen shot 2015-05-15 at 1 47 11 pm

screen shot 2015-05-15 at 1 47 35 pm

```
# python -c "import IPython; print(IPython.sys_info())"
{'commit_hash': u'fd4ede2',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/usr/local/lib/python2.7/dist-packages/IPython',
 'ipython_version': '4.0.0-dev',
 'os_name': 'posix',
 'platform': 'Linux-3.13.0-49-generic-x86_64-with-Ubuntu-14.04-trusty',
 'sys_executable': '/usr/bin/python',
 'sys_platform': 'linux2',
 'sys_version': '2.7.6 (default, Mar 22 2014, 22:59:56) \n[GCC 4.8.2]'}
```

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #96.

I verified this works with a 340MB file (that crashed in the previous version), and also still works with `.ipynb` files.

### CODE REVIEW

**Comment by blink1073** [comment]
I verified this works with a 340MB file.

**Comment by blink1073** [comment]
Well, almost works, the files are corrupted, I'll try again tomorrow...

**Comment by blink1073** [comment]
This solves the upload portion, but not the download back to the server portion.  We need to support a similar chunked protocol on the XHR end.

**Comment by blink1073** [comment]
When we `save()` a file, we could send the size as part of the first call to `/api/contents/ PUT`, then send the blobs after.

**Comment by blink1073** [comment]
A similar protocol would be needed for `get()` to support large file download.

**Comment by ellisonbg** [comment]
@blink1073 do you think this is stable enough to consider for 4.1?

**Comment by ellisonbg** [comment]
Verbally "no" so marking as 4.2

**Comment by tritemio** [comment]
This is an important feature for me. I'm using the upload for an online demo to convert data files to a standard format.

If there is something I can do to help to speed up the inclusion of this feature I'd be glad to help.

**Comment by blink1073** [comment]
I think the simplest way would be to add an optional `chunks_remaining` field to the REST API model and use the existing base64 encoding.  Then you would call `save` with each chunk from `notebooklist.js`.  The server would have to be updated to detect the presence of `chunks_remaining`, and keep a file handle open until `chunks_remaining` is zero.  Thoughts?

**Comment by takluyver** [comment]
Is it worth looking for existing solutions? Uploading a large file over HTTP isn't that unusual, is it?

**Comment by blink1073** [comment]
From what I've gathered in searching, the consensus is to use the HTML5 FileReader API using binary chunks.  There are *uploader* libraries that handle the chunking/resuming, but we also need to stream downloads from the server.  Either way, we'd have to implement the logic on the server to handle streaming.

**Comment by Carreau** [comment]
That has gone stale, I'm going to close to keep the active PR queue short, and tag with "Closed PR" so that we can reopen when needed. Thanks a lot @blink1073 for getting that started .

**Pull request closed without merging**
