### PR TITLE
Respect keyboard manager state in clipboard logic

### LINKED ISSUE #1341: Copy / paste disabled in dialogs
Since the introduction of copy/paste behavior for notebook cells, the `embed interactive widgets` command does not work because the 'copy' command copies the content of the current cell instead of the content of the dialog's textarea.

It would probably work if the event listeners for 'copy' and 'paste' events were added to `#notebook` instead of the global `document`.

cc @Carreau @takluyver

### PR DESCRIPTION
**Pull request by jdfreder**
cc @takluyver @Carreau 

closes #1341

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
👍

**Comment by SylvainCorlay** [comment]
Arg, the test failures seem unrelated.

**Comment by takluyver** [comment]
Looks OK to me. We were already checking it on paste, but it makes sense to do it on copy as well.

I've just restarted one of the failing test jobs to see if it still fails. It didn't sound like anything related to this, but it was the same failure between Python versions, which makes it seem like something real.

**Comment by minrk** [comment]
It's not related to this PR, but it is a real failure. The only thing I've tracked down is that casperjs is 1.1.0-beta5 in the last success, and 1.1.0 after it starts failing.

I have [reproduced the failure](https://travis-ci.org/minrk/notebook/jobs/122752949) with current master.

**Comment by minrk** [comment]
I opened #1348 to pin casper to the last known-good version, in case that's really the issue.

**Comment by minrk** [comment]
Merging, since the failures aren't related to this PR, and with #1348 in, master should still pass.

**Comment by SylvainCorlay** [comment]
Thanks!

**Comment by jdfreder** [comment]
Thank you for looking into this @minrk ! 

@takluyver yeah, there was a dialog with a text area that was designed to be copied from in ipywidgets that wasn't working.  Paste was though ;)

**Pull request merged**
