### PR TITLE
Improve the error message for the nbextension.

### LINKED ISSUE #1624: more informative message for nbextension install
Hi,

First, I did

```bash
jupyter nbextension install  nglview --user --py
```

and got KeyError message

```bash
  File "/home/haichit/anaconda3/envs/ipywidgets5/lib/python3.5/
site-packages/notebook/nbextensions.py", 
line 1125, in _get_nbextension_metadata

    raise KeyError('The Python module {} is not a valid nbextension'.format(module))
KeyError: 'The Python module nglview is not a valid nbextension'
```

So I blindly tried 
```bash
$ jupyter nbextension enable nglview-js --user
Enabling notebook extension nglview-js...
      - Validating: problems found:
        - require?  X nglview-js
```

Both of the error messages did  not help me to fix my issue.

Finally I just realized that I did not put private method in my `__init__.py` folder

```python
def _jupyter_nbextension_paths():
    return [{
        'section': 'notebook',
        'src': 'static',
        'dest': 'nglview',
        'require': 'nglview/extension'
    }]
```

It would be great it developers can make clearer message. thanks.

### PR DESCRIPTION
**Pull request by Carreau**
Closes #1624

--- 
@hainm would this be better? 

Relatively simple, so marking as 4.3, unless @gnestor disagree now that he is the notebook grand master.

### CODE REVIEW

**Comment by hainm** [comment]
> would this be better?

yes. thanks. (It's always better to give a direct instruction in error message than asking users to ask in forum or google :D).

**Comment by Carreau** [comment]
> yes. thanks. (It's always better to give a direct instruction in error message than asking users to ask in forum or google :D).

Yes we are trying to improve aur deprecation warnings as well...

**Comment by gnestor** [comment]
@hainm Thanks for the PR!

@Carreau Should we:

* Merge this into master now?
* Merge into master when we are closer to a 4.3 release?
* Merge this into 4.x branch?

**Comment by minrk** [comment]
@gnestor in general, PRs are against master unless they only affect a backport branch. If a PR affects master and should be backported, the general flow is:

0. mark PR with milestone for the next backport release (4.3)
1. merge into master
2. backport to 4.x
3. push updated 4.x branch

Backports can be done in a variety of ways, but we have [a script](https://github.com/ipython/ipython/blob/master/tools/backport_pr.py) for automating the common process of:

1. download [the patch](https://patch-diff.githubusercontent.com/raw/jupyter/notebook/pull/1645.patch)
2. checkout the 4.x branch
3. apply the patch
4. make a commit

which works for simple cases, at leats.

In this case, it would be:

    python /path/to/ipython-repo/tools/backport_pr.py jupyter/notebook 4.x 1645

After master and backport branches have diverged, the script may not work and backporting the patch by hand may be necessary. If you want to be conservative after manually backporting a patch, a PR against the backport branch would be appropriate.

**Comment by Carreau** [comment]
Thanks @minrk, I"m going to copy your explanation on the Jupyter/jupyter repo for it to appear in the documentation !

**Comment by Carreau** [comment]
I'm also wondering how current master and what should be 4.x differ and whether we should retarget things and says that master == 4.x or, release a 5.0 instead of 4.x

**Comment by minrk** [comment]
@Carreau we could mark it 4.x. I think we would have to roll back some changes to do so, though.

**Comment by gnestor** [comment]
Ok, it looks like @minrk has backported this PR to 4.x. Give me a 👍 and I will merge this into master.

**Comment by minrk** [comment]
:+1: I did not mean to backport before this was merged.

**Comment by Carreau** [comment]
Well, go ahead and merge then !

Feel free to bump thing on 5.0 if needed. We discussed being a bit more aggressive to mark more things for 5.0 as backporting is painful.

**Comment by gnestor** [comment]
@Carreau Agreed. In the future, I will consider bumping milestones to 5.0.

**Pull request merged**
