### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by himani1**
Fixed minor mistakes in readme.

### CODE REVIEW

**Comment by takluyver** [comment]
Thanks for looking at this. You're right that the language there is a bit hard to read, but unfortunately I don't think your changes improve on what's currently there.

**Comment by himani1** [comment]
@takluyver : I understand. There was a bit too much use of 'the' in that. I thought with the changes I have proposed, it'd be clearer to read.

**Comment by takluyver** [comment]
Some of the 'the'-s are necessary for the text to make sense, though, and others are there to match the way we tend to talk about them - e.g. we say "the IPython kernel" rather than using "IPython kernel" as a name. However, we do use "Project Jupyter" as a name, so it doesn't need a 'the'.

**Comment by himani1** [comment]
@takluyver : Ok, I get it now. Thanks for correcting me.

**Comment by takluyver** [comment]
Thanks :-)

**Pull request merged**
