### PR TITLE
Bump minimum version of jQuery to 3.6.0

### PR DESCRIPTION
**Pull request by dylanramzn**
Resolves https://github.com/jupyter/notebook/issues/6469

### CODE REVIEW

**Comment by dylanramzn** [comment]
Tagging @RRosio as suggested by jweill-aws.

**Comment by echarles** [comment]
Looks like only 3 CI jobs have run. Is this expected?

**Comment by echarles** [comment]
@dylanramzn I think the CI was previously run on Travis which has probably been desactived. Do you think that you could backport the GitHub actions used in the 6.5.x branch ? https://github.com/jupyter/notebook/tree/6.5.x/.github/workflows

**Comment by echarles** [comment]
We have discussed this at the last community call with @jweill-aws. There has been a consensus to merge an release without a running CI, assuming the minimal sanity checks are done on a local env. This exceptional procedure is applied based on the nature of the change (jQuery front-end dependency upgrade being used all over the world).

I have tested locally this branch and as a user it works fine. I have also run the pytest command which returns ` 4 failed, 244 passed, 1 skipped, 1 xfailed, 71 warnings, 7 errors in 32.19s ` and was not able to successfully run any javascript test. The js failures are repicable on the vanilla 5.7.x branch. We could invest more time to make the javascript test work again but I wonder if this is worth to do that as we also said during the meeting that this will be the last patch accepted on this 5.7.x. branch.

```
python -m notebook.jstest base

Test group: base
Running tests with notebook directory '/var/folders/ly/vnyntf3n7q76382_rymt0qbm0000gn/T/tmp21ec1_8p'
Test file: /Users/echarles/Desktop/notebook-5.7.x/notebook/tests/base/highlight.js
Timeout for http://localhost:8888/a@b/
Is the notebook server running?
FAIL ".CodeMirror-code" still did not exist in 10000ms
#    type: uncaughtError
#    file: /Users/echarles/Desktop/notebook-5.7.x/notebook/tests/base/highlight.js
#    error: ".CodeMirror-code" still did not exist in 10000ms

#    stack: not provided
```

@dylanramzn BTW the latest jquery version is [3.6.0](https://code.jquery.com/jquery-3.6.0.min.js) and you are using here 3.5.0. Any reason for that?

**Comment by RRosio** [comment]
@dylanramzn Another thing to add is that pinning the dependency, jinja2 to a version <= 3.0.0 is necessary, as the more recent versions of jinja2 package cause import errors. I've verified this with a clean environment and a source package install which currently installs the most recent jinja2 version 3.1.2

<details>
<summary>Current Output with Jinja2==3.1.2</summary>
<br>
500: Internal Server Error
<br><br>
<pre>
[E 08:04:41.149 NotebookApp] Uncaught exception GET /notebooks/getting-familiar-jnb.ipynb (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/notebooks/getting-familiar-jnb.ipynb', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Users/rosioreyes/miniconda3/envs/check_jQuery/lib/python3.8/site-packages/tornado/web.py", line 1711, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/Users/rosioreyes/miniconda3/envs/check_jQuery/lib/python3.8/site-packages/tornado/web.py", line 3208, in wrapper
        return method(self, *args, **kwargs)
      File "/Users/rosioreyes/Desktop/code/jupyter/notebook5/notebook/notebook/notebook/handlers.py", line 90, in get
        self.write(self.render_template('notebook.html',
      File "/Users/rosioreyes/Desktop/code/jupyter/notebook5/notebook/notebook/base/handlers.py", line 519, in render_template
        return template.render(**ns)
      File "/Users/rosioreyes/miniconda3/envs/check_jQuery/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
        self.environment.handle_exception()
      File "/Users/rosioreyes/miniconda3/envs/check_jQuery/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
        raise rewrite_traceback_stack(source=source)
      File "/Users/rosioreyes/Desktop/code/jupyter/notebook5/notebook/notebook/templates/notebook.html", line 1, in top-level template code
        {% extends "page.html" %}
      File "/Users/rosioreyes/Desktop/code/jupyter/notebook5/notebook/notebook/templates/page.html", line 154, in top-level template code
        {% block header %}
      File "/Users/rosioreyes/Desktop/code/jupyter/notebook5/notebook/notebook/templates/notebook.html", line 112, in block 'header'
        {% for exporter in get_frontend_exporters() %}
      File "/Users/rosioreyes/Desktop/code/jupyter/notebook5/notebook/notebook/notebook/handlers.py", line 19, in get_frontend_exporters
        from nbconvert.exporters.base import get_export_names, get_exporter
      File "/Users/rosioreyes/miniconda3/envs/check_jQuery/lib/python3.8/site-packages/nbconvert/__init__.py", line 4, in <module>
        from .exporters import *
      File "/Users/rosioreyes/miniconda3/envs/check_jQuery/lib/python3.8/site-packages/nbconvert/exporters/__init__.py", line 3, in <module>
        from .html import HTMLExporter
      File "/Users/rosioreyes/miniconda3/envs/check_jQuery/lib/python3.8/site-packages/nbconvert/exporters/html.py", line 12, in <module>
        from jinja2 import contextfilter
    ImportError: cannot import name 'contextfilter' from 'jinja2' (/Users/rosioreyes/miniconda3/envs/check_jQuery/lib/python3.8/site-packages/jinja2/__init__.py)
</pre>
</details>

**Comment by dylanramzn** [comment]
> BTW the latest jquery version is [3.6.0](https://code.jquery.com/jquery-3.6.0.min.js) and you are using here 3.5.0. Any reason for that?

This PR was originally just a back port of the commit made previously for Notebook 6. https://github.com/jupyter/notebook/pull/5491

@RRosio I changed it to jQuery 3.6.0, and pinned jinja2 to <=3.0.0. I ran a sanity test and verified I can open a notebook and execute `1+1`.

**Comment by RRosio** [comment]
This PR looks good so I will go ahead and merge!

**Pull request merged**
