### PR TITLE
URL escape file path in iframe view handler

### PR DESCRIPTION
**Pull request by takluyver**
Closes gh-2775

### CODE REVIEW

**Comment by gnestor** [comment]
Thanks @takluyver! I can't reproduce this issue because I don't have a Windows environment, but it looks good to me. Shall I merge?

**Comment by takluyver** [comment]
I think it should be reproducible on any filesystem - try making a file like `a?b.html`, then selecting it and clicking the 'view' button.

**Comment by gnestor** [comment]
Hmmm, I'm actually getting a 404 for http://localhost:8888/view/a%3Fb.html 🤔

**Comment by takluyver** [comment]
With this PR or before it? That's expected before this PR.

**Comment by gnestor** [comment]
No I checked out this branch and rebuilt the JS (even though the change is a Python one) and restarted the server

**Comment by takluyver** [comment]
Weird. Were you definitely running with the server you restarted, and not another one you had running at the same time?

For reference, here's a test file in the editor:

screenshot from 2017-08-19 09-39-46

Here's the `/view/` page on master (you can't tell from this, but the 404 is inside the iframe: the `/view/` URL loads correctly, but refers to an invalid `/files/` URL):

screenshot from 2017-08-19 09-40-04

The error logged in the terminal:
```
[W 09:39:27.062 NotebookApp] 404 GET /files/a?b.html (127.0.0.1) 16.96ms referer=http://localhost:8888/view/a%3Fb.html
```

And here's it loading correctly on this branch:

screenshot from 2017-08-19 09-41-13

@minrk @Carreau and anyone else reading this, could you check this?

**Comment by gnestor** [comment]
I tried again on a new computer and alas, it worked! Merging...

Could this be another instance of indeterminate browser caching issue? It looks like you only edited Python so probably not...

**Comment by takluyver** [comment]
I don't think caching could affect this, but who knows!

**Pull request merged**
