### PR TITLE
fix notebook validation

### PR DESCRIPTION
**Pull request by minrk**
validate was imported from traitlets in #1527, clobbering validate from nbformat

### CODE REVIEW

**Comment by takluyver** [comment]
I'm a bit surprised we didn't have a test which caught this. Is there an easy way to add one that would exercise this code?

**Comment by minrk** [comment]
Me, too, as a matter of fact. I found it because I couldn't open any notebooks. Not sure how that doesn't get any exercise, as anything that opens a notebook should hit this.

**Comment by minrk** [comment]
Oh, now I know. It's because I'm on a branch of traitlets where this invalid call to `validate` raises instead of instantiating an object that gets immediately thrown away.

We don't seem to have a test here for notebooks that fail validation.

**Comment by takluyver** [comment]
> We don't seem to have a test here for notebooks that fail validation.

Is it worth adding one? If you don't fancy doing it here, feel free to open an issue for it, and then I'll merge this.

**Comment by Carreau** [comment]
We should start adding linters when possible, this would have been caught as one import clober another.

**Comment by minrk** [comment]
I'll add a test.

Linters are nice, but can be trouble in CI. I like pyflakes since it mostly checks correctness, but since it gives no mechanism to tell it "No, really, it's fine" I don't think it's okay to use in CI. I've used flake8 + turning off most of its annoying checks to get basically pyflakes with some control.

**Comment by minrk** [comment]
Test added.

**Comment by takluyver** [comment]
Test failed ;-)

It's a Legacy Python thing:

```
Traceback (most recent call last):
  File "/home/travis/build/jupyter/notebook/notebook/services/contents/tests/test_contents_api.py", line 305, in test_get_nb_invalid
    self.make_txt(path, json.dumps(nb))
  File "/home/travis/build/jupyter/notebook/notebook/services/contents/tests/test_contents_api.py", line 169, in make_txt
    f.write(txt)
TypeError: must be unicode, not str
```

**Comment by minrk** [comment]
Argle bargle. Should be okay this time.

**Comment by takluyver** [comment]
Good job, thanks.

**Pull request merged**
