### PR TITLE
Update security docs to reflect new signature system

### PR DESCRIPTION
**Pull request by gnestor**
Closes https://github.com/jupyter/notebook/issues/1848

### CODE REVIEW

**Comment by gnestor** [comment]
@takluyver I've enabled "Allow edits from maintainers" so feel free to revise.

**Comment by takluyver** [comment]
There are also some bits earlier in the file that refer to the signature being stored in notebook metadata.

**Comment by takluyver** [comment]
myeh, I couldn't get the 'allow edits from maintainers' thing to work, so I've sent you gnestor/notebook#3 with some more changes.

**Comment by gnestor** [comment]
Looks good to me. Merge at will 👍

**Pull request merged**
