### PR TITLE
Displays Warning Message if Cookies Not Enabled

### PR DESCRIPTION
**Pull request by ckilcrease**
This addresses #2337 

Adds a check for cookies using navigator.cookiesEnabled (tested in Chrome 64.0.3282.186, works both when cookies are blocked altogether and when only blocked for localhost:8888). If the user doesn't have cookies enabled, a request to enable cookies appears in body of modal as follows:

screen shot 2018-04-06 at 12 34 51 pm

### CODE REVIEW

**Comment by takluyver** [comment]
Thanks, this is looking good. A couple of things:

- Could we ask you to do this with your editor configured not to strip trailing spaces? If you look at [the changes](https://github.com/jupyter/notebook/pull/3511/files), you'll see that >100 lines are changed because of automatically removed whitespace. This can cause unnecessary conflict, and it makes `git blame` less useful.
- Having two buttons seems redundant; the user doesn't really have two options. Maybe get rid of the 'OK' button in this case?
- I think it would be good for the message to mention that Jupyter needs cookies to work. Also, if we can find a good website explaining what cookies are and how to make sure they're enabled on different browsers, we could link to it.

**Comment by ckilcrease** [comment]
Made most of the changes discussed, but I wanted to check in re: websites on cookies before choosing one; I think [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies) does a good job of explaining them concisely, although parts of the page go into details that might not really concern users (such as creating cookies, scope, etc.) - if this would be an issue, I can find one that only presents the overview/relevant details.

**Comment by ckilcrease** [comment]
Made most of the changes discussed, but I wanted to check in re: websites on cookies before choosing one; I think [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies) does a good job of explaining them concisely, although parts of the page go into details that might not really concern users (such as creating cookies, scope, etc.) - if this would be an issue, I can find one that only presents the overview/relevant details.

**Comment by takluyver** [comment]
Thanks!

I like MDN, but I think it's too technical for this. If people want help enabling cookies, they're probably going to be put off by all the detail. I was thinking more of pages like [this one](https://www.whatismybrowser.com/guides/how-to-enable-cookies/) or [this one](https://www.wikihow.com/Enable-Cookies-in-Your-Internet-Web-Browser#Using_Firefox_on_Desktop_sub). (Those are just the first ones I found with a quick search; there may well be better ones out there).

**Comment by ckilcrease** [comment]
That makes sense - I looked at a few other articles as well, but it seems like the WikiHow one is the most accurate (many seem to be outdated) and easy to follow, so at the moment I have that one linked as follows:

screen shot 2018-04-10 at 11 45 31 am

**Comment by takluyver** [comment]
Thanks @ckilcrease and @rosaswaby :-)

**Pull request merged**
