### PR TITLE
Update to JupyterLab 4.2.0rc0

### PR DESCRIPTION
**Pull request by jtpio**
Update to:

- https://github.com/jupyterlab/jupyterlab/releases/tag/v4.2.0b2
- https://github.com/jupyterlab/jupyterlab/releases/tag/v4.2.0b3
- https://github.com/jupyterlab/jupyterlab/releases/tag/v4.2.0rc0

### CODE REVIEW

**Comment by jtpio** [comment]
The file browser now displays `Modified` instead of `Last Modified`, related to https://github.com/jupyterlab/jupyterlab/pull/15948/files#r1571900809 :


| After | Before |
| ------- | ----------  |
| image | image |

**Comment by jtpio** [comment]
> The file browser now displays `Modified` instead of `Last Modified`, related to https://github.com/jupyterlab/jupyterlab/pull/15948/files#r1571900809 :

To be fixed by https://github.com/jupyterlab/jupyterlab/pull/16207

**Comment by krassowski** [comment]
The menu snapshot test failure is likely due to https://github.com/jupyterlab/jupyterlab/pull/16237

**Comment by jtpio** [comment]
bot please update playwright snapshots

**Comment by jtpio** [comment]
Ah looks like the cell toolbar needs adjustments:

image

**Comment by jtpio** [comment]
bot please update snapshots

**Comment by jtpio** [comment]
bot please update playwright snapshots

**Comment by jtpio** [comment]
bot please update snapshots

**Comment by jtpio** [comment]
bot please update playwright snapshots

**Pull request merged**
