### PR TITLE
Rely on umask for default directory permissions

### PR DESCRIPTION
**Pull request by takluyver**
Closes gh-2858

@minrk this feels somewhat unsatisfactory. The function I want to change is in `ipython_genutils`, but we're not making any changes there. So do we need to extract it to each package that uses it to make similar fixes?

### CODE REVIEW

**Comment by blink1073** [comment]
This [search](https://github.com/ipython/ipython/search?utf8=%E2%9C%93&q=ipython_genutils&type=) shows that `ipython` itself is no longer using `ipython_genutils` outside of `indent` and `dedent` in the docs generator.  Perhaps moving the functions to `jupyter_core` makes sense?

**Comment by blink1073** [comment]
To be clear: I mean copying the functions currently used in this repo to `jupyter_core`, releasing `jupyter_core`, and removing the dependency of this repo on `ipython_genutils`.

**Comment by takluyver** [comment]
That's a good idea. jupyter_core probably makes reasonable sense as a place for this.

**Comment by takluyver** [comment]
jupyter/jupyter_core#113 would add it to jupyter_core.

**Comment by takluyver** [comment]
Closing in favour of #3002.

**Pull request closed without merging**
