### PR TITLE
Add MathJax support for AsciiMath and Content MathML

### PR DESCRIPTION
**Pull request by gnestor**
* Test notebook: https://gist.github.com/gnestor/bbe456b13a0d1d8430d0caa8d8a8fd65
* MathML renders correctly using `IPython.core.display.HTML`
* AsciiMath renders correctly in Markdown cells
* MathML and AsciiMath do not render correct on Github/Gist
* Use `…` delimiters to use AsciiMath in a Markdown cell

### CODE REVIEW

**Comment by gnestor** [comment]
A couple questions:

* Are `...` delimiters for AsciiMath standard?
* What version of notebook/nbviewer is Github running? How often to they update? Will this prove problematic for users if these features are enabled in their local environment but not elsewhere like Github?

**Comment by minrk** [comment]
> What version of notebook/nbviewer is Github running? How often to they update?

I don't know what version of nbconvert GitHub is using, but they seem to update extremely rarely, if ever, and have not been responsive in particular to longstanding math rendering errors in the version they still have deployed.

> Will this prove problematic for users if these features are enabled in their local environment but not elsewhere like Github?

Yes, likely. We can propagate it to nbconvert easily enough, so it can land on nbviewer probably before we release it in the stable version of the live notebook.

> Are ... delimiters for AsciiMath standard?

I'm not sure what's standard in AsciiMath, but what's the impetus for supporting asciimath here? The `$` delimiters we started with for mathjax have proven pretty troublesome, since any delimiter type thing is a defacto extension of markdown, which gets hairy when it starts interacting with the markdown rendering, and further loosens the definition of what markdown we actually support (since it's no longer markdown once there is math).

**Comment by rgbkrk** [comment]
Yeah I'd like to let the MathML play out before doing Ascii Math. I haven't seen much use of it and it seems like development has slowed down. I'd want to wait on extensions to commonmark for further mathiness.

**Comment by gnestor** [comment]
Ok removed AsciiMath support. Is there any issue with supporting Content MathML?

**Comment by rgbkrk** [comment]
Nah, I think this looks good. You'll want to rebase with master now that I merged your constants PR.

**Comment by poke1024** [comment]
Getting rid of AsciiMath is fine. Changes look good to me.

**Comment by gnestor** [comment]
Ok, we're rebased and ready to merge 👌

**Comment by gnestor** [comment]
I'm having a hard time rebasing this branch and given that the only outstanding change left is Content MathML support, I am closing this PR and submitting a new one: https://github.com/jupyter/notebook/pull/1685

**Pull request closed without merging**
