### PR TITLE
Remove cell toolbar reminder

### PR DESCRIPTION
**Pull request by gnestor**
This is supposed to be removed before releasing 5.0

### CODE REVIEW

**Comment by takluyver** [comment]
+1

@Carreau is this OK with you? I seem to remember you added the reminder.

**Comment by Carreau** [comment]
Sure!

**Comment by takluyver** [comment]
I merged this and then thought 'wait, what about where this function is called?' :-(  PR coming up

**Comment by takluyver** [comment]
#2333

**Pull request merged**
