### PR TITLE
[WIP] [3335] Convert JS tests to Selenium

### PR DESCRIPTION
**Pull request by arovit**
I want to contribute to converting JS tests to selenium tests. This patch is for converting notebook/prompt_numbers.js to selenium/test_prompt_numbers.py. 
Also removed notebook/prompt_numbers.js

This is a new PR for [3551](https://github.com/jupyter/notebook/pull/3551)

### CODE REVIEW

**Comment by arovit** [comment]
@takluyver Please review and let me know if anything needs to be improved.

**Comment by takluyver** [comment]
BTW, there's no need to open a new PR when someone requests changes - just push more commits to the same branch, and the PR updates.

**Comment by takluyver** [comment]
Looks good, thanks.

**Comment by arovit** [comment]
thanks @takluyver , looking forward to contributing more.

**Pull request merged**
