### PR TITLE
Add a promise for app_initialized event.

### PR DESCRIPTION
**Pull request by takluyver**
See gh-2499

The idea is that custom.js code which was previously listening for `app_initialized.NotebookApp` events can do this instead:

```javascript
define([
        'base/js/namespace',
        'base/js/promises'
     ], function(Jupyter, promises) {
         promises.app_initialized.then(function(appname) {
             if (appname === 'NotebookApp') {
                 do_stuff()
             }
         });
     });
```

I've milestoned this for 5.1 so that we consider it, as I think this is the answer to a long-running annoyance with the event firing before the code listens for it. But I don't mind if we decide to push it back to a later release.

### CODE REVIEW

**Comment by minrk** [comment]
Seems like a good solution to me.

**Comment by gnestor** [comment]
Looks good to me. Should we update the custom.js docs?

**Comment by minrk** [comment]
@gnestor good call. I pushed an update to custom.js

**Comment by takluyver** [comment]
Thanks - I was just about to look at it, so you saved me a few minutes. :-)

**Pull request merged**
