### PR TITLE
Update to JupyterLab `4.1.0a3`

### PR DESCRIPTION
**Pull request by jtpio**
Update to the latest JupyterLab 4.1 pre-release: https://github.com/jupyterlab/jupyterlab/releases/tag/v4.1.0a3

Fixes https://github.com/jupyter/notebook/issues/6404

- [x] Bump `@jupyterlab` packages
- [x] Enable `showFullPath` by default: https://github.com/jupyterlab/jupyterlab/pull/14866

image

- [x] Enable the experimental inline completer: https://github.com/jupyterlab/jupyterlab/pull/15160
- [x] Check other items from https://github.com/jupyterlab/jupyterlab/releases/tag/v4.1.0a3

### CODE REVIEW

**Comment by jtpio** [comment]
> Enable the experimental inline completer

Looking nice:

https://github.com/jupyter/notebook/assets/591645/4e0bdd08-fec9-4e54-9dcf-42119688632c

**Comment by d5423197** [comment]
Hello there, is there any tutorial or docs which can guide user to setup for this feature?

**Comment by jtpio** [comment]
> Hello there, is there any tutorial or docs which can guide user to setup for this feature?

Not yet, this is all still very new!

The next steps would be to get https://github.com/jupyterlab/jupyter-ai/pull/465 merged and released. And then be able to use Jupyter AI in Notebook 7: https://github.com/jupyterlab/jupyter-ai/issues/504

But maybe this can still happen before the JupyterLab 4.1 and Notebook 7.1 final releases.

**Comment by d5423197** [comment]
Thanks for your reply. I saw this feature has been merged into notebook==7.1.0a1. I just installed this version. Can I use it in this version of notebook?

**Comment by jtpio** [comment]
> Thanks for your reply. I saw this feature has been merged into notebook==7.1.0a1. I just installed this version. Can I use it in this version of notebook?

If you want, you can try installing https://github.com/krassowski/jupyterlab-transformers-completer from source. As stated on the README, completions will be very basic so don't expect something at the level of GitHub copilot yet.

Then we would need the two PRs linked above to be merged and released to use better models via Jupyter AI.

**Pull request merged**
