### PR TITLE
Use `tini` in Dockerfile for zombie process reaping

### PR DESCRIPTION
**Pull request by jakirkham**
Follows from here ( https://github.com/jupyter/notebook/issues/334 ).

Contains this ( https://github.com/jupyter/notebook/pull/542 ).

### CODE REVIEW

**Comment by minrk** [comment]
Needs rebase. Can you do that, and remove `scripts/lxc-launch.sh`?

**Comment by jakirkham** [comment]
Sure, in progress. Can I ask why we are running `apt-get update` twice? Is it needed for some reason?

**Comment by jakirkham** [comment]
Ok, ready for more feedback.

**Comment by jakirkham** [comment]
Sorting out a few more things.

**Comment by jakirkham** [comment]
Sorry for all the noise. I think this is good to go.

**Pull request merged**
