### PR TITLE
Automated Changelog Entry for 0.0.0 on main

### PR DESCRIPTION
**Pull request by jtpio**
Automated Changelog Entry for 0.0.0 on main
```
Python version: 0.0.0
npm version: @jupyter-notebook/root: 0.1.0
npm workspace versions:
@jupyter-notebook/app: 7.0.0-alpha.5
@jupyter-notebook/buildutils: 7.0.0-alpha.5
@jupyter-notebook/metapackage: 7.0.0-alpha.5
@jupyter-notebook/application: 7.0.0-alpha.5
@jupyter-notebook/application-extension: 7.0.0-alpha.5
@jupyter-notebook/console-extension: 7.0.0-alpha.5
@jupyter-notebook/docmanager-extension: 7.0.0-alpha.5
@jupyter-notebook/documentsearch-extension: 7.0.0-alpha.5
@jupyter-notebook/help-extension: 7.0.0-alpha.5
@jupyter-notebook/lab-extension: 7.0.0-alpha.5
@jupyter-notebook/notebook-extension: 7.0.0-alpha.5
@jupyter-notebook/terminal-extension: 7.0.0-alpha.5
@jupyter-notebook/tree-extension: 7.0.0-alpha.5
@jupyter-notebook/ui-components: 7.0.0-alpha.5
```

After merging this PR run the "Full Release" Workflow on your fork of `jupyter_releaser` with the following inputs
| Input  | Value |
| ------------- | ------------- |
| Target | jupyter/notebook  |
| Branch  | main  |
| Version Spec | next |
| Since | v7.0.0a4 |

### CODE REVIEW

**Comment by jtpio** [comment]
The workflow that produced this changelog PR: https://github.com/jtpio/jupyter_releaser/runs/6864796475?check_suite_focus=true

**Comment by blink1073** [comment]
@jtpio I pinged you on gitter with more context.

**Comment by blink1073** [comment]
Yeah, it looks like releaser wasn't able to find the version correctly.  This seems related to the points raised by @agoose77 [here](https://github.com/jupyterlab/hatch-jupyter-builder/pull/21).

**Comment by blink1073** [comment]
Closing in favor of #6450

**Pull request closed without merging**
