### PR TITLE
include cross-origin check when allowing login URL redirects

### PR DESCRIPTION
**Pull request by minrk**
allows cross-origin setups to use the login page and redirect back

### CODE REVIEW

**Comment by blink1073** [comment]
👍

**Comment by Carreau** [comment]
`s/redirect/redirect_unsafe/g`, `s/_redirect_safe/redirect/g` from a best practice ? Or, if it's to not break API, prepare for a switch in next major version ?

**Comment by takluyver** [comment]
`redirect` is a method defined by tornado, so let's not change what it means.

**Comment by Carreau** [comment]
> redirect is a method defined by tornado, so let's not change what it means.
>  Show all checks

Ok.

**Pull request merged**
