### PR TITLE
Fix command palette appearance on FF.

### LINKED ISSUE #559: Command palette rendering broken on FireFox
Correct in Chrome:
screenshot from 2015-10-08 10 25 07

Wrong in FireFox:
screenshot from 2015-10-08 10 24 49

### PR DESCRIPTION
**Pull request by Carreau**
Closes #559

### CODE REVIEW

**Comment by ellisonbg** [comment]
Someone want to confirm the fix?

**Comment by Carreau** [comment]
Can I self-confirm ?

ffcp

**Comment by willingc** [comment]
@Carreau LGTM :sunflower:

**Comment by jdfreder** [comment]
I'm checking this out now...

**Comment by jdfreder** [comment]
Tested, fixes the problem for me!  Thanks @Carreau !

**Pull request merged**
