### PR TITLE
[WIP] Use DOM history API for navigating directories

### PR DESCRIPTION
**Pull request by gnestor**
Closes https://github.com/jupyter/notebook/issues/307

### CODE REVIEW

**Comment by gnestor** [comment]
This passes my basic user testing but I'm pretty sure there are some edge cases that may break this so it's marked as WIP.

**Comment by rgbkrk** [comment]
Awesome thanks for going after this!

One edge case worth trying — do a right click and “open in new tab”

**Comment by blink1073** [comment]
This is great @gnestor!  We'll be cribbing this for use with `lab/tree`.  cf https://github.com/jupyterlab/jupyterlab/issues/2532

**Comment by blink1073** [comment]
cc @afshin

**Comment by afshin** [comment]
Thanks for the heads up, @blink1073. Nice one, @gnestor!

**Comment by takluyver** [comment]
Nice, this feels super snappy. :-) I've tried opening in a new tab as @rgbkrk suggests, and it seems to work correctly.

However, something is going wrong with the breadcrumbs - when I click on them to navigate back up, the URL bar does not update. And if I navigate down three directories and then use the breadcrumbs to go up one, it requests the wrong thing (e.g. if I navigate to `Code/astcheck/dist`, and then click *astcheck* in the breadcrumbs, it requests `astcheck` instead of `Code/astcheck`).

**Comment by takluyver** [comment]
I pushed a couple of commits to fix things for me and make sure we're using `base_url` where necessary.

The test failures appear to be unrelated - #3127

**Comment by takluyver** [comment]
@gnestor is there more you want to do with this, or shall we merge it so that people can try it out in master?

**Comment by takluyver** [comment]
:-) As this is a user-visible change, it would be good to write a little bit about it for the release notes.

**Comment by gnestor** [comment]
Is this the same test error that you saw before: https://travis-ci.org/jupyter/notebook/builds/316101183?utm_source=email&utm_medium=notification

Ok, I'll update release notes now...

**Comment by takluyver** [comment]
No, that's a different failure. It seems to be that the linkcheck is failing because nbviewer is down.

**Comment by takluyver** [comment]
https://github.com/jupyter/nbviewer/issues/746

**Pull request merged**
