### PR TITLE
Add post-checkout hook and better development documentation

### LINKED ISSUE #697: Document development install
There should be instructions in the README (or at least linked to from the README) on how to setup a development install. If this information is documented somewhere, it is at least not easily accessible. Things that should ideally be included in this:

* [x] post-checkout hooks for updating and recompiling javascript and css
* [x] instructions for how to install post-checkout hooks
* [x] instructions for how to update js components, compile js, and compile css
* [x] instructions for how to run the test suite

### PR DESCRIPTION
**Pull request by jhamrick**
Fixes #697

@willingc @Carreau

### CODE REVIEW

**Comment by jhamrick** [comment]
Anything here that I'm missing? Anything else that would be useful to know that didn't occur to me (or that I'm not aware of)?

**Comment by willingc** [comment]
@jhamrick Heading to the airport but it looks good on my initial skim (definitely better than what we had before). 

Only thing that you might consider adding to the ``tools/post-checkout`` script is a check at the start to see if the symlink was created. If it hasn't been created, perhaps exit with a message to create the symlink.

**Comment by minrk** [comment]
The git hooks are already in the `git-hooks` directory, along with a README explaining how to use them.

**Comment by jhamrick** [comment]
Oh, hmm, not sure how I missed the git-hooks directory. Ok, will update this to refer to that and to remove the post-checkout hook that I added.

**Comment by jhamrick** [comment]
Done.

**Comment by minrk** [comment]
Awesome, thanks!

**Comment by willingc** [comment]
Nicely done @jhamrick. Thanks :ocean:

**Pull request merged**
