### PR TITLE
remove SYSTEM_NBEXTENSIONS_DIRS

### PR DESCRIPTION
**Pull request by minrk**
use SYSTEM_JUPYTER_PATH from core

for common logic with kernelspec installation

### CODE REVIEW

**Comment by Carreau** [comment]
is that a leftover of IPython thing ? can we check if `SYSTEM_NBEXTENSIONS_DIRS ` is set and log a warning ?

**Comment by minrk** [comment]
@Carreau how could it be set? It's a module constant.

**Comment by Carreau** [comment]
sorry, uppercase made me though as environemnt variable. was too tired this morning.

**Comment by damianavila** [comment]
LGTM

**Pull request merged**
