### PR TITLE
Toolbar buttons tooltip: show help instead of label

### PR DESCRIPTION
**Pull request by manics**
Currently the tooltip for a toolbar button with just an icon is the help text for the action/command.
If a toolbar button has a label the label text is shown alongside the button icon as expected, but it also replaces the tooltip help.

With this PR the help text is always shown as the tooltip.

### CODE REVIEW

**Comment by lresende** [comment]
What is the accessibility side effect of this change? @jasongrout @takluyver any thoughts here?

**Comment by kevin-bates** [comment]
@jasongrout - can you please comment on Luciano's accessibility question?  Otherwise, I think this looks good.

**Comment by kevin-bates** [comment]
@tgeorgeux - I believe you deal in the realm of UX.  Do these changes introduce any accessibility issues and, if so, might there be a way they can be addressed while still providing this improved behavior?

**Comment by tgeorgeux** [comment]
@kevin-bates Sorry I missed this ping. I don't really know enough about the mechanics of what's going on to know if this change will negatively impact accessibility. It looks like a net improvement to me, with @afshin's changes mentioned above.

**Comment by manics** [comment]
Thanks for looking, I've made the requested change.

**Comment by afshin** [comment]
Thank you!

**Pull request merged**
