### PR TITLE
Protection againt bad custom.js

### LINKED ISSUE #1363: Protect against bad custom.js
if custom.js has a bad require, (eg require something only available on 5.x , like `require('notebook')`) all hell break loose and the page do not load. 

That should not be the case.

Marking as 4.3 as it is a bit annoying to debug each time you revert to an older version.

### PR DESCRIPTION
**Pull request by parleur**
Just embed it in a try/catch

closes #1363

### CODE REVIEW

**Comment by Carreau** [comment]
Closes https://github.com/jupyter/notebook/issues/1363 I guess ?

**Comment by takluyver** [comment]
I think we should call @parleur 'Sprint', because he's so good at fixing issues tagged 'Sprint friendly' :-)

**Comment by Carreau** [comment]
@parleur aka 'Sprint', make also puns in his commits.

**Comment by minrk** [comment]
custom.js is also loaded on the `tree` and `edit` pages.

**Comment by parleur** [comment]
I am not really sure about the purpose of custom.js, but maybe it would be meaningful to have a single entry point for js injection? 
I mean, knowing there is three (and it's not obvious), I would first check in custom.js from where the script has been called.

So what about split custom.js in `notebook_custom.js`, `edit_custom.js`, and `tree_custom.js` ?

**Comment by Carreau** [comment]
> So what about split custom.js in notebook_custom.js, edit_custom.js, and tree_custom.js ?

These kind of already exists, and they are nbextensions. If you drop a file in `.jupyter/nbextension/` and modify `~/.jupyter/nbconfig/tree.json`, `~/.jupyter/nbconfig/notebook.json`, `~/.jupyter/nbconfig/edit.json` like so:

```
cat ~/.jupyter/nbconfig/tree.json
{
  "load_extensions": {
    "jupyter_cms/dashboard/main": true,
    "ipyparallel/main": true,
    "assignment_list/main": true
  }
}
```
(here I have 3 extensions enabled)

You can tell which extension to enable on which page, independently. And these files and layout is programmatically modifiable, which is better to install automatically multiple extensions. `custom.js` is just an artifact of the past (really we should just get rid of it ), but people are still using it, and it's damned convenient.

**Comment by minrk** [comment]
Custom.js is an early escape hatch for a lack of configurability in the frontend. As we add that configurability, the need for custom.js diminishes, but it isn't gone yet. It is my hope that JupyterLab, for instance, will have sufficient configurability and not load custom.js.

**Comment by takluyver** [comment]
Do we want this in 4.2.1?

**Comment by Carreau** [comment]
Manually backporting this one, because of the  webpack thing it's unhappy.
The backporting tool will mistakenly says this has not been backported.

**Pull request merged**
