### PR TITLE
[WIP] Use `requirejs` vs. `require`

### PR DESCRIPTION
**Pull request by gnestor**
Closes https://github.com/jupyter/notebook/issues/155

### CODE REVIEW

**Comment by jasongrout** [comment]
> Closes jupyterlab/jupyterlab#3281

Wrong issue?

**Comment by gnestor** [comment]
Yep, thanks @jasongrout 👌

**Comment by takluyver** [comment]
@gnestor is this still a WIP, or do you think it's ready to merge?

**Comment by gnestor** [comment]
@Carreau @rgbkrk Care to review before we merge? 

Here is the merged PR on ipython-contrib: https://github.com/ipython-contrib/jupyter_contrib_nbextensions/pull/1165

**Comment by takluyver** [comment]
Thanks @rgbkrk

**Pull request merged**
