### PR TITLE
Unmark cell after split.

### LINKED ISSUE #648: Split cell leave one cell marked.
I don't think that is intended.

### PR DESCRIPTION
**Pull request by jdfreder**
closes #648
alternative #655

### CODE REVIEW

**Comment by jdfreder** [comment]
@Carreau this is what you suggested, I actually prefer the alternative #655 coupled with a hotkey for unmark all.

**Comment by blink1073** [comment]
Did you intend to remove all the whitespace?

**Comment by ellisonbg** [comment]
I will try these two out...

On Mon, Oct 26, 2015 at 10:53 AM, Steven Silvester <notifications@github.com
> wrote:

> Did you intend to remove all the whitespace?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/pull/654#issuecomment-151163845>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jdfreder** [comment]
> Did you intend to remove all the whitespace?

Arg!  New atom setup, and I forgot to disable the whitespace removal.  New commit on its way, sorry.

**Comment by jdfreder** [comment]
White space should be fixed

**Pull request closed without merging**
