### PR TITLE
Bump upload size to 25MB

### PR DESCRIPTION
**Pull request by blink1073**
Tested with a 24MB file in Firefox and Chrome on OSX.

screen shot 2015-10-21 at 9 12 00 am

### CODE REVIEW

**Comment by minrk** [comment]
+1

**Comment by dsblank** [comment]
Should this limit be configurable? I could imagine that one might want to make the value larger, or smaller, for a set of users.

**Comment by blink1073** [comment]
This is a temporary work-around until we implement streaming binary uploads.

**Comment by dsblank** [comment]
Ok. But even in the future (Oh, it is Back to the Future just now!), I could imagine that the system has no set limit, but it could be configured so that there were one.

**Comment by minrk** [comment]
@blink1073 could you put the constant as a class-level private attribute, just so that it's a bit more easily overridable in a pinch?

**Comment by blink1073** [comment]
Better?

**Comment by minrk** [comment]
:+1: thanks!

**Comment by dsblank** [comment]
Cool! Thanks for this!

**Pull request merged**
