### PR TITLE
Add square logo and desktop entry files

### PR DESCRIPTION
**Pull request by befeleme**
Hi! 
Following the ancient discussion in #1922 I work on adding a desktop entry to Notebook when installed as RPM in Fedora. 
I was looking for the icon to use an thought the official [Jupyter logo](https://commons.wikimedia.org/wiki/File:Jupyter_logo.svg) would suit the best. The image, being rectangle more than square, got however unpleasantly distorted by the system. The graphics was resized so that it's 48x48px square with preserved original proportions and is easily scalable to any other square size.

If the files were included in Python package, they could be used by the other packagers as well. It'd be nice to have them coming from the upstream.

### CODE REVIEW

**Comment by befeleme** [comment]
As was pointed out to me, environments displaying smaller icons (like Xfce) would benefit from icon without the text _jupyter_ inside, so I add another file, favicon alike.
I propose to install the files using `data_files` which ensures the installation to given location. This works well both with system- and user-wide installation.
Looking forward to your opinion.

**Review by blink1073 — APPROVED** [review]
Very nice, thanks!

**Comment by befeleme** [comment]
@blink1073, just a quick question: when could the v. 6.3 be released? I'll help me adjust the next steps regarding the RPM package.

**Comment by blink1073** [comment]
We plan to cut 6.3 early next week.  I'm making a changelog entry PR today.

**Pull request merged**
