### PR TITLE
Add note on JupyterHub to docs

### PR DESCRIPTION
**Pull request by michaelpacer**
Checked that it looks fine once built, wasn't sure if it was an appropriate use of an important block. 

 addresses #1712

### CODE REVIEW

**Comment by michaelpacer** [comment]
I think it was a stalled build…not an actual error.

**Comment by minrk** [comment]
👍 cc @willingc

**Comment by willingc** [comment]
@michaelpacer Thank you! This doc change is eloquent and clear and does a great job capturing the input from @fperez on the the mailing list. Thanks for your work on this. Yes, you have used the important block correctly. I trust your judgement so please follow your instincts when to use them. :cake:

Very happy to merge. Thanks @minrk for the review too.

**Comment by fperez** [comment]
Great, thanks!!

**Pull request merged**
