### PR TITLE
Replaced 'Search and Replace' with 'Find and Replace'

### LINKED ISSUE #452: Replace "Search and Replace" with "Find and Replace"
@ellisonbg recommends that we rename the "Search and Replace" with "Find and Replace" to maintain consistency across editors that use a similar language to describe that functionality. I can give this one a go.

cc/ @Carreau

### PR DESCRIPTION
**Pull request by captainsafia**
Closes #452.

### CODE REVIEW

**Comment by jdfreder** [comment]
Line 185 of searchandreplace.js `.attr('id', 'search-and-replace')` should be `.attr('id', 'find-and-replace')`, and after doing that you'll need to update the less file - replace `#search-and-replace {` in `searchandreplace.less` with `#find_and_replace {`.  You can then rebuild the CSS by running `python setup.py css` in the notebook root IIRC

**Comment by jdfreder** [comment]
(I would have left those as line comments, but I couldn't figure out how to do it since those lines don't show in your diff and GitHub seems to have disabled commenting on lines that don't show in the diff - lame!)

**Comment by captainsafia** [comment]
@jdfreder — Solid!

**Comment by damianavila** [comment]
LGTM

**Comment by jdfreder** [comment]
Sweet!  Thanks @captainsafia

**Comment by Jeffiy** [comment]
I think the file name ``searchandreplace.js`` ``searchandreplace.less`` should be also changed.

**Pull request merged**
