### PR TITLE
Polyfill promises from the page template.

### PR DESCRIPTION
**Pull request by jasongrout**
Doing this from webpack as a plugin caused https://github.com/ipython/ipywidgets/issues/844 (and probably other issues we haven’t noticed), and also forced us to use the es6-promise Promise object instead of the native one.

### CODE REVIEW

**Comment by jasongrout** [comment]
This fixes ipython/ipywidgets#844

**Comment by ivanov** [comment]
👍 🍰  it works! Thanks @jasongrout !

**Comment by ivanov** [comment]
just waiting for the travis tests to pass...

**Comment by rgbkrk** [comment]
I don't think it's node + promises that are failing - I think it's the casper based tests.

**Comment by jasongrout** [comment]
Thanks. You can tell I'm taking a lot of shots in the dark. At first I thought it was phantom not supporting promises, but Slimer didn't seem to help much.

**Comment by jasongrout** [comment]
Ah, this might be the issue, since we are using the babel-loader for some reason: https://github.com/babel/babel-loader#note-transform-runtime--custom-polyfills-eg-promise-library

**Comment by jasongrout** [comment]
I think this is ready to go now. Instead of putting the polyfill on the page, I'm still including it in the webpack bundle, but this time as an explicit polyfill file instead of trying to use the ProvidePlugin mechanism.

When we switch away from using the babel-loader, I think we can reconsider using this approach.

**Comment by ivanov** [comment]
HUZZAH! 🍪 for @jasongrout !

**Comment by minrk** [comment]
@gnestor I marked this as 5.0, because it's webkit-related. The webkit stuff isn't in the 4.x branch. @jasongrout is there still something to do for the 4.x branch?

**Comment by jasongrout** [comment]
I think we're probably good - I wasn't seeing an issue on 4.2.x, at least.

**Pull request merged**
