### PR TITLE
Open all files with `/files` path except for `.html` and .svg`

### PR DESCRIPTION
**Pull request by gnestor**
Closes https://github.com/jupyter/notebook/issues/2404

### CODE REVIEW

**Comment by gnestor** [comment]
@takluyver Can you review?

**Comment by takluyver** [comment]
`.htm` should be treated this way as well, it's a common extension for html files. I wonder if we should be doing it on mime type instead of extension - I think anything that our server offers with mimetype `text/html` can have the same effect, and that can vary by system. In some cases, installed apps can affect what extensions are recognised for a mimetype.

@minrk @rgbkrk do you know of any file types other than html and svg that we should be displaying in the iframe?

**Comment by minrk** [comment]
In general, it's best to avoid a 'not_safe' blacklist, because it's easy to miss things (like the many synonyms for html) instead having a 'safe' list for things that can be trusted to be displayed raw. It seems like it makes more sense to specify a list of things that *don't* work in the iframe (are there examples other than PDF?)

**Comment by gnestor** [comment]
I updated so that `is_viewable` is used in place of `is_not_safe` (just includes `htm` and `html`). Every other file extensions that isn't editable will be opened using the `/files` path and handled by the browser. I also updated the `is_editable` list to be more comprehensive (using the list from https://github.com/sindresorhus/text-extensions/blob/master/text-extensions.json).

**Comment by takluyver** [comment]
Isn't that the same blacklisting approach just with the name 'viewable' in place of 'not_safe'?

I see `xht`, `xhtml`, `mht` and `mhtml` in the editable list - in certain circumstances, any of these could be rendered as HTML in a browser, so viewing them should open them in the iframe. This rather validates Min's point about the problems with a blacklist.

**Comment by gnestor** [comment]
I have updated this PR. The way it works now:

* By default, all files (not directories) are opened using `/files` prefix and display the "View" button
* If a file is html (according to the list of html extensions and `text/html` mime type), it's opened using the `/view` prefix
* If a file is editable (according to the list of editable extensions and `text/*` and `application/*` mime types), it's opened using the `/edit` prefix and displays the "Edit" button
* If a file is a notebook, it's opened using the `/notebooks` prefix
  * Notebooks can be edited in the text editor using the "Edit" button

**Pull request merged**
