### PR TITLE
Further highlight token info in log output

### LINKED ISSUE #1980: Make token URL clearer when no-browser is given
Or be more explicit on the login webpage that a token need to be passed, 
and can be found in the Cli that launched the notebook. 

Otherwise users can't log-in after upgrading to 4.3

(and print the token on the CLI in a more visible manner.)

### PR DESCRIPTION
**Pull request by minrk**
add critical-level log statement at the end of startup with token info

closes #1980

### CODE REVIEW

**Comment by rgbkrk** [comment]
One alarming thing about us logging this in general - if people choose to export their logs to external storage, this is now exposed in those logs. This helps the localhost and SSH based user so I understand why this is here, just a note for the future.

**Comment by minrk** [comment]
@rgbkrk good call. I've switched it so that it only logs the token if it's been automatically generated. Setting a token via config would result in nothing logged.

**Comment by rgbkrk** [comment]
@minrk great, thank you!

**Comment by gnestor** [comment]
@minrk Looks good. Is this ready to merge?

**Comment by minrk** [comment]
Thanks, @gnestor and @rgbkrk!

**Pull request merged**
