### PR TITLE
Add more border width to CodeMirror cursor

### PR DESCRIPTION
**Pull request by gnestor**
Closes https://github.com/jupyter/notebook/issues/2909

### CODE REVIEW

**Comment by gnestor** [comment]
@Carreau We're having a similar Appveyor build issue over here ☹️

**Comment by gnestor** [comment]
@takluyver Care to review and merge?

**Comment by Carreau** [comment]
Clicked on rebuild. I really don't understand how Appveyor works, I can'd find the team section anymore.

**Comment by gnestor** [comment]
Ya me niether...

**Comment by gnestor** [comment]
@Carreau Would you care to review/merge?

**Comment by Carreau** [comment]
Let's try.

**Comment by gnestor** [comment]
@meeseeksdev backport to 5.2.1

**Pull request merged**
