### PR TITLE
Remove keymaps that conflict with non-English keyboards

### PR DESCRIPTION
**Pull request by gnestor**
Fixes https://github.com/jupyter/notebook/issues/2379

### CODE REVIEW

**Comment by gnestor** [comment]
@minrk Care to review? This reverts some of https://github.com/jupyter/notebook/pull/963 which caused conflicts on non-English keyboards.

**Comment by minrk** [comment]
Is it just the ctrl-alt shortcuts or also the cmd-alt shortcuts that cause this problem? I would certainly be sad to lose those.

**Comment by gnestor** [comment]
@minrk This is only removing the <kbd>Cmd-Alt-[</kbd> shortcut, not all <kbd>Cmd-Alt-*</kbd>

**Comment by minrk** [comment]
Sorry. My question was whether it was `ctrl-alt-[` or `cmd-alt-[` or both that cause the issue.

**Comment by gnestor** [comment]
I inquired about that in the issue. Let's see what people say 👍 I think we just need to avoid using shortcuts that involve `[` and `]`, but I saw a one comment about `\` and @Carreau suggested that we also disable ones involving `/`.

**Comment by Carreau** [comment]
I believe that's anything that touch [,], and `alt`.  Alt is heavily use on french keyboard to type punctuation. You just can't bind by default to anything that uses alt. 
That one of the main reason why I'm not an emacs user as most alt-based shortcut were conflicting with typing. 

The MacOS keyboard is slightly different, but same battle. Alt is a critical key.

**Comment by gnestor** [comment]
Ok, so this PR just comments out the 2 commands that involve `alt` so I think we can merge this and iterate if necessary.

**Comment by Carreau** [comment]
> Ok, so this PR just comments out the 2 commands that involve alt so I think we can merge this and iterate if necessary.

Yep, good point.

**Pull request merged**
