### PR TITLE
Make JupyterLab notebook functional and add mathjax support

### PR DESCRIPTION
**Pull request by blink1073**
jupterlab-demo

### CODE REVIEW

**Comment by blink1073** [comment]
Looks like this needs a kick: https://travis-ci.org/jupyter/notebook/jobs/115536165

**Comment by jdfreder** [comment]
> needs a kick

:mans_shoe: :boom:

**Comment by minrk** [comment]
Thanks!

**Comment by willingc** [comment]
@blink1073 Cool.

**Pull request merged**
