### PR TITLE
Added keyboard shortcut for search and replace

### LINKED ISSUE #341: Search and replace Keybinding.
Implement default keybinding for Search and Replace. 

@parleur, you want to give it a try.

### PR DESCRIPTION
**Pull request by captainsafia**
Closes #341.

### CODE REVIEW

**Comment by minrk** [comment]
Is `/` available as a shortcut? I think it's pretty common for search (cc @Carreau for non-English keyboard perspective)

**Comment by ellisonbg** [comment]
Or also why not plain f?

**Comment by captainsafia** [comment]
Plain `f` is available so I changed it to that. I'm a little bit more in favor of it since it's on the home row.

**Comment by ellisonbg** [comment]
I probably prefer that. I know that `/` is used for search, but that tends
to be in more unix command line tools that many notebook users are not
familiar with.

On Wed, Sep 23, 2015 at 7:27 AM, Safia Abdalla <notifications@github.com>
wrote:

> Plain f is available so I changed it to that. I'm a little bit more in
> favor of it since it's on the home row.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/pull/486#issuecomment-142618226>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by minrk** [comment]
Makes sense to me. `f` it is.

**Pull request merged**
