### PR TITLE
Adding GUI Mirroring- issue #1852

### PR DESCRIPTION
**Pull request by samarsultan**
Hey @rgbkrk .
Please check this PR, it is a sample of applying the proposed design approach of UI mirroring.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Cool, how do I enable this? Do I switch my language to Arabic on my OS?

**Comment by samarsultan** [comment]
No, just from the browser settings.

**Comment by Carreau** [comment]
Great ! Thanks a lot @samarsultan to work on that !

I guess for test purpose, we can add a notebook command to force-switch rtl. 
Also I'm pretty sure you tried, but are all the `!important` necessary ?

I'm happy to merge that early and iterate.

**Comment by rgbkrk** [comment]
I'm cool bringing it in and iterating as well, we look forward to you iterating on it @samarsultan. :smile:

**Comment by samarsultan** [comment]
@Carreau ,thanks for your add-on . You are right , we may not need all the important except for 1 or 2 places. I'll re-push them .

**Comment by samarsultan** [comment]
@rgbkrk , do you mean by iterating on it to be fully supported ? If so , I just needed to gurantee that our approach is going to be suitable to submit the full patch.

**Comment by Carreau** [comment]
I think that by "iterating" we mean:

Feel free to submit partial patches, small patches are easier to review quickly and merge.

The time to review and land some changes increase with the size of the patch. 

It's even ok to get something in master have it available for a week or so and decide that it was not actually the right thing to do.

Does that make some sens ?

Thanks !

**Comment by rgbkrk** [comment]
By iterating, I mean that we should merge this and not expect perfection right away. We should make forward progress with you and continue patching to get closer to the ideal. I'm not a domain expert on this, so I want you to have plenty of freedom to support rtl for users. :smile:

**Comment by samarsultan** [comment]
With regard to this PR , I'm going to continue supporting the UI Mirroring alongside with the new requested features #2154 & #2156  ,if you are OK with them.

I need to ensure which branch to work against. Do I need to create a new branch to push my changes in (for ex. "bidi" branch)?

Thanks !

**Comment by Carreau** [comment]
> With regard to this PR , I'm going to continue supporting the UI Mirroring alongside with the new requested features #2154 & #2156 ,if you are OK with them.

Of course, we welcome your input and contribution on this !

> I need to ensure which branch to work against. Do I need to create a new branch to push my changes in (for ex. "bidi" branch)?

You likely want to always submit your work against master (that's the default GitHub configuration so that should be easy), but the exact branch you push your work to, does not really matter. You should anyway be able to push only on your fork. The only limiting factor is you need at least one branch per opened Pull Request. So if you are sure to always have only one PR "in flight" then you can always use the same "bidi" branch. Otherwise you can push things with different name like `bidi-fix-calendar`, and `bidi-fix-numeral` for example, that what I would do.

Also, just as a tip, we tend to not check messages on close issues/merged PR, so if we don't respond feel free to open a new issue.  If you have any other questions about git feel free to ask.

**Comment by samarsultan** [comment]
Thanks @Carreau , I 'll open a new Issue with the proposed design for the Bidi work.

**Pull request merged**
