### PR TITLE
Update to JupyterLab `4.0.0b1` and `4.0.0b2`

### PR DESCRIPTION
**Pull request by jtpio**
Update to https://github.com/jupyterlab/jupyterlab/releases/tag/v4.0.0b1 and https://github.com/jupyterlab/jupyterlab/releases/tag/v4.0.0b2

- [x] Update `@jupyterlab`, `@lumino` packages
- [x] Check https://github.com/jupyterlab/jupyterlab/pull/14053
- [x] Check https://github.com/jupyterlab/jupyterlab/pull/14141
- [x] Check https://github.com/jupyterlab/jupyterlab/releases/tag/v4.0.0b1
- [x] Check https://github.com/jupyterlab/jupyterlab/releases/tag/v4.0.0b2

### CODE REVIEW

**Comment by jtpio** [comment]
> Strangely the title and checkpoint indicator seem to be gone:

Looks like this piece of code is not hit on page reload: 

https://github.com/jupyter/notebook/blob/f0ec5f30e966a722a2d4a1678d3547523fea21e6/packages/notebook-extension/src/index.ts#L85-L88

Although the kernel logo using the same approach and shows up fine:

https://github.com/jupyter/notebook/blob/f0ec5f30e966a722a2d4a1678d3547523fea21e6/packages/notebook-extension/src/index.ts#L180-L182

**Comment by jtpio** [comment]
cc @fcollonval @brichet I see a few PR related to the settings in the `4.0.0b1`: https://github.com/jupyterlab/jupyterlab/releases/tag/v4.0.0b1

Maybe you know if they could be related to the issue mentioned above?

**Comment by brichet** [comment]
@jtpio yes it's strange.
I don't know if this is related but I can take a look at it next week.

**Comment by jtpio** [comment]
Thanks @brichet for looking into it :+1: 

> if I replace `optional: [IToolbarWidgetRegistry],` by `optional: [IToolbarWidgetRegistry, IDocumentManager],` in `kernelLogo`, the widget is not displayed either.

That's strange. At first glance I don't see why the `IDocumentManager` would have any effect here for toolbar items.

**Comment by brichet** [comment]
Actually, the problem come from another part of https://github.com/jupyterlab/jupyterlab/pull/14195:

https://github.com/jupyterlab/jupyterlab/blob/6d9217cc9681879dd822e6aaa5cedad2a648f99c/packages/settingregistry/src/settingregistry.ts#L394-L403

Everything works fine if I avoid this part for `@jupyterlab/application-extension:top-bar` plugin. And I don't know why it works if the `IDocumentManager` is not a dependency.

**Comment by jtpio** [comment]
Maybe it's a race condition, or the behavior is undefined depending on which plugin is activated first?

**Comment by jtpio** [comment]
> Maybe we should track this in a separate issue in JupyterLab so it can be fixed for the next JupyterLab beta release?

I opened https://github.com/jupyterlab/jupyterlab/issues/14366 to track this.

**Comment by brichet** [comment]
There is a workaround for this update, waiting for it to be fixed in the next release of JupyterLab:
https://github.com/jupyterlab/jupyterlab/issues/14366#issuecomment-1506505347

**Comment by jtpio** [comment]
Beta 2 seems to be fixing the settings issue mentioned above :+1: 

Now the button to add a new cell at the end of the notebook needs to be fixed. For reference it was added in https://github.com/jupyterlab/jupyterlab/pull/14109

image

**Comment by jtpio** [comment]
bot please update playwright snapshots

**Comment by jtpio** [comment]
bot please update playwright snapshots

**Comment by jtpio** [comment]
Looks like we might hit https://github.com/jupyterlab/jupyterlab/issues/14385 as well.

**Comment by jtpio** [comment]
Opened https://github.com/jupyter/notebook/issues/6852 to track adding back the "Click to add a cell" button. It was causing issues on CI with the reference snapshots on Firefox.

**Pull request merged**
