### PR TITLE
'include how to build frontend extensions'

### PR DESCRIPTION
**Pull request by Carreau**
Otherwise it's not included on RTD.

### CODE REVIEW

**Comment by willingc** [comment]
@Carreau I think this was removed at Brian's suggestion a while ago.

**Comment by Carreau** [comment]
> @Carreau I think this was removed at Brian's suggestion a while ago.

Then it's a bad one. Because that does not prevent people from writing extensions, and then rely on old tutorial that are inaccurate, and invent things.
I had many requests to to include that at JupyterDays, and have been regularly correcting people on how to build extension.

**Comment by willingc** [comment]
@carreau Let's do this. I'll add this back and see if all the notebooks build cleanly in Sphinx and we can remove the rst files. I'll ping you when I'm ready for it to be reviewed.

**Comment by ellisonbg** [comment]
Trying to catch up on this. I don't remember the original discussion - @willingc do you have a pointer to that.

The only thing I can think of is that before we started to clean up the nbextension stuff for 4.2, the entire nbextension dev experience was bad enough that I was opposed to us promoting it. However, for 4.2 the situation has improved dramaticaly and I think we should start to promote it.

**Comment by willingc** [comment]
@ellisonbg It was a verbal discussion back in December when we were trying to remove some of the duplication of documents (rst vs. ipynb) as well as get doc things back on track. I agree that 4.2 dramatically improves and we should promote it. 

I've been fighting a bit to get the notebooks to build cleanly as notebooks (vs rst files) tonight. I'll continue cleaning up and hope to have it done tomorrow.

**Comment by ellisonbg** [comment]
Hmm, I don't remember the context exactly. But as @willingc knows I am +1
on more integration of notebooks into the docs.

On Tue, Mar 22, 2016 at 10:09 PM, Carol Willing <notifications@github.com>
wrote:

> @ellisonbg <https://github.com/ellisonbg> It was a verbal discussion back
> in December when we were trying to remove some of the duplication of
> documents (rst vs. ipynb) as well as get doc things back on track. I agree
> that 4.2 dramatically improves and we should promote it.
>
> I've been fighting a bit to get the notebooks to build cleanly as
> notebooks (vs rst files) tonight. I'll continue cleaning up and hope to
> have it done tomorrow.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/pull/1250#issuecomment-200184606>
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Pull request closed without merging**
