### PR TITLE
Selenium test updates

### PR DESCRIPTION
**Pull request by ericsnekbytes**
Refactor deprecated selenium `find_element_by_*` calls to new `find_element(By.*, "blah")` API.

See also [this SO post](https://stackoverflow.com/questions/69875125/find-element-by-commands-are-deprecated-in-selenium).

### CODE REVIEW

**Comment by ericsnekbytes** [comment]
Undrafted! Trying to get the tests to complete successfully here still...

**Comment by echarles** [comment]
@ericsnekbytes  Looks like the new API does the job. I see a new error. Has this been introduced by the new selenium?

```
selenium.common.exceptions.ElementClickInterceptedException: Message: Element <div class="cell code_cell unrendered selected"> is not clickable at point (683,175) because another element <div class="modal-body"> obscures it
```

**Comment by ericsnekbytes** [comment]
> @ericsnekbytes Looks like the new API does the job. I see a new error. Has this been introduced by the new selenium?
> 
> ```
> selenium.common.exceptions.ElementClickInterceptedException: Message: Element <div class="cell code_cell unrendered selected"> is not clickable at point (683,175) because another element <div class="modal-body"> obscures it
> ```

Which one is this from? This looks like a page layout issue to me, I wouldn't expect it to be caused by the new version.

**Comment by ericsnekbytes** [comment]
Just checked the static PR and [that same failure was there](https://github.com/jupyter/notebook/runs/7450072277?check_suite_focus=true) for Ubuntu/3.9...

**Comment by echarles** [comment]
@ericsnekbytes Just merged https://github.com/jupyter/notebook/pull/6474 which has introduced a conflict here.

**Review by echarles — APPROVED** [review]
LGTM Thx @ericsnekbytes

**Pull request merged**
