### PR TITLE
Update JavaScript Notebook Extensions.rst

### PR DESCRIPTION
**Pull request by nymoorland**
Hey, I was just reading the docs to better understand the internals. This doc is really informative and interesting and I love the conversational writing style! I hope you don't mind, I made a few quick ten minute proofs/edits. My only question is if this rst doc is the right place to make the edits to populate the ipynb file? Also, in the diff I was seeing whitespace but not in the raw file. Thanks.

### CODE REVIEW

**Comment by Carreau** [comment]
Hey !

Thanks a lot for that ! I still don't quite how the docs works in this area, let me ping someone who might remember !


Does someone (@jdfreder ? @takluyver ? @ellisonbg ?) remember why we have both `.rst` and `.ipynb` in the directory ?
And if so if/how to regenerate one from the other ?If this is the case shouldn't the generated ones get a warning at the top 'Warning this is generated' ?

Thanks !

**Comment by nymoorland** [comment]
Thanks @Carreau! Fyi, this is where I originally read the docs (http://jupyter-notebook.readthedocs.org/en/latest/examples/Notebook/JavaScript%20Notebook%20Extensions.html). If you want, just take my edits and you can update it on your end without my pull request. If you prefer another way for user contributions to docs, then please advise. Maybe just filing an issue? You may want to refer to the Pandas docs where they have a whole section on that. @takluyver @ellisonbg @jdfreder

**Comment by jdfreder** [comment]
.rst gets generated by the .ipynb, so this will be overwritten on doc build.  

@nymoorland no, this is great, as long as you can make the changes to the ipynb instead.  I believe the command to build the rst docs is then `make ipynb2rst` inside the docs subdir

We probably shouldn't be checking in the .rst files because it's confusing, but I think we needed to in order for things to work with readthedocs..

**Comment by nymoorland** [comment]
Right!  readthedocs didn't have .ipynb in mind when they designed that “edit on Github” link. It would be a bit too magical if that actually worked. Alrightee, I just installed Sphinx last weekend so time to have some fun.

**Comment by Carreau** [comment]
If you don't want to re-do the change I can transpose what you did to .ipynb .
If we don't remove ipynb2rst should likely prepend a comment at top of RST file.

**Comment by nymoorland** [comment]
I think that makes sense in this case. YO
That sounds fine. If that works and makes sense, you can go ahead and do that.
Tha

**Comment by nymoorland** [comment]
Sure. That would be great and would make sense in this case. So, you can go ahead and do that. Cheers.

**Comment by nymoorland** [comment]
Sure. That would be great and would make sense in this case. So, you can go ahead and do that. Cheers.

**Comment by nymoorland** [comment]
>If you don't want to re-do the change I can transpose what you did to .ipynb .
If we don't remove ipynb2rst should likely prepend a comment at top of RST file.
 
Re-doing the change would be pretty fast for me.  I would like to play around with readthedocs and Sphinx a bit. I'm a bit busy so I may be able to get to it this weekend. I'll leave it up to you.

**Comment by nymoorland** [comment]
Awesome. Thanks. :+1:

**Comment by Carreau** [comment]
Thanks! cherry-picked and manually merged as part of #363 !

Closing !

**Pull request closed without merging**
