### PR TITLE
Temporarily add notebooks' generated rst files to version control

### PR DESCRIPTION
**Pull request by willingc**
Addresses #488 and #479 

This adds the autogenerated rst files to version control so that RTD can build without regenerating the rst files. I know that this is a change in workflow but I believe it will be temporary.

### CODE REVIEW

**Comment by minrk** [comment]
Is there a reason to not reinstate building the rst docs on RTD? When did we stop doing that?

**Comment by willingc** [comment]
@minrk The rst docs should be built on RTD. This PR makes the docs current for the end user while we troubleshoot why RTD was failing for the past month to build the docs correctly.

**Comment by minrk** [comment]
@willingc fair enough

**Comment by willingc** [comment]
Thanks @minrk. :boat: :sunrise: :ocean:

**Pull request merged**
