### PR TITLE
If kernel is broken, start a new session

### PR DESCRIPTION
**Pull request by gnestor**
Fixes https://github.com/jupyter/notebook/issues/1454

### CODE REVIEW

**Comment by gnestor** [comment]
@Carreau Can you test?

**Comment by Carreau** [comment]
> @Carreau Can you test?

Starting to test review that. Sorry for the delay !

**Comment by Carreau** [comment]
Hum... does not seem to fix it for me... Let me make sure I have your branch...

**Comment by Carreau** [comment]
Ha... it work 1/2 time...

i can do `Kernel A` -> `Broken Kernel` -> `Kernel B` successfully, but not `Kernel A` -> `Broken Kernel` -> `Kernel A`.

**Comment by Carreau** [comment]
Ok, that's because this logic is faulty as well: 

https://github.com/jupyter/notebook/blob/fd03c87f431372fc5de459ecbba00fa3f5c15765/notebook/static/notebook/js/notebook.js#L258-L260

if the kernel is broken `that.session.kernel` still point to the **old** kernel, so it does nothing and does not start a new session...

**Comment by gnestor** [comment]
@Carreau Good catch! Can you pull and test again?

**Comment by Carreau** [comment]
Whooo ! Thanks !

**Pull request merged**
