### PR TITLE
try to enable travis caching

### PR DESCRIPTION
**Pull request by Carreau**
Let's see is this speeds up the builds !

cc @minrk that was complaining on Mathjax install.

### CODE REVIEW

**Comment by Carreau** [comment]
So far so good:
```
$ export CASHER_DIR=$HOME/.casher
$ Installing caching utilities
attempting to download cache archive
fetching PR.86/cache--python-3.4.tbz
fetching master/cache--python-3.4.tbz
could not download cache
adding /home/travis/.cache/bower to cache
/home/travis/.cache/bower is not yet cached
adding /home/travis/.cache/pip to cache
/home/travis/.cache/pip is not yet cached
adding /home/travis/.npm to cache
/home/travis/.npm is not yet cached
```

**Comment by Carreau** [comment]
Still good:
```
store build cache
changes detected, packing new archive
uploading archive
```

**Comment by Carreau** [comment]
I'll re-trigger py34-js that took 4min47s.

**Comment by Carreau** [comment]
Hum... shaved of 30s, but the cache packing takes ~30s, so the actual test are 1min faster. 
Maybe more specific caching ? Thoughts ?

**Comment by Carreau** [comment]
nah wrong line, it did not change time much, half the time is still spent on  install line, I'll try to narrow that down.

**Comment by Carreau** [comment]
So travis give the timing on the side,  pip-install shrank from 155s to 95s, but expanding cache takes ~ 20s to unpack and 20s to pack...

Bower seem to use the cached folder, though it seem like the install step of the notebook itself take more than a minute and is the limiting factor. 

I'll continue to play with this.

**Comment by jdfreder** [comment]
/me Looks at the green Travis check mark without checking the code.
/me says "Looks like this is passing, I should merge it now!"

...

:trollface:

**Comment by Carreau** [comment]
Nah I give up. Travis cahing speeds up by 1min, but you loose 30 sec to download cache, and ~25s to upload it again. Not worth it.

**Comment by jdfreder** [comment]
Can you change the base image that Travis uses to a custom image?  So we could preload it with everything but the notebook.

**Comment by Carreau** [comment]
Not that I am aware of.

**Pull request closed without merging**
