### PR TITLE
Avoid trying to upload large files

### PR DESCRIPTION
**Pull request by blink1073**
Workaround for #96, I verified that I could upload files of size 15Mb in Firefox and Chrome in OSX.

screen shot 2015-10-19 at 7 45 46 pm

ping @ellisonbg @Carreau

### CODE REVIEW

**Comment by Carreau** [comment]
+1, 

I would just reword it as it does not "fail" to upload, but we actively prevent it.

**Comment by blink1073** [comment]
Better?

**Comment by Carreau** [comment]
Yep. I relaunched the failing test.

**Comment by minrk** [comment]
Nice. Thanks, guys.

**Comment by ssanderson** [comment]
ping @adzuci @richafrank.  We probably care about getting this in our next upgrade.

**Comment by tritemio** [comment]
Why the limit is 15MB? I can upload up to 35MB without issues.

I recently setup a demo service for [converting data files](http://photon-hdf5.github.io/Photon-HDF5-Converter/) using mybinder.org. The demo can still be useful with the limitation of 35MB, but it would become severely limited with an hard limit of 15MB.

Would it be possibile to lift this limit to 35MB as it is now? Thanks.

**Comment by blink1073** [comment]
@tritemio, I chose 15MB to be conservative, since cannot know for sure what the crash limit is ahead of time.

**Comment by ellisonbg** [comment]
Gmail uses 25MB as the limit. I would probably go with that.

On Wed, Oct 21, 2015 at 9:16 AM, Steven Silvester <notifications@github.com>
wrote:

> @tritemio <https://github.com/tritemio>, I chose 15MB to be conservative,
> since cannot know for sure what the crash limit is ahead of time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/pull/623#issuecomment-149890586>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Pull request merged**
