### PR TITLE
bump term.js to 0.0.7

### LINKED ISSUE #104: Paste into Jupyter terminal?
Is there any way to paste text into the Jupyter terminal?   

On chrome I'm able to copy from the terminal no problem, but can't figure out how to get text in.

The terminal is quite handy, but being unable to paste in snippets of text makes it difficult to execute larger commands.  I may just not have been able to figure out how to do it.

### PR DESCRIPTION
**Pull request by minrk**
various issues fixed, including copy/paste

closes #104

### CODE REVIEW

**Comment by Carreau** [comment]
relaunched failing tests.

**Comment by Carreau** [comment]
Travis Happy !

**Comment by rgbkrk** [comment]
:+1: :heart_eyes:

**Comment by eulerreich** [comment]
I can't seem to get paste working with the current master branch, with a clean install according to the README. The right click menu paste does nothing.

**Comment by eulerreich** [comment]
Ah in chrome I can get it working with the paste button in the upper right hand menu (the paste option is not present in the right click menu).

In firefox it still doesn't work though

**Pull request merged**
