### PR TITLE
Nested svg

### LINKED ISSUE #982: Nested SVG elements unsupported
@brainstorm opened ipython/ipython#8996

The plot shows up exactly as advertised in the README.md of the official project **when opened directly via a browser** (as in File->Open File->image.svg):

https://github.com/CSB-IG/pyveplot

But it shows only partially when trying to render it with IPython's Display SVG:

https://gist.github.com/brainstorm/25f69d7a735f6e0127ff

### PR DESCRIPTION
**Pull request by parleur**
Solve the nested svg issue FIX #982.

The old implementation use find that return an array of all svg, then silently reorganised by jquery.

This new one also suppose a unique svg parent (first element of find) but allow nested element to be untouched.

### CODE REVIEW

**Comment by Carreau** [comment]
+1, do you want to attempt to write a test ?
if no, we can take care of that.

**Comment by parleur** [comment]
Hmmm ... I am quite confuse with the bug raised in test ... what exactly does 'circleci' ?

**Comment by Carreau** [comment]
> circleci

Don't worry about it, It's an alternative to Travis. it's testing docker stuff.

**Comment by Carreau** [comment]
Failing test on travis seem like a random failure (only 1 of the 12 items was failing), I relaunched them.

**Comment by parleur** [comment]
Ha yes I also wonder about it .... Random failure ? seriously ? Thanks anyway ;-)

**Comment by Carreau** [comment]
CircleCI error is just do to Circle not respecting the `circle.yml` and running nosetest instead of docker.
Merging.

**Comment by brainstorm** [comment]
This is fantastic! Thanks to you all for the fix! :+1: 

When will this one be pushed into PyPi/Anaconda for public consumption? :)

**Comment by Carreau** [comment]
> When will this one be pushed into PyPi/Anaconda for public consumption? :)

Hum it was originally marked 5.0, I just marked 4.2, so now it should wait for backport, and then 4.2 to be released. There are unfortunately 43 issues open for 4.2 so it will take quite some time. I wouldn't expect it on PyPI/Anaconda before April.

**Pull request merged**
