### PR TITLE
Upgraded jquery-typeahead library

### PR DESCRIPTION
**Pull request by ahangsleben**
Solves https://github.com/jupyter/notebook/issues/4866
Upgraded the typeahead library and added backwards compatibility mapping through requirejs so any third party plugins leveraging "typeahead" don't break. The typeahead formatting is more or less the same as before, with minor color and spacing changes.

### CODE REVIEW

**Comment by ahangsleben** [comment]
Anyone able to review this?

**Comment by ahangsleben** [comment]
Bump

**Comment by lresende** [comment]
@ahangsleben could you please bring this up to date to master so I can merge it.

**Comment by ahangsleben** [comment]
@lresende Do you still need me to bring it up to date? Looks like you were able to merge it.

**Pull request merged**
