### PR TITLE
revert style change

### PR DESCRIPTION
**Pull request by Carreau**
Also make the marked color a variable.

### CODE REVIEW

**Comment by jdfreder** [comment]
If we are going to revert the input color change suggested by @cameronoelsen, we may want him to instead pick a darker marker color.  cc @ellisonbg

**Comment by Carreau** [comment]
I'm not sure it is worth bikeshedding on a color that will be changed if we redo the color scheme for 5.0

**Comment by cameronoelsen** [comment]
Yeah I think thats probably a good idea by @Carreau unless we want a new color. I want to, in a future iteration, get a better color palette that works well in the input cells and the website itself (along with the orange in the jupyter logo)

**Comment by jdfreder** [comment]
Makes sense

**Pull request merged**
