### PR TITLE
Update chat links to Zulip.

### PR DESCRIPTION
**Pull request by ericsnekbytes**
Updated the issue template chat link and docs page header icons to point to Zulip.

### CODE REVIEW

**Comment by ericsnekbytes** [comment]
Related to:

- https://github.com/jupyter/governance/issues/182
- https://github.com/jupyterlab/frontends-team-compass/issues/263

**Comment by jtpio** [comment]
Thanks @ericsnekbytes!

Looks like the CI failures are not related. Looks like they should have been fixed by https://github.com/jupyter/jupyter_events/pull/103.

**Comment by jtpio** [comment]
> Looks like the CI failures are not related. Looks like they should have been fixed by [jupyter/jupyter_events#103](https://github.com/jupyter/jupyter_events/pull/103).

Actually they are still failing, but with a different error.

**Comment by Carreau** [comment]
https://github.com/jupyter-server/jupyter_server/pull/1481 should fix it... but I need review, and merge and release.

**Review by jtpio — APPROVED** [review]
Thanks!

**Pull request merged**
