### PR TITLE
The root directory of the notebook server should never be hidden

### PR DESCRIPTION
**Pull request by takluyver**
Closes gh-2382

### CODE REVIEW

**Comment by choldgraf** [comment]
TYVM @takluyver :-)

**Comment by gnestor** [comment]
Tests are passing, shall I merge @takluyver?

**Comment by takluyver** [comment]
I think it's OK. I saw you talking about releasing 5.2, so I thought I'd try to get this in.

**Comment by gnestor** [comment]
Yes, after reading the whole discussion at https://github.com/jupyter/notebook/issues/2382, I'm very grateful for this 🙏

**Pull request merged**
