### PR TITLE
add npm run build:css

### LINKED ISSUE #1433: refactor npm run build:css
It is ridiculously slow, and the step it takes are also ridiculous as:

 - `npm run build:css`
   - call `python setup.py css`
      - that call jsdeps
          - that call `npm install` (to get bower)
          - that call `npm run`
             - and call `bower install`
    - then build the css by calling less. 

Like really ? Asking the **build** the css invoke 3 different installation programs in 2 different languages. The build itself take a fraction of a second, for 2 files.

### PR DESCRIPTION
**Pull request by minrk**
setup.py css is just an alias for this, so there should be no more calls back to Python from npm run build:anything

closes #1433

### CODE REVIEW

**Comment by rgbkrk** [comment]
What an improvement. It looks like the bower fetch still needs to be run prior to building CSS.

**Comment by minrk** [comment]
After a bit of fiddling, this works now. less-2.7 fixes compatibility with node-6, but introduces a sourcemap  bug (less/less.js#2896). We should upgrade LESS and restore source maps once they ship 2.7.1 with the fix.

**Comment by ellisonbg** [comment]
Great!

On Sun, May 8, 2016 at 9:03 AM, Kyle Kelley <notifications@github.com>
wrote:

> Merged #1436 <https://github.com/jupyter/notebook/pull/1436>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/pull/1436#event-653742044>
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by damianavila** [comment]
@minrk 2.7.1 is available by now...

**Pull request merged**
