### PR TITLE
Depend on nbclassic 0.4.7

### PR DESCRIPTION
**Pull request by echarles**
This PR upgrades the nbclassic dependency to 0.4.7.

### CODE REVIEW

**Comment by bnavigator** [comment]
Just wanted to let you know that from a distribution point of view this pinning and bumping out of sync is really annoying.

**Comment by echarles** [comment]
@bnavigator thx for your feedback. We have today a community call (https://github.com/jupyter/notebook-team-compass) where we can discuss that. You are welcome to join, or share here more context (why, conseqences, alternatives...)

**Comment by echarles** [comment]
We have discussed that during the community call and the conclusion was that we should define a lower boundary instead of a strict pin. I have just pushed a commit that defines `nbclassic>=0.4.7`

**Comment by bnavigator** [comment]
Thank you. I understand that sometimes it is necessary, e.g. the pinning to 0.4.5 because 0.4.6 broke it (https://github.com/jupyter/notebook/pull/6580) But when you do, please at least add a comment and explain it in your commits/pull requests. For example, #6570 is unnecessarily opaque.

**Comment by echarles** [comment]
Right, I have added a small explanation on https://github.com/jupyter/notebook/pull/6570#issuecomment-1294499684

**Comment by RRosio** [comment]
LGTM, thanks @echarles!

**Pull request merged**
