### PR TITLE
Run and select below multiselect compat.

### LINKED ISSUE #795: Run and select below + Multiselect
Does not select after the selection, select the last cell of selection.

### PR DESCRIPTION
**Pull request by jdfreder**
closes #795

### CODE REVIEW

**Comment by Carreau** [comment]
Need tests.

**Comment by jdfreder** [comment]
Tests added

**Comment by Carreau** [comment]
:-( need rebase

**Comment by jdfreder** [comment]
It's because of the test, one sec...

**Comment by jdfreder** [comment]
@Carreau rebased

**Pull request merged**
