### PR TITLE
When adapting also log the version jupyter_client is expecting.

### PR DESCRIPTION
**Pull request by Carreau**
It's still (IMHO) unclear how the adaptation goes. Like does "adapting
to protocol X.Y.Z." mean the end-result is X.Y.Z or what you
got is X.Y.Z and it's X.Y.W after adaptation.

### CODE REVIEW

**Comment by blink1073** [comment]
What if we said instead "adapting from protocol version XXX to YYY"?  I agree that the message is confusing, I had no idea it meant which version we were adapting from.

**Comment by Carreau** [comment]
> "adapting from protocol version XXX to YYY"

Yeah, even that is ambiguous 

`adapting from protocol version XXX (kernel) to YYY (client)` ?

**Comment by blink1073** [comment]
Sounds good!

**Comment by Carreau** [comment]
I've tried something from the github UI, let's see if it works.

**Comment by jasongrout** [comment]
Thanks! That message looks a lot more understandable to me.

**Pull request merged**
