### PR TITLE
Adding a split cell style into the notebook

### PR DESCRIPTION
**Pull request by cdknorow**
… menu select item

updated markdown cell to also allow split window
switched order of cell styling
moved cell style down to bottom of the dropdown menu
updated to use metadata of the cell to store the cell position
minor bug fixes
refactor code
updating tojson and from json to add persistence

### CODE REVIEW

**Comment by cdknorow** [comment]
As a summary, I added a cell_style attribute which can be set to center, left, or right. This is stored in the ipynb json format for persistence. The modification to the html sets the cell style to  float left or right at 50% width or to be 100width for centered.

screen shot 2016-04-02 at 6 52 30 pm

**Comment by cdknorow** [comment]
I'm going to figure out why unit tests are failing, add better documentation and update unit tests where appropriate. But I could use advice help if any is  available.

**Comment by ellisonbg** [comment]
I agree with @takluyver that this is probably better an an extension. That would enable us to see how users respond to it before including it for all users.

**Comment by cdknorow** [comment]
Is there anyone I can talk to about implementing this as an extension?

**Comment by takluyver** [comment]
@Carreau generally knows the most about JS extensions, and @juhasch has the most experience working with them at the [notebook extensions repo](https://github.com/ipython-contrib/IPython-notebook-extensions).

**Comment by ellisonbg** [comment]
Also @willingc knows about some of the new documentation about nbextensions
we are adding for 4.2.

On Thu, Apr 7, 2016 at 4:45 PM, Thomas Kluyver <notifications@github.com>
wrote:

> @Carreau <https://github.com/Carreau> generally knows the most about JS
> extensions, and @juhasch <https://github.com/juhasch> has the most
> experience working with them at the notebook extensions repo
> <https://github.com/ipython-contrib/IPython-notebook-extensions>.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/pull/1298#issuecomment-207139316>
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by juhasch** [comment]
As @takluyver suggests, take a look at the notebook extensions repo. Take look at the existing extensions or open an issue to discuss how to do this as an extension.

**Comment by cdknorow** [comment]
I have created an ipython extension which performs well. I will update as I have time. https://github.com/ipython-contrib/IPython-notebook-extensions/pull/573

**Comment by ellisonbg** [comment]
Great!

On Tue, Apr 12, 2016 at 12:28 AM, Chris Knorowski <notifications@github.com>
wrote:

> I have created an ipython extension which performs well. I will update as
> I have time. ipython-contrib/IPython-notebook-extensions#573
> <https://github.com/ipython-contrib/IPython-notebook-extensions/pull/573>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/pull/1298#issuecomment-208753823>
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
Ok, great, sorry to have let this slipped through, lot of things to deal with these days.

Closing as this is now an extension !

**Pull request closed without merging**
