### PR TITLE
Autoselect command palette search result if there is only one result

### LINKED ISSUE #678: Get command palette to autopick when there is a single options
Currently, if you start to type in the command palette and there is only one possibly option left, you still have to press the down arrow to select it. Pressing enter does nothing even though there is only one reasonable option. We should get the UI to use that last remaining option even without a down arrow selection of it.

### PR DESCRIPTION
**Pull request by captainsafia**
Closes #678.

Currently trying to debug an issue where `.active` styling isn't actually added when the class is added so this isn't quite ready yet.

cc: @ellisonbg

### CODE REVIEW

**Comment by captainsafia** [comment]
OK. I am no front-end Javascript expert but some Googling identifies wrapping a `setTimeout` around the style changes as away to force WebKit browsers to re-render the element. Let me know if there is a better approach.

If not, then this should be good to go.

**Comment by blink1073** [comment]
You could use `requestAnimationFrame`: https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame

**Comment by captainsafia** [comment]
Thanks @blink1073! Updated the code.

**Comment by blink1073** [comment]
No problem @captainsafia!  One nitpick, generally you don't write `window.`, since `window` is the already global namespace in the browser.

**Comment by willingc** [comment]
@blink1073 Thanks for reviewing. Since JS is not my first language, I assume that one drops ``window.`` so the call is just ``requestAnimationFrame`` with no prefix. Just leveling up my knowledge, is there a case where you would want to use ``window.`` ? :cookie:

**Comment by blink1073** [comment]
Hi @willingc, I've seen it done when you want to override a global variable, like `window.XMLHttpRequest = my_cool_replacement`, so you are explicit about what you are doing.

**Comment by willingc** [comment]
Ahh... great example. Thanks for the tip :cake: :smile:

**Comment by captainsafia** [comment]
Nitpick away, @blink1073. Code is updated.

**Comment by willingc** [comment]
@captainsafia I gave Travis a gentle nudge to restart. All green now :+1: 
@blink1073 I will leave the final review and merge to you. :city_sunset:

**Comment by blink1073** [comment]
Looks good to me, but I have no green button powers here.  :)

**Comment by willingc** [comment]
Happy to merge. Thanks @captainsafia and @blink1073 :cookie: :cookie:

**Comment by Carreau** [comment]
Try to tag on the sidebar 4.1 when it get merged into a specific release, so that it's easy to find :-P

**Comment by willingc** [comment]
@Carreau You said sidebar and all I could think of was the documentation sidebars. :laughing: Took me a good 5 minutes to realize that you meant the GitHub milestone. :-P

**Comment by Carreau** [comment]
Sorry, I did not even realized I spoke of a sidebar :disappointed:

**Pull request merged**
