### PR TITLE
test: stop caching bower

### PR DESCRIPTION
**Pull request by minrk**
see if this fixes our bower problems

### CODE REVIEW

**Comment by minrk** [comment]
just disabling cache: nope. Trying passing `--no-force-latest`

**Comment by takluyver** [comment]
Still nope :-(

**Comment by SylvainCorlay** [comment]
`--force-latest false`? https://github.com/yatskevich/grunt-bower-task/issues/7

**Comment by SylvainCorlay** [comment]
@minrk  `bower cache clean` should clean the cache.

**Comment by Carreau** [comment]
I just cleared travis caches. There is a button for that.

**Comment by minrk** [comment]
It's definitely not the Looks like @Carreau's clearing of the cache was enough. I'm not sure why disabling the caching altogether wasn't, but I'm guessing it's not something you can do in a PR maybe?

**Comment by Carreau** [comment]
I reran 1 on the job, that passed. Reopenning and rerunning everything to see.

**Comment by minrk** [comment]
Purging the cache seems to have fixed things. Master and downstream builds are passing. I don't think anything in this PR is relevant, though there is some chance that `--force-latest=false` will prevent this issue in the future.

**Pull request closed without merging**
