### PR TITLE
fix subcommand quoting on Windows in setup.py

### LINKED ISSUE #540: Build command broken on Windows
Running `setup.py build` on Windows breaks on the CSS command. This is due to excessive quoting of the command by the `run` function.

[This change](https://github.com/jupyter/notebook/commit/f175b2391ae468de39831e65674012c9543b0ccb) introduced an extra level of quoting to all commands. 

On Windows, the `lessc` command list looks like the following:

```
['lessc', '--source-map', "--include-path='E:\\Development\\sccolbert\\notebook\\notebook\\static'", 'E:\\Development\\sccolbert\\notebook\\notebook\\static\\style\\ipython.less', 'E:\\Development\\sccolbert\\notebook\\notebook\\static\\style\\ipython.min.css']
```

Which would be valid if joined with spaces. But with the extra quoting, the command is invalid on Windows:

```
lessc --source-map '--include-path='"'"'E:\Development\sccolbert\notebook\notebook\static'"'"'' 'E:\Development\sccolbert\notebook\notebook\static\style\ipython.less' 'E:\Development\sccolbert\notebook\notebook\static\style\ipython.min.css'
```

The [docs](https://docs.python.org/2/library/pipes.html#pipes.quote) for `pipes.quote` indicate that the quoting is only compatible with Unix shells.

On my machine, doing a simple space-join is sufficient to fix the breakage. But, I'm not sure if this will cause breakage on other platforms.

pinging @jdfreder @minrk

### PR DESCRIPTION
**Pull request by minrk**
Windows accepts command lists when shell=True. With this, build completes successfully on Windows.

closes #540

### CODE REVIEW

**Comment by ellisonbg** [comment]
Someone else on Windows want to test this?

**Comment by jdfreder** [comment]
I can try, one sec, need to reboot

**Comment by jdfreder** [comment]
/me begins process of setting up a dev env on Windows

**Comment by jdfreder** [comment]
Took a while, but I was finally able to reproduce the error:

capture

(note, the details are hidden by jupyter-devinstall)

Now I'm going to checkout this branch...

**Comment by jdfreder** [comment]
Success!  Thanks @minrk !

**Comment by ellisonbg** [comment]
Success == ready to merge ?

On Mon, Oct 12, 2015 at 5:17 PM, Jonathan Frederic <notifications@github.com
> wrote:

> Success! Thanks @minrk <https://github.com/minrk> !
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/pull/550#issuecomment-147525324>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by ellisonbg** [comment]
Thanks!

On Mon, Oct 12, 2015 at 5:17 PM, Jonathan Frederic <notifications@github.com
> wrote:

> Merged #550 <https://github.com/jupyter/notebook/pull/550>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/pull/550#event-433377584>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Pull request merged**
