### PR TITLE
Use jquery-ui instead of jqueryui

### LINKED ISSUE #767: Requirejs config and path names
The requirejs path shortcuts for things like `jquery-ui` defined in `page.html` don't match the actual names of the packages. For example, `jqueryui` should be `jquery-ui` etc...

It could help transitioning to the nodejs world to use the actual package names instead.

See e.g. the shims by @jdfreder here: https://github.com/ipython/ipywidgets/blob/master/ipywidgets/static/widgets/js/requirejs-shim.js#L25

@minrk @jdfreder

### PR DESCRIPTION
**Pull request by SylvainCorlay**
I also added a requirejs map so that it does not break code of people requiring jqueryui in notebook extensions. Fixes #767

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Ping @jdfreder

**Comment by Carreau** [comment]
+1 for me. 
-

**Comment by minrk** [comment]
+1. 4.1 or not, @Carreau?

**Comment by Carreau** [comment]
I'm fine with that in 4.1 I dont think it can break anything. And we can test a few weeks waiting fro multiple selection to land + Beta Period.  @ellisonbg ?

**Comment by SylvainCorlay** [comment]
Merge?

**Comment by jdfreder** [comment]
+1 to align with the npm package name

**Comment by jdfreder** [comment]
I'd push for getting this is for 4.1, then I can merge the relative PR in ipywidgets, and ipywidgets 5.0 can target notebook 4.1+.

**Pull request merged**
