### PR TITLE
Solved colour contrast issues

### PR DESCRIPTION
**Pull request by joshuazeltser**
Fixed issues #3987,  #3988, #3999, #4001, #4002 and #4003. We created acc_overwrite.less to overwrite bootstrap attributes in order to improve the colour ratio for the following buttons/links:

- "Restart and Run"
- "Terminal", "Notebook", "Kernel Name", "Shutdown" 
- "Delete"
- "Close"
- "Reset"

This PR also fixes issue #3984 by adding a focus outline around the relevant controls

### CODE REVIEW

**Comment by takluyver** [comment]
Could I ask for some before/after screenshots for visual changes like this?

**Comment by taohan16** [comment]
Screenshots for changes in the issues above
[Color_Contrast_Issue_Screenshot.pptx](https://github.com/jupyter/notebook/files/3324842/Color_Contrast_Issue_Screenshot.pptx)

**Comment by takluyver** [comment]
Thanks, but if you do this without wrapping them in Powerpoint, we can see them directly in the issue. Like this:

#4003 (red button) and #4001 (x to close dialog), before:

4003_before

After:

4003_after
-----
#4002 (the reset button on the right), before:

image3

After:

image4
-----
#3999 (Terminals header, 'Python 3' and shutdown buttons), before:

image5

After:

image6
-----
#3998 (red button) & #3987 (x to close dialog) before:
image7

After:

image8
-----
#3984 (keyboard focus on the file menu), before:

image9

After:

image10

**Comment by takluyver** [comment]
These changes all look fine to me.

**Pull request merged**
