### PR TITLE
Improve about dialog

### PR DESCRIPTION
**Pull request by yjrab**
## Suggestions for Improving about dialog UI
This is to make Jupyter Notebook's about dialog UI similar to that of Jupyter Lab's.
This is related to issue: Improve the About dialog #6552

### Modifications in base.css for .jp-AboutNotebook-version
To make sure that the spacing between the version line and external link is bigger than before and closer to how it is in Jupyter Lab. More importantly, to make sure that the default dialog box when first opened has the same height and width as the dialog box in Jupyter Lab. 
```diff
- padding: var(--jp-flat-button-padding);
+ padding-bottom: 30px;
```
### Modifications in base.css for .jp-AboutNotebook-about-externalLinks
To make sure that the spacing around the external links are consistent with how it is in Jupyter Lab.
```diff
- padding-top: 12px;
```

### CODE REVIEW

**Comment by yjrab** [comment]
## More Suggestions for Improving about dialog UI
I have other modifications to show to improve the about dialog.
Do I perform another seperate pull request?
Thank you.

**Comment by jtpio** [comment]
Thanks @yjrab!

Would it be possible to provide a before / after screenshot of the changes so it's easier to have an idea of the visual changes?

**Comment by yjrab** [comment]
Hi @jtpio, yes absolutely!

The following image is the Jupyter Notebook About Dialog Before:
Jupyter Notebook About Dialog Before

The following image is the Jupyter Notebook About Dialog After:
Jupyter Notebook About Dialog After

The following image is the Jupyter Lab About Dialog used as reference:
Jupyter Lab About Dialog

**Review by jtpio — APPROVED** [review]
Thanks!

**Pull request merged**
