### PR TITLE
iconset for Jupyter notebook

### PR DESCRIPTION
**Pull request by Carreau**
The pngs could be generated from inkscape in a loop, though for reason X
or Y, inkscape 0.91 refuse it.

The command to generate the icns is

iconutil -c icns -o ipynb.icns ipynb.iconset

 - yes the folder have to be named icon.iconset, because Apple
 - yes the file icon_111x111@2x.png is the same than icon_222x222.png
   but the @2x make a difference on retina screen, because Apple

Right now in **some conditions** the iconutils fails with out of memory error. (`... iconutil[8476] <Error>: ImageIO: _CGImageDestinationCreateWithWriter capacity parameter (16) is too large for this file format (max is 10)`)
we should try to pngcrush some images, or diminish the number of images in the folder.

cc @cameronoelsen

(there is technically no real design work, as I just took the old icons and changed the color)

### CODE REVIEW

**Comment by ellisonbg** [comment]
Can you describe what the goal of this PR is?

**Comment by Carreau** [comment]
It reintroduce icons for notebook, as they where deleted in the 3.x -> 4.x refactoring, remove the name "IPython" from the icons, replace it by "Jupyter", and change the color from bluish to orange-ish. 

Seem pretty obvious from looking at the diff.

**Comment by ellisonbg** [comment]
Hmm, not obvious to me :)

I don't recall us ever using these icons.

What did we use them for?

Did we create these ourselves?

Are we/you proposing to use them again?

**Comment by Carreau** [comment]
https://github.com/ipython/ipython/tree/3.x/docs/resources

our docs about these icons : 

http://ipython.org/ipython-doc/2/whatsnew/version0.13.html#ipython-notebook-file-icons

google search for IPtyhon notebook icon:

https://www.google.com/search?q=ipython+notebook+icon&es_sm=91&source=lnms&tbm=isch&sa=X&ved=0CAcQ_AUoAWoVChMIoauDvq3hxgIVzAWSCh3i7Qb0&biw=1280&bih=730

screen shot 2015-07-16 at 21 49 37


Used by downstream packagers (at some point in the past at least), and my Finder 
screen shot 2015-07-16 at 21 44 03

(Though it becomes harder in recent version of OS X since I brew-install my MacVim which make it painful to re-register.)

And original PR:

https://github.com/ipython/ipython/pull/1968/files

**Comment by ellisonbg** [comment]
Ahh, thanks, I missed the original PR. I will talk to Cameron about this
tomorrow.

On Thu, Jul 16, 2015 at 9:54 PM, Matthias Bussonnier <
notifications@github.com> wrote:

> https://github.com/ipython/ipython/tree/3.x/docs/resources
>
> our docs about these icons :
>
>
> http://ipython.org/ipython-doc/2/whatsnew/version0.13.html#ipython-notebook-file-icons
>
> google search for IPtyhon notebook icon:
>
>
> https://www.google.com/search?q=ipython+notebook+icon&es_sm=91&source=lnms&tbm=isch&sa=X&ved=0CAcQ_AUoAWoVChMIoauDvq3hxgIVzAWSCh3i7Qb0&biw=1280&bih=730
>
> [image: screen shot 2015-07-16 at 21 49 37]
> <https://cloud.githubusercontent.com/assets/335567/8740798/9a509f5e-2c04-11e5-9263-f752b9cc3af4.png>
>
> Used by downstream packagers (at some point in the past at least), and my
> Finder
> [image: screen shot 2015-07-16 at 21 44 03]
> <https://cloud.githubusercontent.com/assets/335567/8740764/029722c8-2c04-11e5-9b0c-d45cfd04cf91.png>
>
> (Though it becomes harder in recent version of OS X since I brew-install
> my MacVim which make it painful to re-register.)
>
> And original PR:
>
> https://github.com/ipython/ipython/pull/1968/files
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/pull/208#issuecomment-122175700>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
screen shot 2015-07-16 at 21 56 26
screen shot 2015-07-16 at 21 56 37
screen shot 2015-07-16 at 21 57 29


And how it looked with half the notebook with new icon-set. The medium sized is borked and get 24px icon instead of 32px because of the building step that fails in the middle that I need to figure out. 

The first PR is 3 year old, you had plenty of time to catch up with it :-) 

I would like to avoid  re-Bikesheding on the font and everything about the icons if possible. 

More providers that use the icons:

https://www.terminal.com/snapshot/8e1b3ab4db4640d88f69e6e0dcc875a2f955b280b740ec21c5f7f42a4bf1b7eb

https://demo.jujucharms.com/~bigdata-dev/trusty/apache-spark-notebook-16/?text=ipython-notebook

How to set icon in ubuntu:

http://ochsavidare.blogspot.com/2015/04/how-to-create-new-mime-type-for-ipython.html

So not shipping that is actually removing something that is used.

**Comment by ellisonbg** [comment]
Discussing design is not bikeshedding.

If previously provided icons are now missing, we should definitely include
them.

As we work with Cameron on the website design, we are finding that his
design skills go way beyond ours, both in quality and speed. I have no
doubt that he could do an icon set that is a massive improvement over these
(no offense to you or the original authors). The main thing I want to talk
to him about is the time effort required. Right now he is working hard on
the websites, which are pretty high priority. It may make sense to merge
the icons as is for 4.0 and then have Cameron do a redesign for 5.0.

On Thu, Jul 16, 2015 at 10:08 PM, Matthias Bussonnier <
notifications@github.com> wrote:

> [image: screen shot 2015-07-16 at 21 56 26]
> <https://cloud.githubusercontent.com/assets/335567/8740853/9c048c56-2c05-11e5-89fc-3dabe43ed9a6.png>
> [image: screen shot 2015-07-16 at 21 56 37]
> <https://cloud.githubusercontent.com/assets/335567/8740852/9c044052-2c05-11e5-8699-7c9b1ed5ab13.png>
> [image: screen shot 2015-07-16 at 21 57 29]
> <https://cloud.githubusercontent.com/assets/335567/8740858/aebfe908-2c05-11e5-8885-3e6876a04da9.png>
>
> And how it looked with half the notebook with new icon-set. The medium
> sized is borked and get 24px icon instead of 32px because of the building
> step that fails in the middle that I need to figure out.
>
> The first PR is 3 year old, you had plenty of time to catch up with it :-)
>
> I would like to avoid re-Bikesheding on the font and everything about the
> icons if possible.
>
> More providers that use the icons:
>
>
> https://www.terminal.com/snapshot/8e1b3ab4db4640d88f69e6e0dcc875a2f955b280b740ec21c5f7f42a4bf1b7eb
>
>
> https://demo.jujucharms.com/~bigdata-dev/trusty/apache-spark-notebook-16/?text=ipython-notebook
>
> How to set icon in ubuntu:
>
>
> http://ochsavidare.blogspot.com/2015/04/how-to-create-new-mime-type-for-ipython.html
>
> So not shipping that is actually removing something that is used.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/pull/208#issuecomment-122177102>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
> no offense to you 

None taken, 

> or the original authors

None taken either.

Sorry if I'm pushy, but that the kind of details that have been overlooked in the past,
and I'm not yet ready to accept that saying redesign will be done will actually
make things happen.

**Comment by takluyver** [comment]
@ellisonbg where did discussions with Cameron on this get to?

**Comment by ellisonbg** [comment]
He ca. Do it but the website is higher priority so this will likely be for 5.0

**Comment by Carreau** [comment]
It's true that the website have to be release before the 4.0 packages, and that people are already using the website to provide icons to user.

**Comment by takluyver** [comment]
Does it make sense to merge these icons for 4.0, and get redesigned ones for 5.0?

**Comment by ellisonbg** [comment]
I am fine with merging this for 4.0.

On Thu, Jul 23, 2015 at 2:19 PM, Thomas Kluyver <notifications@github.com>
wrote:

> Does it make sense to merge these icons for 4.0, and get redesigned ones
> for 5.0?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/pull/208#issuecomment-124243327>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by takluyver** [comment]
@Carreau, do you want to restore the branch so we can do that?

**Comment by Carreau** [comment]
It's deleted now. I can't reopen.

**Comment by takluyver** [comment]
Even when I delete a branch, I see a 'Restore branch' button next to the line where I deleted it. Do you not see that? It's still showing the diff, after all, so it hasn't really deleted anything.

**Comment by JanSchulz** [comment]
The commits are probably part of this repo as you canusually get the PRs pulled to your local repo with

```
[remote "origin"]
    url = https://github.com/pydata/pandas.git
    fetch = +refs/heads/*:refs/remotes/origin/*
    fetch = +refs/tags/*:refs/tags/origin/*
    fetch = +refs/pull/*/head:refs/remotes/origin/pr/*
```

So if you only want to get the commits back that probably possible.

**Comment by takluyver** [comment]
Good point, thanks @JanSchulz .

@Carreau , do you see a restore button? If not, I can make a new branch with this commit.

**Comment by Carreau** [comment]
Thank you, I am familiar with git rebase, reflog, fetch, and my global git configuration already exposes all PRs under origin/pr/<prnumber>, and are regularly fetched as a morning routine.

So I'm sure I could get the commits again if needed.

Envoyé de mon iPhone

**Pull request closed without merging**
