### PR TITLE
Docs typo

### PR DESCRIPTION
**Pull request by Carreau**
Supercede #326

### CODE REVIEW

**Comment by Carreau** [comment]
Rha... should integrate modif from https://github.com/jupyter/notebook/pull/328 too.

**Comment by Carreau** [comment]
Ok, this now should merge most of #326 and #328 by keeping commits of original authors !

Ping @minrk that have been working on the same file.

**Comment by minrk** [comment]
The rst files are there on purpose. cc @ellisonbg

**Comment by minrk** [comment]
@Carreau I'm fine closing #369 if you want to finish here, or wait for this to go in and rebase that. Either way is fine with me.

**Comment by Carreau** [comment]
Either are fine. @Jdfreder [said earlier](https://github.com/jupyter/notebook/pull/328#issuecomment-134745177) : 

> We probably shouldn't be checking in the .rst files because it's confusing, but I think we needed to in order for things to work with readthedocs.

Do we need for RTD ? I thought it was just for the backlink.

**Comment by Carreau** [comment]
And mybad, I though #369 was merged, I would have rebased on top of yours also. 
I can merge the 3 together tomorrow.

**Comment by minrk** [comment]
> Do we need them for RTD ?

Backstory, if I remember correctly:

- Committing rst was assumed necessary for RTD since we can't install pandoc via requirements.txt
  - turns out, RTD environments have pandoc
- RTD doesn't run Makefiles, it runs sphinx directly, so Make dependencies don't resolve
  - we have a hack in conf.py to trigger nb→rst even 

So we definitely don't need the rst files for RTD. After realizing it wasn't needed, I think some folks wanted to try committing rst files, to see if they made reviewing prose changes easier. But if that's not the case, I think we are out of reasons to keep them.

**Comment by Carreau** [comment]
This is a combinaison of 3 PRs that make fixes to docs and on the same file, and I don't want o get yet another PR on it, so I'm going to merge, we can iterate later.

**Comment by minrk** [comment]
Thanks, @Carreau!

**Pull request merged**
