### PR TITLE
[WIP] Toggle all line numbers, &  persist config 

### PR DESCRIPTION
**Pull request by Carreau**
Add 3 actions `show all`,`hide all`, `toggle`, expose toggle in the menu. 

Persist state to nbconfig. Also improve the config so that config option set on `Cell` apply to MD/Code/Raw unless overwritten. By a more specific config. 

Thus the line-numbering state is stored as:

```
{
  "Cell": { 
    "cm_config": {
      "lineNumbers": false
    }
  }
}
```

### CODE REVIEW

**Comment by Carreau** [comment]
Nah, bug, it erase CodeCell.cm_config default options instead of merging them, leading to no syntax highlighting,

**Comment by gnestor** [comment]
@Carreau It looks like https://github.com/jupyter/notebook/pull/1312 is continuation of this PR. If so, should we close this one?

**Comment by Carreau** [comment]
Sure, let's close.

**Comment by Carreau** [comment]
Wait technically  this one is the continuation of #1342 as this is the most recent one. 
As you like.

**Comment by gnestor** [comment]
Oh you're right! I basically reimplemented what you did in this PR! Ok, let me reconcile this and https://github.com/jupyter/notebook/pull/1676...

**Comment by gnestor** [comment]
Merged by https://github.com/jupyter/notebook/pull/1676

**Pull request closed without merging**
