### PR TITLE
Search And replace.

### PR DESCRIPTION
**Pull request by Carreau**
On top of the command palette, and WIP. 
Search and replace. 
snr-2

### CODE REVIEW

**Comment by jdfreder** [comment]
Awesome!

**Comment by Carreau** [comment]
May I just scream here super loudly ?

**Comment by Carreau** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

        ｡゜(`Д´)゜｡
    ┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻

**Comment by jdfreder** [comment]
lol, u mad bro?

**Comment by Carreau** [comment]
Yeahhhhh working, just need to cleanup things now....

**Comment by Carreau** [comment]
cc @dhermes and @michaelpacer

**Comment by Carreau** [comment]
Not working case:

```
def something():
  pass
```

```
^( ){1,3}(\w)
    $2
```

**Comment by Carreau** [comment]
Ok, mostly ready for comments.

**Comment by ellisonbg** [comment]
I didn't see a standard keyboard shortcut or Edit menu item for this. I know it may be difficult to find a good keyboard shortcut (maybe not) but there should definitely be an Edit menu item for this as it is a very common action.

Also, what would it take to enable this and the command pallette on the text editor page as well?

**Comment by Carreau** [comment]
> I didn't see a standard keyboard shortcut or Edit menu item for this.

We can bikeshed on that in another smaller PR.
It is "a very common action" but no-one was able to use it for the past 4 years, so it can wait a week. 
I would prefer to land that and test it quick then someone can decide on icon and menu naming later.

> Also, what would it take to enable this and the command palette on the text editor page as well?

What would be the point ? The command palette is made to list `actions` and work with a `keyboard_manager` which the text-editor lacks. Plus menus [do not use actions](https://github.com/ipython/ipython/pull/7285), so what would be the use of the command palette?

**Comment by ellisonbg** [comment]
I am fine merging and iterating in master. But I don't understand why you
refer to a discussion/decision about keyboard shortcuts and menu items as
bikeshedding. Do you mean that we shouldn't have the discussion?

IIRC there was a PR to add the keyboard manager to the file browser so
adding it to the text editor would also make sense? I didn't realize that
menus were not yet using actions. My logic about the commad pallette is
that as we move to a single page app where there are many different
components on a page, having a command pallette would be very useful - even
for non-notebook components.

On Sat, Aug 15, 2015 at 8:36 AM, Matthias Bussonnier <
notifications@github.com> wrote:

> I didn't see a standard keyboard shortcut or Edit menu item for this.
>
> We can bikeshed on that in another smaller PR.
> It is "a very common action" but no-one was able to use it for the past 4
> years, so it can wait a week.
> I would prefer to land that and test it quick then someone can decide on
> icon and menu naming later.
>
> Also, what would it take to enable this and the command palette on the
> text editor page as well?
>
> What would be the point ? The command palette is made to list actions and
> work with a keyboard_manager which the text-editor lacks. Plus menus do
> not use actions <https://github.com/ipython/ipython/pull/7285>, so what
> would be the use of the command palette?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/pull/285#issuecomment-131394935>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
No bikeshedding just in the sens that people will disagree on `F` vs `Shift-F`, vs `Ctrl/Cmd-Shift-F`, menu naming, position in the menu, separator or not, wether is conflit on Chrome/FF/safari/Linux, and how it is not possible to trigger the search and replace on a Mac running Linux with a physical german windows keyoard configured to use a Dvorak layout.

We can have the discussion, but I don't want to introduce (too much) non-technical change in this PR. 

The other thing that could go into the discussion is the tabindex position of the "Use regEx" and "case sensitive" button in the current dialog layout.


I fail to see the use on the command palette on the "tree" view, and I don't see any reason to have a keyboard_manager on the editor, as it is already "just" a full page codemirror instance that have it's own keybindings, and no concept of actions either. 

Though if `actions` are added to the editor or tree view, I can adapt the code of the command palette to also work there, it shouldn't be too hard.

**Comment by Carreau** [comment]
update to have 2 action, replace in all notebook, or only in selected cells.

**Comment by Carreau** [comment]
Last version of the UI, with lots of though and improvement. 

`Search` is focused by default. 
`Tab` switch focus to `Replace`.

So you can easily search/replace with keyboard. 

CaseSensitive / RegEx toggle are just before Search, So just a Shift-Tab Away.

I did it this way because having this after Search, or Replace was too far, or annoying. to tab 4 times to go to replace. 

Case &  RegEx auto focus input after toggle, which reduce the number of keypress needed.

The replace only is selected cells is just after the Replace field which make it easy to toggel just before validating. 

Recap of flow, Search selected by default. Shift Tab, does of course inverse of Tab. 
CaseSensitive-[tab]->RegEx Toggle
RegEx Toggle-[tab]->Search
**Search**-[tab]->Replace
Replace-[tab]->Only Selected toggle

Switch Case Sensitive -> Search focused.
Switch RegEx -> Search focused.
Switch only selected cell -> replace focused.


screen shot 2015-08-18 at 13 29 11

**Comment by nymoorland** [comment]
@Carreau Super!  Really happy(https://github.com/jupyter/notebook/issues/261)  about this + #266 = super power Jupyter notebook:) Your implementation looks very cool.

**Comment by Carreau** [comment]
> @Carreau Super! Really happy(#261) about this + #266 = super power Jupyter notebook:) Your implementation looks very cool.

Thanks.

**Comment by Carreau** [comment]
Ping.

Otherwise I'll merge and wait for complaints.

**Comment by ellisonbg** [comment]
+1, we know we want this, let's merge and iterate in master if we need to.

On Wed, Aug 26, 2015 at 1:52 AM, Matthias Bussonnier <
notifications@github.com> wrote:

> Ping.
>
> Otherwise I'll merge and wait for complaints.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/pull/285#issuecomment-134902074>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
You haven't pushed the Green Button in a while, do I leave you to do it ?

**Comment by Carreau** [comment]
(and also why are you up so early)

**Comment by ellisonbg** [comment]
Merged! - woke up at 6:30 for no particular reason - my mind must have sensed my inbox filling up :)

**Comment by ellisonbg** [comment]
any many thanks for the work on this one - super useful!

On Wed, Aug 26, 2015 at 7:31 AM, Matthias Bussonnier <
notifications@github.com> wrote:

> (and also why are you up so early)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/pull/285#issuecomment-135041091>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
Great !
Let me now open a PR with the keybinding, menu, and toolbar icon.

**Comment by Carreau** [comment]
> Merged! - woke up at 6:30 for no particular reason - my mind must have sensed my inbox filling up :)

:-) I can ping you on more things.

**Comment by bollwyvl** [comment]
Hadn't even seen this! how cool.

I assume the modal is not the long-term home for this? Being able to use the search results as a navigation mechanism for long documents is really key. Currently, I think the pager answers the mail, while a phosphor panel would make long term sense...

**Comment by Carreau** [comment]
the "Search" part is not really done, the replace mostly. I would use search through the browser it is more reliable.

**Comment by GandalfSaxe** [comment]
Sorry for my ignorance, but how do I get access to find and replace? How do I open this "Command palette" (Googling "jupiter command palette" gives me nothing useful). I could really use some find and replace functionality in my work right now where I have to rename a bunch of variables.

Regarding versions:
Clicking about in Jupiter Notebook: "The version of the notebook server is 4.0.4"
conda update jupyter: "jupyter                   1.0.0                    py34_0"

**Comment by minrk** [comment]
@GandalfSaxe this hasn't been released, so you would need to install the notebook from master, or wait for the release of 4.1.

**Comment by GandalfSaxe** [comment]
@minrk Ah fair enough. Looking forward to it :+1:

**Comment by eulerreich** [comment]
@Carreau I know you said the "search part" is not really done, but I'd love if you could implement the look ahead and look behind features of regex.

**Comment by geekan** [comment]
Awesome work!

**Pull request merged**
