### PR TITLE
Add 5.2.1 to changelog

### PR DESCRIPTION
**Pull request by gnestor**

### CODE REVIEW

**Comment by gnestor** [comment]
@Carreau Care to review/merge this one, too?

**Comment by mpacer** [comment]
I'm happy to merge this.

**Comment by Carreau** [comment]
Thanks !

**Comment by gnestor** [comment]
@meeseeksdev backport to 5.2.1

**Comment by gnestor** [comment]
I manually backported to 5.2.1 👍

**Pull request merged**
