### PR TITLE
Update xterm.js to 1.1.2

### PR DESCRIPTION
**Pull request by yuvipanda**
Major feature upgrade is that IMEs now work, so people
can type non-latin characters into them!

Also has:
   - Better mouse support
   - Signed releases
   - Scrollbar

https://github.com/sourcelair/xterm.js/releases/tag/1.1.2

### CODE REVIEW

**Comment by minrk** [comment]
1.1 apparently hasn't been published to npm yet. 1.0 is still the [latest release](https://www.npmjs.com/package/xterm).

**Comment by yuvipanda** [comment]
Yup, filed https://github.com/sourcelair/xterm.js/issues/244

**Comment by yuvipanda** [comment]
They fixed the issue with their release script and pushed 1.1.3, so I've updated to that. Waiting for travis now.

**Comment by yuvipanda** [comment]
Are these just flaky tests? I don't see how they are related...

**Comment by takluyver** [comment]
Yup, looks like flaky tests. I just re-ran the failing one, and it passed. Let's see if this helps with #1724.

**Pull request merged**
