### PR TITLE
Use attachment:path instead of attachment://path

### PR DESCRIPTION
**Pull request by mgeier**
This partly reverts #1659, see also #1655 and https://github.com/jupyter/nbformat/pull/77.

### CODE REVIEW

**Comment by takluyver** [comment]
What will happen with notebooks already saved with references to attachments including the `//`?

**Comment by mgeier** [comment]
I guess those attachments wouldn't be shown until their URIs are fixed.

**Comment by takluyver** [comment]
Do we want to try to automatically fix them? Or even just provide a script which people can run to fix them?

**Comment by minrk** [comment]
> Do we want to try to automatically fix them?

since the spec has been out for a few versions, I would.

**Comment by michaelpacer** [comment]
Would the automatic fix "change" them in memory (& so, as displayed) immediately when the notebook is loaded and then overwrite the file system version only when the file is saved? Or would it attempt to rewrite the file immediately upon loading?

**Comment by takluyver** [comment]
Probably the former - that's already how we handle upgrading notebooks in an older format, for instance.

**Comment by mgeier** [comment]
I hope you don't expect me to implement the auto-fix behavior ... I don't know enough JavaScript to do that!

**Comment by takluyver** [comment]
I suspect it could be done in Python. Maybe it belongs in the nbformat package rather than here. @minrk would it be worth doing a minor version bump on the format and using the conversion machinery to implement that?

Probably the trickiest bit would be parsing the markdown to modify it. I proposed a [markdown passthrough](https://github.com/lepture/mistune-contrib/pull/9/files) for mistune, but it's not yet accepted. I expect we could get away with regexes, as `attachment://` is only likely to occur in this context.

**Comment by minrk** [comment]
We could possibly do it in nbformat. In any case, it doesn't need to be in this PR.

**Comment by michaelpacer** [comment]
Can you point to examples of the conversion machinery as it already exists in nbformat that would be used in this case? 

I'm trying to figure out how to handle the header id convention change across nbconvert and the notebook, and while I was planning on trying to do it without altering ipynb metadata, I'm gradually coming to the conclusion that that may be impossible to do without breaking things in unintuitive ways once file sharing comes into the picture.

**Comment by takluyver** [comment]
Here's some of the conversion machinery:
https://github.com/jupyter/nbformat/blob/master/nbformat/v4/convert.py

None of it currently reaches into the markdown to modify things, though - it's all about modifying the JSON structure of the notebook. So it may not be all that useful.

**Comment by minrk** [comment]
I think it will probably be simpler to have the warning and shim in this repo. We can do that in another PR.

**Pull request merged**
