### PR TITLE
support routing updating outputs with display_id

### PR DESCRIPTION
**Pull request by minrk**
notebook implementation of jupyter/jupyter_client#209

- display(id=...) always adds something to the page
- update(id=...) updates only existing things on page

A single display_id can be used multiple times on the page, and all instances will be updated and kept in sync.

related: https://github.com/ipython/ipykernel/pull/204 , https://github.com/ipython/ipython/pull/10048

### CODE REVIEW

**Comment by minrk** [comment]
An example notebook for testing with these messages (doesn't require IPython PRs): https://nbviewer.jupyter.org/gist/minrk/1a1e56a611f1ff1e2645f733bdd0e381

**Comment by minrk** [comment]
Only missing thing: updating execute_result.

**Comment by rgbkrk** [comment]
Looking good!

**Comment by minrk** [comment]
No longer WIP, this should be all set, now.

**Pull request merged**
