### PR TITLE
add Restart & Run All action

### PR DESCRIPTION
**Pull request by minrk**
- to actions list, so it can be bound to a shortcut
- to Kernel menu

I made Notebook.restart_kernel return a promise that resolves when the kernel becomes ready, which makes the implementation a bit easier, but I can back that out if people would prefer.

closes ipython/ipython#4468

### CODE REVIEW

**Comment by rabernat** [comment]
:+1:

**Comment by Carreau** [comment]
+1, 

that remind me that I had a close PR with more actions.

**Comment by ellisonbg** [comment]
+1 from me.

**Comment by Carreau** [comment]
the second possibility was to have a restart and run all button on the kernel-restart modal dialog.

**Pull request merged**
