### PR TITLE
enhancement: `IPython.toolbar.add_buttons_group` should return the new button group

### PR DESCRIPTION
**Pull request by jcb91**
For any code which wishes to do further customization to the group without having to find it through jQuery again

### CODE REVIEW

**Comment by jdfreder** [comment]
This is okay for a minor release since the function wasn't returning anything anyways, @Carreau @minrk any object to merging this for 4.1?  Marking as 4.2 until I hear +1 from someone else.

**Comment by minrk** [comment]
No objection for 4.1.

**Comment by Carreau** [comment]
No objection for 4.1 either. 
I was just not looking at thing tagged 4.2 or later.

**Comment by jdfreder** [comment]
Thanks @jcb91 !

**Comment by jcb91** [comment]
welcome ^_^

**Pull request merged**
