### PR TITLE
Have _ defined in notebook.transutils

### PR DESCRIPTION
**Pull request by hroncok**
Fixes https://github.com/jupyter/notebook/issues/2798

### CODE REVIEW

**Comment by hroncok** [comment]
This allows to use _ from anywhere.

**Comment by hroncok** [comment]
@takluyver from https://github.com/jupyter/notebook/issues/2798#issuecomment-324465518:

> Yup, that's the i18n machinery - `_` is injected into the builtins to look up translations, but evidently it isn't when the docs build imports the notebook.
>
> Thanks for the report, it's embarrassing that we haven't caught that already. I suspect it can be worked around by modifying `conf.py` - if you get that working, please do send us a PR.

If that's the case, maybe importing it in `notebook/services/contents/manager.py` is not a good idea and injecting it to builtins in `conf.py` would be preferred. Thoughts?

**Comment by takluyver** [comment]
I'd be inclined to import it from `conf.py` - calling `.install()` special cases `_` to be used throughout the code without importing it. Importing it into one file risks that it will spread to another file and we'll be back to problems with the docs.

Adding it to builtins is not very Pythonic, though, so other people might disagree with me.

**Comment by hroncok** [comment]
So, let's keep the transutils module but import `_` from it in `conf.py` instead of `notebook/services/contents/manager.py`?

**Comment by takluyver** [comment]
Sounds OK. I don't think it needs to import `_` in conf, though; the important bit is that `trans.install()` gets called before we try importing other notebook modules.

**Comment by hroncok** [comment]
Well adding the following code to the end of `conf.py` actually makes sure it gets called before everything else:

```python
# import before any doc is built, so _ is guaranteed to be injected
from notebook.transutils import _
```

It's a bit black magik and can be exchanged with `from notebook import transutils`.

**Comment by takluyver** [comment]
Does "import notebook.transutils" work too?

**Comment by hroncok** [comment]
Yes it does. Amended.

**Comment by takluyver** [comment]
Thanks! Could I ask you to add a one-line docstring to the `transutils` module? Other than that, I think this is ready to go.

**Comment by hroncok** [comment]
Done. Also copied the copyright header from `utils.py`

**Comment by takluyver** [comment]
Super, thanks.

**Comment by hroncok** [comment]
AppVeyor fails with bower. Seems not related.

**Comment by takluyver** [comment]
Yup. I clicked rebuild just so it goes green.

I'm not addicted to little green CI check marks. I can quit any time I like.

**Pull request merged**
