### PR TITLE
Add PERMITTED_MIMETYPES to mimetype check

### PR DESCRIPTION
**Pull request by captainsafia**
This is a follow up to #1143 and #1408.

I think the easiest and most scalable solution would be to set up a PERMITTED_MIMETYPES array that we can add strange but editable mime types to. We can build the download and edit functionality on top of this.

cc: @takluyver @minrk

### CODE REVIEW

**Comment by minrk** [comment]
Makes sense. I would probably do `EDIT_MIMETYPES`, since it's specifically for those that should go to the editor.

**Comment by captainsafia** [comment]
Updated.

**Comment by takluyver** [comment]
I suspect that it may be better to offer an 'edit' button for each file, separate from the view/download action, and then introduce a blacklist for files that we know we can't edit, rather than this whitelist approach. There are files like HTML and SVG that we can open in a text editor, but the user might also want to view them in the browser.

**Comment by minrk** [comment]
Edit button + blacklist sounds great in the long run. Merging this as an incremental improvement, which we can remove when the edit button is added.

**Pull request merged**
