### PR TITLE
add support for fullscreen print-friendly and dock-able quickhelp

### PR DESCRIPTION
**Pull request by jcb91**
close ipython/ipython#8141

### CODE REVIEW

**Comment by Carreau** [comment]
Hi Sorry for not looking into this, this got lost in the high number of PR next to the end of the queue. I suppose that @ellisonbg and @cameronoelsen want to have some look at the design, but I can perfectly see a usecase for an always visible version of the help panel with available shortcuts.

**Comment by Carreau** [comment]
@ellisonbg and @cameronoelsen you seem to have never seen the mention here.  Sorry about that @jcb91. @ellisonbg Maybe some of your current student can have a look at that ?

**Comment by gnestor** [comment]
@jcb91 Thanks for PR 10 months ago (I'm sorry this hasn't been addressed sooner). I just [merged](https://github.com/gnestor/notebook/tree/pr/633) the master into your PR and resolved conflicts. I tested your PR by:

1. Click Help > Keyboard Shortcuts
2. Click "Printable view"

After which I hit the following error:

```
Uncaught TypeError: this.build_side_panel is not a function
    QuickHelp.show_keyboard_shortcuts @ quickhelp.js:191
    (anonymous function) @ menubar.js:267
    dispatch @ jquery.min.js?v=ccd0edd…:5
     y.handle @ jquery.min.js?v=ccd0edd…:5
```

Does `this.build_side_panel` depend on an nbextension that I may not have installed?

**Comment by gnestor** [comment]
@jcb91 I see that this depends on [help_panel extension](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/blob/master/src/jupyter_contrib_nbextensions/nbextensions/help_panel/readme.md). I enabled it and verified that it was loaded in the notebook (`Loading extension: help_panel/help_panel`) but I'm still running into the same error.

**Comment by Carreau** [comment]
Thanks a lot @gnestor for helping go through all these PR backlogs.

I wondering wether targeting this directly for JupyterLab would be easier ?
JupyterLab have already the concept of panels, so it might be simpler to implement there, 
and make use of all the nice features of JupyterLab.

**Comment by gnestor** [comment]
@Carreau Please loop in people who can help make that call. 

@jcb91 In order to merge this with notebook (vs. merging it with the help_desk extension), it would need to conditionally display the "Printable view" button based on whether the required extension is enabled.

**Comment by Carreau** [comment]
>> I wondering wether targeting this directly for JupyterLab would be easier ?
>>  JupyterLab have already the concept of panels, so it might be simpler to implement there, 
>> and make use of all the nice features of JupyterLab.

> @Carreau Please loop in people who can help make that call.

I guess that would be me, @ellisonbg and @jasongrout if final decision there need to be.

**Comment by jasongrout** [comment]
Thanks @Carreau for pinging us directly to make sure we saw this. I think it would be a good idea to have a help page in JupyterLab with the keymap configuration (first we'd have to write a plugin to expose the keymaps, and then it would automatically be printable, I think, as a normal tab).

I'll let you guys make the call on whether it is feasible to get this working in the new notebook, but exposing a list of the keybindings in JupyterLab is definitely in the plans. See https://github.com/jupyter/jupyterlab/issues/695

**Comment by ellisonbg** [comment]
I don't think we should implement this in the classic notebook. And honestly, I think if we want something is print friendly, we should just create a PDF that we can ship. RStudio has done a spectacular job with those:

https://www.rstudio.com/resources/cheatsheets/

Can someone open an issue on jupyter/jupyterlab with the cheatsheet idea? Closing this one.

**Comment by jcb91** [comment]
@gnestor apologies for the delay replying here, I've been a little tied up this week. Anyway, looks like this is already receiving attention elsewhere...

**Pull request closed without merging**
