### PR TITLE
Update to JupyterLab 4.2.0b0

### PR DESCRIPTION
**Pull request by jtpio**
Update to https://github.com/jupyterlab/jupyterlab/releases/tag/v4.2.0b0

### CODE REVIEW

**Comment by jtpio** [comment]
Now seeing the following error in the dev tools console, which seems related to https://github.com/jupyterlab/jupyterlab/pull/14683 :

image

**Comment by jtpio** [comment]
cc @afshin do you know what the main DOM differences are between the `defer` and `full` modes? Gonna look into updating the CSS to fix https://github.com/jupyter/notebook/issues/7231.

For now the browser default scrollbar is still missing.

**Comment by krassowski** [comment]
> [Default to defer for now](https://github.com/jupyter/notebook/pull/7312/commits/2bba503cd053b88f1e3bf2c8d6b7fced4cb7d637)

I think this is fine. There is less of a user benefit for Notebook than for Lab from using full windowed mode because users may have 10 long notebooks in Lab opened in a single browser tab, but not in Notebook.

**Comment by jtpio** [comment]
Is there a way to set the windowing mode without going through the settings?

Otherwise this also changes the windowing mode used in JupyterLab, as the settings are shared between notebook and lab. There is a similar issue with Notebook setting the file browser checkboxes by default, which currently also show up in lab (https://github.com/jupyterlab/jupyterlab/issues/14623).

**Comment by krassowski** [comment]
It looks like you would need to override the `notebookConfig` in factory: https://github.com/jupyterlab/jupyterlab/blob/6152e3a5f94d728ccd2727d6d8413f12ddafb669/packages/notebook-extension/src/index.ts#L1867-L1898

An alternative would be to use setting transforms to change the default value temporarily.

**Comment by jtpio** [comment]
> An alternative would be to use setting transforms to change the default value temporarily.

Looks like that would mean using a setting transform for the `@jupyterlab/notebook-extension:tracker`, which is the one defining the `windowingMode`? https://github.com/jupyterlab/jupyterlab/blob/6152e3a5f94d728ccd2727d6d8413f12ddafb669/packages/notebook-extension/schema/tracker.json#L816
But the setting file does not seem to have `jupyter.lab.transform` set to `true`.

**Comment by jtpio** [comment]
Opened https://github.com/jupyter/notebook/issues/7318 to have a look later to not block this PR.

If anyone would like to help with this or https://github.com/jupyter/notebook/issues/7231 that would be appreciated, thanks!

**Pull request merged**
