### PR TITLE
Patch CodeMirror 5.22

### LINKED ISSUE #1967: Spacing in text cells on Safari 10
I've been encountering some formatting strangeness in any text block (code and markdown) on Safari v10.0.1 using jupyter notebook v4.3.0.

Spaces in text are not being show. Once characters are placed the formatting looks correct. I've included an example below:

jupytercode_spacing

If there are characters on the line after the cursor, there don't seem to be any issues. I haven't been able to replicate the issue in Chrome. 

Possibly related to #1943. Thanks for any help!

### LINKED ISSUE #2037: Python 3.6 f-strings break notebook syntax highlighting
Using Notebook v4.3.1, use of f-strings (PEP 498, Python 3.6) breaks syntax highlighting for the remaining code in a given cell.

Is Jupyter curently unable to handle this syntax? I would imagine that this issue would have been raised by others were this the case.

Using OS X, brewed Python 3.6.0, Firefox 50.

```
$ python3 --version
Python 3.6.0
$ jupyter --version
4.2.1
$ jupyter-notebook --version
4.3.1
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.2
BuildVersion:	16C68
```

### PR DESCRIPTION
**Pull request by minrk**
closes #2037

TODO:

- [x] fix #1967

@gnestor this PR is from a branch on trunk, so feel free to play around with fixes for the cursor issue in this PR

I can't work on a fix because I can't reproduce #1967 (Safari 10.0.3 or 10.2 preview)

Assuming the fix is simple, we might consider a patch-level backport to 4.3.2 as well.

### CODE REVIEW

**Comment by gnestor** [comment]
@minrk I've submitted https://github.com/jupyter/notebook/pull/2068 to merge into this branch.We shoud have a fix on CodeMirror's end eventually (see https://github.com/codemirror/CodeMirror/issues/4454), but this will allow us to ship 4.3.2.

**Comment by minrk** [comment]
Maybe it would be better to patch in-place after `bower install`, rather than track the modified file whole? Otherwise, I think we're at risk of clobbering the file on bower install, etc. That might be related to the error on Windows, I'm not sure.

**Comment by gnestor** [comment]
How would you do this patch in place? Put the patched `codemirror.js` somewhere in the repo and then `cp path/to/codemirror.js notebook/static/components/codemirror/lib`? And where would you run this script? In setup.py? I don't think any npm scripts are being run after `bower install`...

**Comment by gnestor** [comment]
Let's include this in 4.3.2 👍

**Comment by minrk** [comment]
@gnestor merged #2068

**Comment by gnestor** [comment]
@meeseeksdev backport to 4.x

**Comment by Carreau** [comment]
> @meeseeksdev backport to 4.x

Ok, I think I see the bug ...

**Pull request merged**
