### PR TITLE
Notebook v7 scaffolding

### PR DESCRIPTION
**Pull request by jtpio**
Closes https://github.com/jupyter/notebook/pull/6293

Fixes https://github.com/jupyter/notebook-team-compass/issues/6

See https://github.com/jupyter/notebook/issues/6266 for more context about the 7.0 pre-release plan.

This is the initial step towards implementing the Notebook v7 JEP: https://jupyter.org/enhancement-proposals/79-notebook-v7/notebook-v7.html

This PR incorporates the RetroLab code base, which currently lives in https://github.com/jupyterlab/retrolab.
More specifically, it is based on the following PR which served as a preparation for the move: https://github.com/jupyterlab/retrolab/pull/323

Fixes https://github.com/jupyterlab/retrolab/issues/313

## Try it on Binder

[Binder](https://mybinder.org/v2/gh/jtpio/notebook/notebook-7?urlpath=tree)

image

## TODO

- [x] Bump version to `7.0.0a0`
- [x] Update `README.md` with relevant information about the different stream of works (classic notebook v6 and notebook v7)
- [ ] Update issue templates (https://github.com/jupyter/notebook-team-compass/issues/7)
- [x] Fix docs build
- [x] Update or remove the example notebook on Binder
- [x] Cleanup files that are not needed anymore (previous CI workflows, templates...)

### CODE REVIEW

**Comment by jtpio** [comment]
Pushed some cleanup to the docs to:

- Update to the PyData Sphinx Theme so it's consistent with the other Jupyter projects
- Remove outdated docs about v6 frontend extensions
- Link to the Jupyter Server for server related config and security 

The documentation preview for this PR is available on ReadTheDocs: https://jupyter-notebook--6294.org.readthedocs.build/en/6294/

**Comment by jtpio** [comment]
The docs and README can still be iterated on, but should be "good enough" for now.

The missing item for this PR would be to update the issue templates to properly orient users and not confuse them.
Although this could also be postponed until we have the first 7.0 pre-release out. Since the new Notebook v7 is not installable for now anyway.

cc @Zsailer @afshin @jweill-aws if you have any input / ideas on this, since this is something that was discussed at the notebook and triage meetings

**Comment by jtpio** [comment]
Marking as ready for review so folks can already have a look and try it on Binder:

https://mybinder.org/v2/gh/jtpio/notebook/notebook-7?urlpath=tree

**Comment by Zsailer** [comment]
AMAZING work here, @jtpio! I've checked out this PR locally and confirm everything is working beautifully. 

As for a thorough code review, it's nearly impossible with 627 files! 😅 

Here's what I propose... let's merge and iterate. This looks good to go from my perspective. We can address issues as they arise and move faster after this update.

Thank you for all of this hard work, Jeremy—this can't be said enough! You deserve all the credit here! 🎉

**Comment by jasongrout** [comment]
> +28,194 −90,947

Wow. Just wow. Hats off to you!

**Comment by jtpio** [comment]
> (I'll merge Monday if you don't have any issues with this @jtpio).

Sounds good to me, let's wait until Monday and I'll let you merge @Zsailer. Thanks!

**Comment by choldgraf** [comment]
YayYesGIF

**Comment by fperez** [comment]
Wohooo!!! Hats off @jtpio for this incredible work, thank you so much.  Next time we catch up, 🍺/🍷/☕ on me! The entire project is going to benefit immensely from resolving this choke point, and this sets up a great path forward.

Also big thank you to @Zsailer, the rest of the team, and all the users who patiently have given input and feedback. Still a lot of work ahead to ensure that we have no regressions in the user experience, but this is where we wanted to be now! Exciting times ahead.

**Pull request merged**
