### PR TITLE
This is my contributions to Jupyter Notebook.

### PR DESCRIPTION
**Pull request by AlyMuhammadAly**

### CODE REVIEW

**Comment by kevin-bates** [comment]
Hi @AlyMuhammadAly.  This PR includes quite a few unsolicited changes and hints that it was meant to be merged into a forked repository.  Is it your intention to have this merged in this repository - jupyter/notebook?  If so, I would recommend opening specific issues to which the pull request will address.  This will help us understand your intention.

If this was not meant to be merged into the repository, please close the pull request, and we'll look forward to your contribution another time.

**Comment by AlyMuhammadAly** [comment]
Hey @kevin-bates. Yeah I would like to contribute in Project Jupyter. What aspects my PR should have addresses?

**Comment by kevin-bates** [comment]
There are significant changes that require an explanation as to how they are beneficial and why they are necessary.  Once provided we can review the changes.

Also, please resolve the conflicts by updating to the latest master branch.

Thank you.

**Comment by AlyMuhammadAly** [comment]
Thank you @kevin-bates

**Pull request closed without merging**
