### PR TITLE
Deselect items after successful actions on notebook list page.

### PR DESCRIPTION
**Pull request by nvdv**
Currently selected items are not deselected after successful actions. This PR fixes this issue.

### CODE REVIEW

**Comment by Carreau** [comment]
@ellisonbg , I seem to remember asking for that, but it was decided not-to. 
Do yo remember the reason why ?

**Comment by ellisonbg** [comment]
Don't remember the details of the discusion, but after using it for a
while, I fully agree that we should deselect after actions.

On Thu, Feb 4, 2016 at 3:29 PM, Matthias Bussonnier <
notifications@github.com> wrote:

> @ellisonbg <https://github.com/ellisonbg> , I seem to remember asking for
> that, but it was decided not-to.
> Do yo remember the reason why ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/pull/1044#issuecomment-180101736>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by minrk** [comment]
Travis is being a little grumpy, but it's not related to this PR.

**Comment by nvdv** [comment]
Great! Thanks!

**Pull request merged**
