### PR TITLE
Remove duplicate dependencies in bower

### PR DESCRIPTION
**Pull request by gnestor**
An initial stab at https://github.com/jupyter/notebook/issues/1778. 

I've enabled "Allow edits from maintainers" so feel free to push to this PR...

### CODE REVIEW

**Comment by blink1073** [comment]
I think you might also need to remove some script tags in `page.html` or the other templates.

**Comment by gnestor** [comment]
@blink1073 Good call! Now what about instances where `moment` is defined using RequireJS (https://github.com/jupyter/notebook/blob/53ab302a98ca24b2a104a4ec7bb049ff4dcc1a09/notebook/static/base/js/utils.js#L6)? Will that look for `moment` in node_modules? If not, then we need to replace these with `import moment from 'moment'`...

**Comment by blink1073** [comment]
It looks like `moment` is in the compiled WebPack bundle, so the code looks good as is.  Eventually, it may make sense to switch to all-CommonJS code in `static/`.

**Comment by gnestor** [comment]
@blink1073 @minrk It looks like the tests are failing because ["ReferenceError: Can't find variable: Promise" ](https://travis-ci.org/jupyter/notebook/jobs/162261858#L922). I removed `es6-promise` from bower so now the tests will rely on webpack for `Promise`. Is the source not being built by webpack before tests are run?

**Comment by minrk** [comment]
I believe the source is built by webpack in the tests, otherwise no js would be loaded because the main.js would be undefined.

**Comment by blink1073** [comment]
Is the webpack even running?  It looks like the build is failing because you need to `require('webpack')` in order to use the `ProvidePlugin`.

**Pull request merged**
