### PR TITLE
Don't assume that application/ mime types are editable

### PR DESCRIPTION
**Pull request by takluyver**
The application media type includes many common binary files like `application/zip` and `application/pdf`. I don't think we can assume it's editable.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Except for application/json

**Comment by takluyver** [comment]
We're already whitelisting several relevant extensions, like `.json`, `.jsonld` and `.geojson`. Is that likely to be enough, or do you want to whilelist `application/*+json` as well?

**Comment by takluyver** [comment]
I've included a check for `+json` and `+xml` mimetypes.

**Comment by rgbkrk** [comment]
> Is that likely to be enough, or do you want to whilelist application/*+json as well?

That sounds good, though it looks like you've already added it. 😄

**Pull request merged**
