### PR TITLE
[WIP] add appveyor.yml to start running tests on Windows

### PR DESCRIPTION
**Pull request by minrk**
Doesn't pass yet, but it at least starts running the tests.

- use conda-forge scripts to bootstrap conda
- I don't plan to run the js tests, just the Python ones

### CODE REVIEW

**Comment by takluyver** [comment]
:+1:

**Comment by willingc** [comment]
Tests are good 👍

**Comment by Carreau** [comment]
I enabled appveyor, it should ignore any branch without an `appveyor.yml` but I hope it will start to build this PR.

Thanks @minrk for starting this !

**Comment by takluyver** [comment]
Closing and reopening to see if that triggers Appveyor.

**Comment by takluyver** [comment]
Several test failures on Py2 appear to relate to it not getting errors when expected.

**Comment by Carreau** [comment]
> Closing and reopening to see if that triggers Appveyor.

Oh, good point. 

> Several test failures on Py2 appear to relate to it not getting errors when expected.

Easy path forward if skip-if windows for now.

**Comment by minrk** [comment]
I only got Python 3 passing yesterday, but moved on before dealing with the Python 2 errors. I'll spend a little more time figuring out exactly why they fail before punting to skip-on-Windows. It's a bit odd that they only fail on Python 2.

**Comment by minrk** [comment]
Most of the py2 failures were because of a real bug. The samefile backport in #1142 didn't work on Python 2 because the stat fields used (st_ino, st_dev) always return 0 on Windows + Python 2, causing the function to return True for any pair of files. It works everywhere else, though. I updated the method to do case-insensitive file comparison plus full stat comparison (times included), and use the stdlib `os.path.samefile` where it's available (everywhere but win+py2).

An alternative would be to make the fill-in same file just do `path == other_path`, which would never give a false-positive, but would disable renaming with only changed case on Windows + Python 2. Since it works correctly on Python 3 due to samefile, I don't have a huge preference either way.

**Comment by takluyver** [comment]
I also have no strong preference, but since you have this working now, let's go with this unless/until we want to do something different. :-)

**Comment by Carreau** [comment]
Yeahh ! Thanks @minrk  !

**Pull request merged**
