### PR TITLE
Contrast of inline code snippets: issue #4010

### PR DESCRIPTION
**Pull request by joshuazeltser**
Fixed issue #4010. We changed line 61 #d4d4d4 to #757474 to meet the required ratio

### CODE REVIEW

**Comment by taohan16** [comment]
The Screenshots of changes for issue #4010
[Issue_4010_Screenshot.pptx](https://github.com/jupyter/notebook/files/3324912/Issue_4010_Screenshot.pptx)

**Comment by joshuazeltser** [comment]
Before:
image

After:
image

**Comment by takluyver** [comment]
This one looks wrong - making the background darker decreases the text contrast. I struggle to read the text in the 'after' screenshot with corrected-to-normal vision.

**Comment by taohan16** [comment]
> This one looks wrong - making the background darker decreases the text contrast. I struggle to read the text in the 'after' screenshot with corrected-to-normal vision.

Hi, thanks for your comment. I agree with you that this does not look good, but it does reach the contrast ratio of 4.5:1 for both black and white. I think a better way to fix this is to change the color to white when using "``" in markdown. How do you feel about the below one?
image

**Comment by takluyver** [comment]
My experience with situations that limit contrast (projectors, screens in bright sunlight) is that it's much easier to read dark text on a light background than the other way round.

Is there actually a problem with how it was before? I think only the contrast between the text and the background is important - the distinction between the light grey background of the inline code and the white of the page is only cosmetic, as far as I'm concerned. If an automated tool decided this was a problem, I think we can override it with a human judgment that it's not.

**Comment by taohan16** [comment]
> My experience with situations that limit contrast (projectors, screens in bright sunlight) is that it's much easier to read dark text on a light background than the other way round.
> 
> Is there actually a problem with how it was before? I think only the contrast between the text and the background is important - the distinction between the light grey background of the inline code and the white of the page is only cosmetic, as far as I'm concerned. If an automated tool decided this was a problem, I think we can override it with a human judgment that it's not.

I agree with you. The contrast between the background and the text is more important to ensure the contents are readable. So maybe we can close this PR.

**Comment by takluyver** [comment]
OK, thanks.

**Comment by takluyver** [comment]
Actually, I think issue #4010 is talking about the ratio between the text and the background, looking at the  screenshot it shows. But the hex codes it shows are not the same as those involved here. If you've got more time to work on this, could you check the text/background contrast again, and record on #4010 whether it's still a problem or not.

**Comment by taohan16** [comment]
For the inline code snippets in current Jupyter, the HEX code is #EFF0F1.
The contrast ratio between it and the white background is 1.1:1.
The contrast ratio between it and the black text is 18.4:1.

The background color for the inline code snippets after changing is #757474.
The contrast ratio between it and the white background is 4.7:1.
The contrast ratio between it and the black text is 4.5:1.

**Comment by takluyver** [comment]
Thanks, I've closed #4010 on the grounds of that.

**Pull request closed without merging**
