### PR TITLE
Support for moving multiple cells up and down

### PR DESCRIPTION
**Pull request by mathieu1**
Builds on #266 and #269. Looking into slight improvements for focus behavior, comments welcome.

### CODE REVIEW

**Comment by ellisonbg** [comment]
Can you describe more what this is trying to do. We already have support for moving cells up and down. Also, focus in the notebook is a *horrifically* complicated matter and we find that it is nearly impossible to make any changes to how it is handled without breaking other things. Can you clarify what you changed about focus?

**Comment by Carreau** [comment]
> Can you describe more what this is trying to do.

Title: Support for moving **multiple** cells up and down.

I don't see any focus behavior change in the code.

**Comment by ellisonbg** [comment]
Ahhh, that helps!

On Sun, Sep 20, 2015 at 11:06 AM, Matthias Bussonnier <
notifications@github.com> wrote:

> Can you describe more what this is trying to do.
>
> Title: Support for moving *multiple* cells up and down.
>
> I don't see any focus behavior change in the code.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/pull/464#issuecomment-141816265>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by mathieu1** [comment]
Haven't changed anything about the focus yet, working on it at the moment. I will give a detailed explanation of how things are done, it seems it's possible to do with only very mild modifications.

**Comment by mathieu1** [comment]
As described in the full commit message:

- Problem : the cell that has the focus (cursor) can be either at the top or at the bottom of the selection. For example if the cursor is at the top and we move cells down, then only the cursor will remain visible if the selection goes below the visible screen.

- Solution : before moving cells down, possibly reverse the direction of the selection so that the cursor is necessarily the bottom cell of the selection.

In the end, I'm not messing around with focus but rather with the selection.

**Comment by mathieu1** [comment]
Thanks to selection reversal, also fixed the following strange copy/paste behavior:
- start with three cells A, B, C
- select C, then B then A using shift+K
- The result of `copy` and `paste below` is A, A, B, C, B, C (the cells are copied below the cursor, which is A)

**Comment by Carreau** [comment]
Thanks, will try to get some time to review in depth. 

I'm marking as 4.1, to try to get that in if we review test it enough, but we might bump it to later otherwise. 
I'm assigning @takluyver as he wrote the multi-selection originally, but he might be busy for the next 2 weeks, so if someone else can test/have a look.

**Comment by ellisonbg** [comment]
We are looking at changing how multiple-selection is done. See #597 

Let's see how that pans out first before moving on this. That PR also enables discontinuous selections of cells, which could compilcate things like moving up/down.

**Comment by takluyver** [comment]
I think that with the ability to select more than one cell, cut/copy/paste is a more powerful, flexible and understandable metaphor for rearranging cells than moving the selection up and down. So I'd actually try to remove/deprecate the shortcuts to move cells up and down.

**Comment by ellisonbg** [comment]
Yeah, I mostly agree with this. The only place where multi-cell cut, copy,
paste is still a little annoying is if you want to insert cells at the top
of a notebook. But virtually no UIs that I know of offer move up/down for
things like this. It would also free up space in the toolbar.

On Tue, Dec 1, 2015 at 7:45 AM, Thomas Kluyver <notifications@github.com>
wrote:

> I think that with the ability to select more than one cell, cut/copy/paste
> is a more powerful, flexible and understandable metaphor for rearranging
> cells than moving the selection up and down. So I'd actually try to
> remove/deprecate the shortcuts to move cells up and down.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/pull/464#issuecomment-161005993>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
Moving multiple cells up.down is now a simple side-effect of the continuous selection. 
As then you "just" need to move the cell before the selection to just after to "move the selection up" and vice versa. 

So unless I'm misunderstanding, I'm going to close this, 

Thanks a lot though for the time you've put into that, and sorry these commit don't land into master. 

Waiting for your next PR !

(closing, feel free to reopen if I missed something)

**Pull request closed without merging**
