### PR TITLE
bump MathJax to 2.6

### LINKED ISSUE #1010: Update MathJax to 2.6, to fix rendering artifact
I'm getting the following artifact of a right sided border on rendered MathJax objects (see image) from either manually created LaTeX code (as below) or Sympy expression renderings. The issue happens for both $ ... $ and $$ ... $$ items, where the MathJax object terminates; inline expressions will have them, too. This was working on the default install of a plain Python installation, using notebook 4.1, but under the most recent distribution of Anaconda, it's happening.

image

```
We know the following:
* Side AC = 500
* Side BC = 300
* Angle BAC = 36.87
* Angle ABC = 90

We need to solve for side AB. As described, angle BAC allows us to use its cosine ratio to derive AB, since it is adjacent and side AC is opposite angle ABC, and thus is the hypotenuse:

$\cos{36.87} = \frac{AB}{500}$  
$500 \cdot \cos{36.87} = AB$  
$400 = AB$

We can check this using the Pythagorean theorem, $a^2 + b^2 = c^2$:  
$300^2+b^2=500^2$  
$90000+b^2=250000$  
$b^2 = 160000$  
$b = \sqrt{160000} = 400$
```

I can do further testing, but wanted to at least bring this to your attention first to know if I'm missing something here. Thanks!

### PR DESCRIPTION
**Pull request by minrk**
closes #1010

### CODE REVIEW

**Comment by minrk** [comment]
4.2 or 5.0?

**Comment by takluyver** [comment]
Here's the what's new page for MathJax 2.6:
https://docs.mathjax.org/en/latest/whats-new-2.6.html

The changes in there sound OK for us to put in a 4.2 release to me.

**Comment by ellisonbg** [comment]
I think that looks fine.

On Mon, Feb 1, 2016 at 1:29 PM, Thomas Kluyver <notifications@github.com>
wrote:

> Here's the what's new page for MathJax 2.6:
> https://docs.mathjax.org/en/latest/whats-new-2.6.html
>
> The changes in there sound OK for us to put in a 4.2 release to me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/pull/1032#issuecomment-178203155>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by minrk** [comment]
From the release notes, it looks like maybe we should switch the output to CommonHTML, but that's probably something to save for 5.0.

**Comment by Carreau** [comment]
Need backport.

**Pull request merged**
