### PR TITLE
Display "trusted" and "untrusted" notifications

### PR DESCRIPTION
**Pull request by gnestor**
demo

### CODE REVIEW

**Comment by gnestor** [comment]
Related #1293

**Comment by gnestor** [comment]
@ellisonbg Can you UX test?

**Comment by minrk** [comment]
Nice!

**Comment by Carreau** [comment]
I would just not use the `danger` alternative as it's ok to view an untrusted notebook. 
I think the "classic" color for both trusted and untrusted might be sufficient. 

One of the reasons I think it would be better, is that I don't want this action to become something which is click-through like the UAC on windows. 

Otherwise +1

**Comment by takluyver** [comment]
Yeah, we want to avoid creating something like the MS Office 'enable macros' dialog. Because when the computer says "This might be incredibly dangerous!", users say:

**Comment by gnestor** [comment]
Ok, I just switched to classic style. 

One other question: Should the "Trusted" notification hide itself after a second or so? Currently both notifications are persisted. If the "Untrusted" notification is clicked, the user is prompted to trust the notebook. If the "Trusted" notification is clicked, the notification hides.

**Comment by Carreau** [comment]
> Ok, I just switched to classic style.
> 
> One other question: Should the "Trusted" notification hide itself after a second or so? Currently both notifications are persisted. If the "Untrusted" notification is clicked, the user is prompted to trust the notebook. If the "Trusted" notification is clicked, the notification hides.

I think that's a good compromise. And it's easy enough to change afterward if needed. 
It will keep the UI clean for most users. 

As @Phyks was the first initiator of that, we can ask him his thoughts.

**Comment by takluyver** [comment]
I think I'd be inclined to hide both notifications after 10 seconds or so, to reduce the likelihood that the user will click to make it go away. Even in blue, it still stands out quite a bit.

**Comment by Carreau** [comment]
>  Even in blue, it still stands out quite a bit.

Both are gray now. IIUC.

**Comment by Phyks** [comment]
Sorry, I did not have much time to follow it and eventually work on my PR lately. 

Thanks @gnestor ! Your design implementation looks really cool!

I would not be in favor of hiding the untrusted notification, as the user may not notice it before it goes away and the main purpose of this feature was to have an indication that a notebook is untrusted. The trusted notification can go away though I think, as it results from either a user interaction, or a notebook being safe from the loading.

**Comment by gnestor** [comment]
Ok, @minrk should we switch this to 5.0 before merging or leave it at 4.3 and backport?

**Comment by Carreau** [comment]
> Ok, @minrk should we switch this to 5.0 before merging or leave it at 4.3 and backport?
>  Show all checks

You can leave at 4.3 for the backport script to find the issue. 
Or you can decide this is only 5.0 and is a "new feature" and leave switch the milestone to 5.0; 
Up to you. I'm fine considering that as "new feature" and having one less thing to backport.

**Comment by gnestor** [comment]
> I'm fine considering that as "new feature" and having one less thing to backport.

That's what I was thinking...

**Comment by Carreau** [comment]
Yeah !

**Pull request merged**
