### PR TITLE
Remove hard-coding of jupyter_config_dir config_dir at the notebookapp level

### LINKED ISSUE #880: Some problems with the ConfigManager
Context: I have written a custom config manager but it is not working... looking for the issue, I just tried to setup the env path directly in the current ConfigManager with no luck:

If I change https://github.com/jupyter/notebook/blob/master/notebook/services/config/manager.py#L17
from
`return os.path.join(jupyter_config_dir(), 'nbconfig')`
to
`return os.path.join(ENV_CONFIG_PATH[0], 'nbconfig')`

and I still can not load the nbconfig from that conda env... ideas???

Even more, if I try the option the option
`--ConfigManager.config_dir=path/to/env/etc/jupyter/nbconfig` when I launch the notebook, it keeps loading nbconfig from the `./jupyter` user space...

What other `jupyter_config_dir`-related things am I missing? Or it could be some problem upstream this? maybe `traitlets`?

pinging @takluyver @minrk who are probably interested, also @jdfreder who chat a little bit with me about this, although everyone else in invited :wink:

### PR DESCRIPTION
**Pull request by damianavila**
Let's the ConfigManager to deal with the default value, so we can make it truly configurable.

Pretend to fix #880

### CODE REVIEW

**Comment by damianavila** [comment]
Can we make this into 4.1? It is a bug fix from my point of view and more importantly, this allow to use custom ConfigManager, which provides an alternative until things related with the nbextensions discussion in #878 and https://github.com/jupyter/enhancement-proposals/pull/7 is decided. 
ping @minrk @ellisonbg @takluyver and @Carreau

**Comment by minrk** [comment]
It's a reasonable question. I'm not sure if we want to actually make that configurable, or remove the `config=True` flag that doesn't actually work, but we should do one or the other. Allowing sub-config locations to be themselves configurable makes it a lot easier for it to get into an inconsistent state. I would like to see a pretty good reason for frontend config and server config to have to be in different locations for these to be allowed to be separated.

**Comment by Carreau** [comment]
I'm fine with this fix. Should we merge that and Beta2 or RC ? Min ?

**Comment by minrk** [comment]
I'm fine with it as well, I'd just like a bit more explanation of cases where it's reasonable for frontend config to come from a different place from the rest.

**Comment by Carreau** [comment]
Like other place from the disk ? I'm sure Continuum have deployment where config is on a db, or a separate folder network-mounted, or sync via dropbox.

**Comment by minrk** [comment]
This is only relevant for breaking up user-config, so that part of user-config can come from JUPYTER_CONFIG_DIR, but the nbconfig subdir is broken out of the config dir.

Arbitrary other data sources already works fine by specifying `NotebookApp.config_manager_class`.

I'm mainly wondering what the case is where you would want to specify where `nbconfig` is, but not JUPYTER_CONFIG_DIR.

**Comment by damianavila** [comment]
OK, I (and others) have written some nbextensions ans server extensions and package them with conda. Because we want to keep thing isolated inside prefix, we want to read the config from `prefix/etc/jupyter/nbconfig` but some people have also some other extensions installed in the user space (aka. `./jupyter`).
If we setup the `jupyter_config_dir` to just look into `prefix/etc/jupyter` all the "user" activated extensions are not loaded... this is the main discussion in the other issues.

To workaround this for the moment I have written a custom ConfigManager which is able to read the "user" space but also the prefix space, so people can install our extensions and also install other extensions as well and have all of them activated beyond the place where the the config is located.

In fact, I have no problem to avoid `config=True` at the native ConfigManager, we can remove that if you feel it will bring problems. The main thing is avoid hardcoding the `config_dir` at the notebookapp level so anyone can come up with another ConfigManager implementation to support their use case (like the one I described above) or any other use case that the the native implementation does not support...

**Comment by minrk** [comment]
OK

**Comment by ellisonbg** [comment]
After working on this stuff yesterday, I have doubts about doing this ... Will reply more later when I fully wake up...

**Comment by damianavila** [comment]
Thanks!

I still believe we should continue discussing the whole thing in the other threads and  the meeting, but at least this one gives people an entry point to workaround the whole thing if the resolution we come up later do not satisfy their requirements.

**Pull request merged**
