### PR TITLE
quickhelp usability: 2 boxes

### PR DESCRIPTION
**Pull request by Carreau**
As described By Jess and Brian in #533

### CODE REVIEW

**Comment by Carreau** [comment]
ping @jhamrick @ellisonbg

**Comment by Carreau** [comment]
screen shot 2015-10-26 at 11 21 16

**Comment by ellisonbg** [comment]
Great! Merging.

**Comment by jhamrick** [comment]
Sorry I didn't see this sooner, but yeah, looks great! :+1:

**Comment by willingc** [comment]
@ellisonbg @Carreau I think we want to edit MacOS to Mac or Mac OS X

**Comment by Carreau** [comment]
> @ellisonbg @Carreau I think we want to edit MacOS to Mac or Mac OS X

Meh, no strong feeling. 

If there is a PR I'll merge it, though.

**Pull request merged**
