### PR TITLE
use splitext to remove extension from notebook name

### PR DESCRIPTION
**Pull request by minrk**
extension may not be .ipynb.

cc @rossant @gregcaporaso

closes ipython/ipython#8510

### CODE REVIEW

**Comment by Carreau** [comment]
We have the following around line 2100.
```
    Notebook.prototype.ensure_extension = function (name) {
        if (!name.match(/\.ipynb$/)) {
            name = name + ".ipynb";
        }
        return name;
    };
```

**Comment by takluyver** [comment]
So, do we merge this as is? It seems substantially more complex to do the right thing when adding the extension, so perhaps it should be left to another PR.

**Comment by minrk** [comment]
We know the extension used to load the file, so we should be able to ensure the extension doesn't change.

**Comment by minrk** [comment]
ensure_extension should preserve the existing extension, rather than enforcing .ipynb unconditionally

**Pull request merged**
